import { randomUUID } from "node:crypto";
import { Router, type Request } from "express";
import multer from "multer";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { validateOdometer } from "../../domain/rules.js";
import { requireAnyPermission, requirePermission } from "../../middleware/authorize.js";
import { detectSupportedImageMime } from "../../lib/imageFiles.js";
import { readPrivateFile, saveHandoverEvidence } from "../../lib/fileStorage.js";

export const handoversRouter=Router();
const evidenceUpload=multer({storage:multer.memoryStorage(),limits:{files:1,fileSize:6*1024*1024}}).single("photo");
const idParam=(v:string|string[]|undefined)=>typeof v==="string"?v:null;
const number=()=>`HO-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomUUID().slice(0,8).toUpperCase()}`;
type HandoverRow={id:string;organizationId:string;handoverNumber:string;vehicleId:string;fromDriverId:string|null;toDriverId:string|null;type:string;status:string;odometerKm:number;fuelPercent:number|null;location:string|null;exteriorCondition:string|null;interiorCondition:string|null;tyreCondition:string|null;accessories:unknown;conditionNotes:string|null;createdByUserId:string;acceptedByUserId:string|null;acceptedAt:Date|null;rejectedReason:string|null;closedAt:Date|null;createdAt:Date;updatedAt:Date};
async function driverForUser(organizationId:string,userId:string){return prisma.driver.findFirst({where:{organizationId,userId,archivedAt:null},select:{id:true,userId:true,fullName:true}});}
async function getRow(organizationId:string,id:string){return (await prisma.$queryRaw<HandoverRow[]>`SELECT * FROM "VehicleHandover" WHERE "organizationId"=${organizationId}::uuid AND "id"=${id}::uuid`)[0]??null;}
function canViewSelf(req:Request,row:HandoverRow,driverId:string|null){return req.auth!.permissions.has(PERMISSIONS.HANDOVER_VIEW)||Boolean(driverId&&(row.toDriverId===driverId||row.fromDriverId===driverId));}

handoversRouter.get("/",requireAnyPermission(PERMISSIONS.HANDOVER_VIEW,PERMISSIONS.HANDOVER_ACCEPT_SELF),async(req,res)=>{
 const driver=req.auth!.permissions.has(PERMISSIONS.HANDOVER_VIEW)?null:await driverForUser(req.auth!.organizationId,req.auth!.userId);if(!req.auth!.permissions.has(PERMISSIONS.HANDOVER_VIEW)&&!driver)return res.json({items:[]});
 const rows=req.auth!.permissions.has(PERMISSIONS.HANDOVER_VIEW)
  ?await prisma.$queryRaw<Array<HandoverRow&{registrationNumber:string;make:string;model:string;fromDriverName:string|null;toDriverName:string|null}>>`SELECT h.*,v."registrationNumber",v."make",v."model",fd."fullName" AS "fromDriverName",td."fullName" AS "toDriverName" FROM "VehicleHandover" h JOIN "Vehicle" v ON v."id"=h."vehicleId" LEFT JOIN "Driver" fd ON fd."id"=h."fromDriverId" LEFT JOIN "Driver" td ON td."id"=h."toDriverId" WHERE h."organizationId"=${req.auth!.organizationId}::uuid ORDER BY h."createdAt" DESC LIMIT 300`
  :await prisma.$queryRaw<Array<HandoverRow&{registrationNumber:string;make:string;model:string;fromDriverName:string|null;toDriverName:string|null}>>`SELECT h.*,v."registrationNumber",v."make",v."model",fd."fullName" AS "fromDriverName",td."fullName" AS "toDriverName" FROM "VehicleHandover" h JOIN "Vehicle" v ON v."id"=h."vehicleId" LEFT JOIN "Driver" fd ON fd."id"=h."fromDriverId" LEFT JOIN "Driver" td ON td."id"=h."toDriverId" WHERE h."organizationId"=${req.auth!.organizationId}::uuid AND (h."fromDriverId"=${driver!.id}::uuid OR h."toDriverId"=${driver!.id}::uuid) ORDER BY h."createdAt" DESC LIMIT 100`;
 return res.json({items:rows});
});

handoversRouter.post("/",requirePermission(PERMISSIONS.HANDOVER_CREATE),async(req,res)=>{
 const input=z.object({vehicleId:z.string().uuid(),fromDriverId:z.string().uuid().optional(),toDriverId:z.string().uuid().optional(),type:z.enum(["ISSUE","RETURN","TRANSFER"]),odometerKm:z.number().int().min(0),fuelPercent:z.number().int().min(0).max(100).optional(),location:z.string().max(250).optional(),exteriorCondition:z.string().max(2000).optional(),interiorCondition:z.string().max(2000).optional(),tyreCondition:z.string().max(2000).optional(),accessories:z.array(z.string().max(100)).max(50).optional(),conditionNotes:z.string().max(3000).optional()}).refine(v=>v.fromDriverId||v.toDriverId,{message:"A handover must identify the outgoing or receiving driver."}).refine(v=>v.type!=="ISSUE"||Boolean(v.toDriverId),{message:"Vehicle issue requires a receiving driver."}).refine(v=>v.type!=="RETURN"||Boolean(v.fromDriverId),{message:"Vehicle return requires the returning driver."}).refine(v=>v.type!=="TRANSFER"||Boolean(v.fromDriverId&&v.toDriverId&&v.fromDriverId!==v.toDriverId),{message:"Transfer requires different outgoing and receiving drivers."}).parse(req.body);
 const vehicle=await prisma.vehicle.findFirst({where:{id:input.vehicleId,organizationId:req.auth!.organizationId,archivedAt:null},select:{id:true,currentOdometerKm:true,registrationNumber:true}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});validateOdometer(vehicle.currentOdometerKm,input.odometerKm);
 const driverIds=[input.fromDriverId,input.toDriverId].filter((x):x is string=>Boolean(x));if(driverIds.length){const count=await prisma.driver.count({where:{organizationId:req.auth!.organizationId,id:{in:driverIds},archivedAt:null}});if(count!==new Set(driverIds).size)return res.status(400).json({error:"One or more drivers do not belong to this organization."});}
 const id=randomUUID(),handoverNumber=number(),now=new Date();await prisma.$executeRaw`INSERT INTO "VehicleHandover"("id","organizationId","handoverNumber","vehicleId","fromDriverId","toDriverId","type","status","odometerKm","fuelPercent","location","exteriorCondition","interiorCondition","tyreCondition","accessories","conditionNotes","createdByUserId","createdAt","updatedAt") VALUES (${id}::uuid,${req.auth!.organizationId}::uuid,${handoverNumber},${vehicle.id}::uuid,${input.fromDriverId??null}::uuid,${input.toDriverId??null}::uuid,${input.type},'PENDING',${input.odometerKm},${input.fuelPercent??null},${input.location??null},${input.exteriorCondition??null},${input.interiorCondition??null},${input.tyreCondition??null},${JSON.stringify(input.accessories??[])}::jsonb,${input.conditionNotes??null},${req.auth!.userId}::uuid,${now},${now})`;
 await audit(req,{action:"CREATE",recordType:"VEHICLE_HANDOVER",recordId:id,newValue:{handoverNumber,vehicleId:vehicle.id,registrationNumber:vehicle.registrationNumber,type:input.type,fromDriverId:input.fromDriverId??null,toDriverId:input.toDriverId??null,odometerKm:input.odometerKm,fuelPercent:input.fuelPercent??null}});return res.status(201).json({id,handoverNumber,status:"PENDING"});
});

handoversRouter.post("/:id/decision",requireAnyPermission(PERMISSIONS.HANDOVER_MANAGE,PERMISSIONS.HANDOVER_ACCEPT_SELF),async(req,res)=>{
 const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid handover id."});const input=z.object({decision:z.enum(["ACCEPTED","REJECTED"]),comments:z.string().max(1500).optional()}).parse(req.body);const row=await getRow(req.auth!.organizationId,id);if(!row)return res.status(404).json({error:"Handover not found."});if(row.status!=="PENDING")return res.status(409).json({error:"Only a pending handover can be accepted or rejected."});
 if(!req.auth!.permissions.has(PERMISSIONS.HANDOVER_MANAGE)){const driver=await driverForUser(req.auth!.organizationId,req.auth!.userId);if(!driver||row.toDriverId!==driver.id)return res.status(403).json({error:"Drivers may accept only handovers issued or transferred to them."});}
 if(input.decision==="REJECTED"&&!input.comments)return res.status(400).json({error:"A rejection reason is required."});const now=new Date();await prisma.$executeRaw`UPDATE "VehicleHandover" SET "status"=${input.decision},"acceptedByUserId"=${req.auth!.userId}::uuid,"acceptedAt"=${input.decision==="ACCEPTED"?now:null},"rejectedReason"=${input.decision==="REJECTED"?(input.comments??"Rejected"):null},"updatedAt"=${now} WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`;
 await audit(req,{action:input.decision==="ACCEPTED"?"ACCEPT":"REJECT",recordType:"VEHICLE_HANDOVER",recordId:id,oldValue:{status:row.status},newValue:{status:input.decision},...(input.comments?{reason:input.comments}:{})});return res.json({id,status:input.decision});
});

handoversRouter.post("/:id/close",requirePermission(PERMISSIONS.HANDOVER_MANAGE),async(req,res)=>{const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid handover id."});const row=await getRow(req.auth!.organizationId,id);if(!row)return res.status(404).json({error:"Handover not found."});if(!["ACCEPTED","REJECTED"].includes(row.status))return res.status(409).json({error:"Handover must be accepted or rejected before closure."});const now=new Date();await prisma.$executeRaw`UPDATE "VehicleHandover" SET "status"='CLOSED',"closedAt"=${now},"updatedAt"=${now} WHERE "id"=${id}::uuid`;await audit(req,{action:"CLOSE",recordType:"VEHICLE_HANDOVER",recordId:id,oldValue:{status:row.status},newValue:{status:"CLOSED"}});return res.json({id,status:"CLOSED"});});

handoversRouter.post("/:id/evidence",(req,res,next)=>evidenceUpload(req,res,error=>error?next(error):next()),async(req,res)=>{const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid handover id."});const row=await getRow(req.auth!.organizationId,id);if(!row)return res.status(404).json({error:"Handover not found."});const driver=await driverForUser(req.auth!.organizationId,req.auth!.userId);if(!canViewSelf(req,row,driver?.id??null)||(!req.auth!.permissions.has(PERMISSIONS.HANDOVER_MANAGE)&&!req.auth!.permissions.has(PERMISSIONS.HANDOVER_ACCEPT_SELF)))return res.status(403).json({error:"You are not authorized to add evidence to this handover."});if(!req.file)return res.status(400).json({error:"Choose a handover photo."});const mime=detectSupportedImageMime(req.file.buffer);if(!mime)return res.status(415).json({error:"Handover evidence must be a valid JPEG, PNG or WebP image."});const evidenceId=randomUUID();const locator=await saveHandoverEvidence({organizationId:req.auth!.organizationId,handoverId:id,buffer:req.file.buffer,mime});await prisma.$executeRaw`INSERT INTO "HandoverEvidence"("id","organizationId","handoverId","kind","storageLocator","mimeType","originalName","sizeBytes","uploadedByUserId") VALUES (${evidenceId}::uuid,${req.auth!.organizationId}::uuid,${id}::uuid,'CONDITION_PHOTO',${locator},${mime},${req.file.originalname||"handover-photo"},${req.file.size},${req.auth!.userId}::uuid)`;await audit(req,{action:"UPLOAD",recordType:"HANDOVER_EVIDENCE",recordId:evidenceId,newValue:{handoverId:id,mime,bytes:req.file.size}});return res.status(201).json({id:evidenceId,mime,sizeBytes:req.file.size});});

handoversRouter.get("/:id/evidence",requireAnyPermission(PERMISSIONS.HANDOVER_VIEW,PERMISSIONS.HANDOVER_ACCEPT_SELF),async(req,res)=>{const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid handover id."});const row=await getRow(req.auth!.organizationId,id);if(!row)return res.status(404).json({error:"Handover not found."});const driver=req.auth!.permissions.has(PERMISSIONS.HANDOVER_VIEW)?null:await driverForUser(req.auth!.organizationId,req.auth!.userId);if(!canViewSelf(req,row,driver?.id??null))return res.status(404).json({error:"Handover not found."});const items=await prisma.$queryRaw<Array<{id:string;kind:string;mimeType:string;originalName:string;sizeBytes:number;createdAt:Date}>>`SELECT "id","kind","mimeType","originalName","sizeBytes","createdAt" FROM "HandoverEvidence" WHERE "organizationId"=${req.auth!.organizationId}::uuid AND "handoverId"=${id}::uuid ORDER BY "createdAt" DESC`;return res.json({items:items.map(x=>({...x,fileEndpoint:`/api/handovers/evidence/${x.id}/file`}))});});

handoversRouter.get("/evidence/:evidenceId/file",requireAnyPermission(PERMISSIONS.HANDOVER_VIEW,PERMISSIONS.HANDOVER_ACCEPT_SELF),async(req,res)=>{const evidenceId=idParam(req.params.evidenceId);if(!evidenceId)return res.status(400).end();const rows=await prisma.$queryRaw<Array<{storageLocator:string;mimeType:string;handoverId:string;fromDriverId:string|null;toDriverId:string|null}>>`SELECT e."storageLocator",e."mimeType",e."handoverId",h."fromDriverId",h."toDriverId" FROM "HandoverEvidence" e JOIN "VehicleHandover" h ON h."id"=e."handoverId" WHERE e."organizationId"=${req.auth!.organizationId}::uuid AND e."id"=${evidenceId}::uuid`;const item=rows[0];if(!item)return res.status(404).end();if(!req.auth!.permissions.has(PERMISSIONS.HANDOVER_VIEW)){const driver=await driverForUser(req.auth!.organizationId,req.auth!.userId);if(!driver||![item.fromDriverId,item.toDriverId].includes(driver.id))return res.status(404).end();}const buffer=await readPrivateFile(item.storageLocator);const mime=detectSupportedImageMime(buffer);if(!mime)return res.status(500).end();res.set({"Content-Type":mime,"Content-Disposition":"inline","Cache-Control":"private, max-age=300","X-Content-Type-Options":"nosniff"});return res.send(buffer);});
