import { Router } from "express";
import { prisma } from "../../lib/prisma.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { requirePermission } from "../../middleware/authorize.js";

export const recordHubRouter=Router();

type SearchItem={type:string;id:string;title:string;subtitle:string;status?:string;href:string};
type Battery={id:string;serialNumber:string;brand:string;model:string|null;status:string;position:string|null;warrantyEnd:Date|null;currentVehicleId:string|null};
type Handover={id:string;handoverNumber:string;vehicleId:string;fromDriverId:string|null;toDriverId:string|null;type:string;status:string;odometerKm:number;fuelPercent:number|null;createdAt:Date;acceptedAt:Date|null;registrationNumber?:string;fromDriverName?:string|null;toDriverName?:string|null};
type Vault={id:string;entityType:string;entityId:string;documentType:string;title:string;referenceNumber:string|null;issuer:string|null;expiryDate:Date|null;mimeType:string;originalName:string;sizeBytes:number;createdAt:Date};
type Approval={id:string;definitionId:string;moduleKey:string;recordId:string;requesterUserId:string;status:string;currentStep:number;requestedAt:Date;definitionName:string;roleName:string;allowRequester:boolean;minApprovals:number;requesterName:string};

recordHubRouter.get("/search",async(req,res)=>{
 const q=String(req.query.q??"").trim();if(q.length<2)return res.json({items:[]});const org=req.auth!.organizationId,p=req.auth!.permissions,like=`%${q}%`;const items:SearchItem[]=[];
 if(p.has(PERMISSIONS.BATTERY_VIEW)){const rows=await prisma.$queryRaw<Array<Battery&{registrationNumber:string|null}>>`SELECT b."id",b."serialNumber",b."brand",b."model",b."status",b."position",b."warrantyEnd",b."currentVehicleId",v."registrationNumber" FROM "BatteryAsset" b LEFT JOIN "Vehicle" v ON v."id"=b."currentVehicleId" WHERE b."organizationId"=${org}::uuid AND (b."serialNumber" ILIKE ${like} OR b."brand" ILIKE ${like} OR COALESCE(b."model",'') ILIKE ${like} OR COALESCE(v."registrationNumber",'') ILIKE ${like}) ORDER BY b."createdAt" DESC LIMIT 6`;items.push(...rows.map(x=>({type:"BATTERY",id:x.id,title:x.serialNumber,subtitle:`${x.brand}${x.model?` ${x.model}`:""}${x.registrationNumber?` · ${x.registrationNumber}`:" · stores"}`,status:x.status,href:"/batteries"})));}
 if(p.has(PERMISSIONS.HANDOVER_VIEW)){const rows=await prisma.$queryRaw<Array<Handover&{registrationNumber:string;fromDriverName:string|null;toDriverName:string|null}>>`SELECT h."id",h."handoverNumber",h."vehicleId",h."fromDriverId",h."toDriverId",h."type",h."status",h."odometerKm",h."fuelPercent",h."createdAt",h."acceptedAt",v."registrationNumber",fd."fullName" AS "fromDriverName",td."fullName" AS "toDriverName" FROM "VehicleHandover" h JOIN "Vehicle" v ON v."id"=h."vehicleId" LEFT JOIN "Driver" fd ON fd."id"=h."fromDriverId" LEFT JOIN "Driver" td ON td."id"=h."toDriverId" WHERE h."organizationId"=${org}::uuid AND (h."handoverNumber" ILIKE ${like} OR v."registrationNumber" ILIKE ${like} OR COALESCE(fd."fullName",'') ILIKE ${like} OR COALESCE(td."fullName",'') ILIKE ${like}) ORDER BY h."createdAt" DESC LIMIT 6`;items.push(...rows.map(x=>({type:"HANDOVER",id:x.id,title:x.handoverNumber,subtitle:`${x.registrationNumber} · ${x.fromDriverName??"Fleet"} → ${x.toDriverName??"Fleet"}`,status:x.status,href:"/handovers"})));}
 if(p.has(PERMISSIONS.DOCUMENT_VIEW)){const rows=await prisma.$queryRaw<Vault[]>`SELECT "id","entityType","entityId","documentType","title","referenceNumber","issuer","expiryDate","mimeType","originalName","sizeBytes","createdAt" FROM "DocumentVaultItem" WHERE "organizationId"=${org}::uuid AND ("title" ILIKE ${like} OR "documentType" ILIKE ${like} OR COALESCE("referenceNumber",'') ILIKE ${like} OR COALESCE("issuer",'') ILIKE ${like}) ORDER BY "createdAt" DESC LIMIT 6`;items.push(...rows.map(x=>({type:"DOCUMENT",id:x.id,title:x.title,subtitle:`${x.documentType} · ${x.entityType}${x.referenceNumber?` · ${x.referenceNumber}`:""}`,href:"/documents"})));}
 if(p.has(PERMISSIONS.APPROVAL_VIEW)){const rows=await prisma.$queryRaw<Array<{id:string;moduleKey:string;recordId:string;status:string;definitionName:string}>>`SELECT r."id",r."moduleKey",r."recordId",r."status",d."name" AS "definitionName" FROM "ApprovalRequest" r JOIN "ApprovalDefinition" d ON d."id"=r."definitionId" WHERE r."organizationId"=${org}::uuid AND (d."name" ILIKE ${like} OR r."moduleKey" ILIKE ${like} OR r."recordId" ILIKE ${like}) ORDER BY r."requestedAt" DESC LIMIT 6`;items.push(...rows.map(x=>({type:"APPROVAL",id:x.id,title:x.definitionName,subtitle:`${x.moduleKey} · record ${x.recordId}`,status:x.status,href:"/approvals"})));}
 return res.json({items:items.slice(0,24)});
});

recordHubRouter.get("/vehicles/:id",requirePermission(PERMISSIONS.VEHICLE_VIEW),async(req,res)=>{const id=typeof req.params.id==="string"?req.params.id:"";const org=req.auth!.organizationId,p=req.auth!.permissions;const vehicle=await prisma.vehicle.findFirst({where:{id,organizationId:org,archivedAt:null},select:{id:true}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});const canBattery=p.has(PERMISSIONS.BATTERY_VIEW),canHandover=p.has(PERMISSIONS.HANDOVER_VIEW),canDocument=p.has(PERMISSIONS.DOCUMENT_VIEW);const [batteries,handovers,documents]=await Promise.all([
  canBattery?prisma.$queryRaw<Battery[]>`SELECT "id","serialNumber","brand","model","status","position","warrantyEnd","currentVehicleId" FROM "BatteryAsset" WHERE "organizationId"=${org}::uuid AND "currentVehicleId"=${id}::uuid ORDER BY "position"`:Promise.resolve([]),
  canHandover?prisma.$queryRaw<Array<Handover&{fromDriverName:string|null;toDriverName:string|null}>>`SELECT h."id",h."handoverNumber",h."vehicleId",h."fromDriverId",h."toDriverId",h."type",h."status",h."odometerKm",h."fuelPercent",h."createdAt",h."acceptedAt",fd."fullName" AS "fromDriverName",td."fullName" AS "toDriverName" FROM "VehicleHandover" h LEFT JOIN "Driver" fd ON fd."id"=h."fromDriverId" LEFT JOIN "Driver" td ON td."id"=h."toDriverId" WHERE h."organizationId"=${org}::uuid AND h."vehicleId"=${id}::uuid ORDER BY h."createdAt" DESC LIMIT 12`:Promise.resolve([]),
  canDocument?prisma.$queryRaw<Vault[]>`SELECT "id","entityType","entityId","documentType","title","referenceNumber","issuer","expiryDate","mimeType","originalName","sizeBytes","createdAt" FROM "DocumentVaultItem" WHERE "organizationId"=${org}::uuid AND "entityType"='VEHICLE' AND "entityId"=${id}::uuid ORDER BY "createdAt" DESC LIMIT 20`:Promise.resolve([])
 ]);return res.json({batteries,handovers,documents:documents.map(x=>({...x,fileEndpoint:`/api/documents/${x.id}/file`})),access:{battery:canBattery,handover:canHandover,document:canDocument}});
});

recordHubRouter.get("/drivers/:id",requirePermission(PERMISSIONS.DRIVER_VIEW),async(req,res)=>{const id=typeof req.params.id==="string"?req.params.id:"";const org=req.auth!.organizationId,p=req.auth!.permissions;const driver=await prisma.driver.findFirst({where:{id,organizationId:org,archivedAt:null},select:{id:true}});if(!driver)return res.status(404).json({error:"Driver not found."});const canHandover=p.has(PERMISSIONS.HANDOVER_VIEW),canDocument=p.has(PERMISSIONS.DOCUMENT_VIEW);const[handovers,documents]=await Promise.all([canHandover?prisma.$queryRaw<Array<Handover&{registrationNumber:string}>>`SELECT h."id",h."handoverNumber",h."vehicleId",h."fromDriverId",h."toDriverId",h."type",h."status",h."odometerKm",h."fuelPercent",h."createdAt",h."acceptedAt",v."registrationNumber" FROM "VehicleHandover" h JOIN "Vehicle" v ON v."id"=h."vehicleId" WHERE h."organizationId"=${org}::uuid AND (h."fromDriverId"=${id}::uuid OR h."toDriverId"=${id}::uuid) ORDER BY h."createdAt" DESC LIMIT 12`:Promise.resolve([]),canDocument?prisma.$queryRaw<Vault[]>`SELECT "id","entityType","entityId","documentType","title","referenceNumber","issuer","expiryDate","mimeType","originalName","sizeBytes","createdAt" FROM "DocumentVaultItem" WHERE "organizationId"=${org}::uuid AND "entityType"='DRIVER' AND "entityId"=${id}::uuid ORDER BY "createdAt" DESC LIMIT 20`:Promise.resolve([])]);return res.json({handovers,documents:documents.map(x=>({...x,fileEndpoint:`/api/documents/${x.id}/file`})),access:{handover:canHandover,document:canDocument}});});

recordHubRouter.get("/action-centre",requirePermission(PERMISSIONS.DASHBOARD_VIEW),async(req,res)=>{if(!req.auth!.permissions.has(PERMISSIONS.APPROVAL_DECIDE))return res.json({items:[]});const org=req.auth!.organizationId;const rows=await prisma.$queryRaw<Approval[]>`SELECT r."id",r."definitionId",r."moduleKey",r."recordId",r."requesterUserId",r."status",r."currentStep",r."requestedAt",d."name" AS "definitionName",s."roleName",s."allowRequester",s."minApprovals",u."fullName" AS "requesterName" FROM "ApprovalRequest" r JOIN "ApprovalDefinition" d ON d."id"=r."definitionId" JOIN "ApprovalDefinitionStep" s ON s."definitionId"=r."definitionId" AND s."stepOrder"=r."currentStep" JOIN "User" u ON u."id"=r."requesterUserId" WHERE r."organizationId"=${org}::uuid AND r."status"='PENDING' ORDER BY r."requestedAt" ASC LIMIT 50`;const items=rows.filter(x=>req.auth!.roles.includes(x.roleName)&&(x.allowRequester||x.requesterUserId!==req.auth!.userId)).map(x=>({type:"CONFIGURABLE_APPROVAL",id:x.id,title:`${x.definitionName} awaiting ${x.roleName.replaceAll("_"," ")}`,subtitle:`${x.moduleKey} · record ${x.recordId} · requested by ${x.requesterName} · step ${x.currentStep}`,severity:"WARNING" as const,href:"/approvals",createdAt:x.requestedAt}));return res.json({items});});
