import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { App } from "./app";
import { AuthProvider } from "./auth/AuthContext";
import "./styles.css";
import "./styles-v2.css";
import "./styles-v2-ops.css";
import "./styles-v3.css";
import "./styles-v4.css";
import "./styles-v5.css";
import "./styles-v6.css";
import "./styles-v6-secure.css";
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><AuthProvider><App/></AuthProvider></BrowserRouter></React.StrictMode>);
