import { useEffect,useMemo,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { api,apiBlob } from "../api/client";
import { Icon } from "./Icon";

type Handover={id:string;handoverNumber:string;vehicleId:string;registrationNumber:string;type:string;status:string;odometerKm:number;fuelPercent?:number|null;createdAt:string;acceptedAt?:string|null;fromDriverId?:string|null;toDriverId?:string|null};type Doc={id:string;documentType:string;title:string;referenceNumber?:string|null;issuer?:string|null;expiryDate?:string|null;mimeType:string;originalName:string;sizeBytes:number;fileEndpoint:string};type Payload={handovers:Handover[];documents:Doc[];access:{handover:boolean;document:boolean}};
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString():"—";
function Restricted(){return <div className="restricted-section-v6"><Icon name="shield" size={21}/><b>Restricted by role</b><span>This integrated record set requires an additional operational permission.</span></div>}
export function DriverRecordHub(){const{id}=useParams();const[data,setData]=useState<Payload|null>(null),[error,setError]=useState("");useEffect(()=>{if(!id)return;void api<Payload>(`/record-hub/drivers/${id}`).then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load integrated driver records."));},[id]);const stats=useMemo(()=>data?{pending:data.handovers.filter(x=>x.status==="PENDING").length,docsDue:data.documents.filter(x=>x.expiryDate&&new Date(x.expiryDate).getTime()-Date.now()<=60*86400000).length}:null,[data]);const open=async(doc:Doc)=>{try{const blob=await apiBlob(doc.fileEndpoint.replace(/^\/api/,""));const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(e){setError(e instanceof Error?e.message:"Unable to open private document.");}};if(!data&&!error)return <div className="record-hub-loading-v8"><span className="loading-ring small"/>Loading custody and private records…</div>;if(error)return <div className="error-box">{error}</div>;if(!data)return null;return <section className="integrated-record-hub-v8"><div className="record-hub-title-v8"><div><span className="eyebrow-v2">PHASE 8 · DRIVER RECORD HUB</span><h2>Custody & private driver records</h2><p>Driver 360 now brings vehicle custody history and private document records into the readiness profile while preserving role boundaries.</p></div><span className="record-hub-badge-v8"><Icon name="shield" size={15}/>Permission scoped</span></div><div className="record-hub-summary-v8"><span className={stats?.pending?"warn":""}><b>{data.access.handover?stats?.pending:"—"}</b> pending custody records</span><span className={stats?.docsDue?"warn":""}><b>{data.access.document?stats?.docsDue:"—"}</b> documents due ≤60d</span></div><div className="record-hub-grid-v8 two-v8">
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">CUSTODY HISTORY</span><h3>Vehicle handovers</h3></div>{data.access.handover&&<Link to="/handovers">Handover ledger →</Link>}</div>{data.access.handover?<div className="panel-body-v2 compact-stack">{data.handovers.map(x=><div className={`record-card-v6 ${x.status==="PENDING"?"attention":""}`} key={x.id}><div><b>{x.handoverNumber} · {x.registrationNumber}</b><small>{x.type} · {date(x.createdAt)}</small></div><span>{x.status}<small> · {x.odometerKm.toLocaleString()} km · fuel {x.fuelPercent??"—"}%</small></span></div>)}{!data.handovers.length&&<div className="empty-strip">No vehicle handovers linked to this driver.</div>}</div>:<Restricted/>}</section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">PRIVATE DRIVER FILES</span><h3>Document vault</h3></div>{data.access.document&&<Link to="/documents">Document Vault →</Link>}</div>{data.access.document?<div className="panel-body-v2 record-doc-grid-v8">{data.documents.map(x=>{const expired=x.expiryDate?new Date(x.expiryDate).getTime()<Date.now():false;return <button className={`record-doc-v8 ${expired?"expired":""}`} key={x.id} onClick={()=>void open(x)}><span className="record-doc-icon-v8"><Icon name="audit" size={17}/></span><span><b>{x.title}</b><small>{x.documentType} · {x.referenceNumber||x.issuer||"No reference"}</small></span><em>{x.expiryDate?date(x.expiryDate):"No expiry"}</em></button>})}{!data.documents.length&&<div className="empty-strip">No private driver documents linked yet.</div>}</div>:<Restricted/>}</section>
</div></section>}
