import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api/client";
import { Icon, type IconName } from "./Icon";

type SearchResult={type:string;id:string;title:string;subtitle:string;status?:string;href:string};
const icons:Record<string,IconName>={VEHICLE:"vehicle",DRIVER:"driver",TRIP:"trip",WORK_ORDER:"wrench",INCIDENT:"alert",VENDOR:"users",BATTERY:"gauge",HANDOVER:"assignment",DOCUMENT:"audit",APPROVAL:"shield"};
const labels:Record<string,string>={VEHICLE:"Vehicle",DRIVER:"Driver",TRIP:"Trip",WORK_ORDER:"Workshop",INCIDENT:"Incident",VENDOR:"Vendor",BATTERY:"Battery",HANDOVER:"Handover",DOCUMENT:"Document",APPROVAL:"Approval"};

export function SearchPalette({onClose}:{onClose:()=>void}){
 const navigate=useNavigate();const[query,setQuery]=useState("");const[items,setItems]=useState<SearchResult[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{const q=query.trim();if(q.length<2){setItems([]);setError("");return;}const timer=window.setTimeout(()=>{setLoading(true);setError("");void Promise.allSettled([api<{items:SearchResult[]}>(`/workspace/search?q=${encodeURIComponent(q)}`),api<{items:SearchResult[]}>(`/record-hub/search?q=${encodeURIComponent(q)}`)]).then(results=>{const merged:SearchResult[]=[];for(const result of results)if(result.status==="fulfilled")merged.push(...result.value.items);const seen=new Set<string>();setItems(merged.filter(item=>{const key=`${item.type}:${item.id}`;if(seen.has(key))return false;seen.add(key);return true;}).slice(0,40));if(results.every(result=>result.status==="rejected"))setError("Search is temporarily unavailable.");}).finally(()=>setLoading(false));},180);return()=>window.clearTimeout(timer);},[query]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[onClose]);
 const grouped=useMemo(()=>{const map=new Map<string,SearchResult[]>();for(const item of items)map.set(item.type,[...(map.get(item.type)??[]),item]);return [...map.entries()];},[items]);
 const open=(item:SearchResult)=>{navigate(item.href);onClose();};
 return <div className="search-palette-backdrop" role="presentation" onMouseDown={(e)=>{if(e.currentTarget===e.target)onClose();}}><section className="search-palette" role="dialog" aria-modal="true" aria-label="Search ACRILAND Fleet Command"><div className="search-palette-input"><Icon name="search" size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vehicle, driver, trip, battery, handover, document, job card or vendor…"/><kbd>ESC</kbd></div><div className="search-palette-body">{loading&&<div className="search-state"><span className="loading-ring small"/>Searching authorized fleet records…</div>}{error&&<div className="error-box">{error}</div>}{!loading&&query.trim().length<2&&<div className="search-state search-hint"><Icon name="shield" size={24}/><b>Universal fleet search</b><span>Search operational, custody, asset and governance records. Results are limited to permissions granted to your role.</span></div>}{!loading&&query.trim().length>=2&&!items.length&&!error&&<div className="search-state"><Icon name="search" size={24}/><b>No matching records</b><span>Try registration, employee number, trip, handover, battery serial, document reference or vendor.</span></div>}{grouped.map(([type,rows])=><div className="search-result-group" key={type}><span className="search-result-heading">{labels[type]??type.replaceAll("_"," ")}</span>{rows.map(item=><button key={`${item.type}-${item.id}`} className="search-result-row" onClick={()=>open(item)}><span className="search-result-icon"><Icon name={icons[item.type]??"search"} size={17}/></span><span className="search-result-copy"><b>{item.title}</b><small>{item.subtitle}</small></span>{item.status&&<span className={`status-pill-v2 search-status s-${item.status}`}><i/>{item.status.replaceAll("_"," ")}</span>}<span className="search-open">Open →</span></button>)}</div>)}</div><footer className="search-palette-footer"><span><b>ACRILAND Command Search</b> · tenant and permission scoped</span><span>Ctrl/Cmd + K</span></footer></section></div>;
}
