import { useEffect,useMemo,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { api,apiBlob } from "../api/client";
import { Icon } from "./Icon";

type Battery={id:string;serialNumber:string;brand:string;model?:string|null;status:string;position?:string|null;warrantyEnd?:string|null};type Handover={id:string;handoverNumber:string;type:string;status:string;odometerKm:number;fuelPercent?:number|null;createdAt:string;acceptedAt?:string|null;fromDriverName?:string|null;toDriverName?:string|null};type Doc={id:string;documentType:string;title:string;referenceNumber?:string|null;issuer?:string|null;expiryDate?:string|null;mimeType:string;originalName:string;sizeBytes:number;fileEndpoint:string};type Payload={batteries:Battery[];handovers:Handover[];documents:Doc[];access:{battery:boolean;handover:boolean;document:boolean}};
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString():"—";
function Restricted(){return <div className="restricted-section-v6"><Icon name="shield" size={21}/><b>Restricted by role</b><span>This integrated record set requires an additional operational permission.</span></div>}
export function VehicleRecordHub(){const{id}=useParams();const[data,setData]=useState<Payload|null>(null),[error,setError]=useState("");useEffect(()=>{if(!id)return;void api<Payload>(`/record-hub/vehicles/${id}`).then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load integrated vehicle records."));},[id]);const watch=useMemo(()=>data?{batteryWarranty:data.batteries.filter(x=>x.warrantyEnd&&new Date(x.warrantyEnd).getTime()-Date.now()<=60*86400000).length,pendingHandovers:data.handovers.filter(x=>x.status==="PENDING").length,expiringDocs:data.documents.filter(x=>x.expiryDate&&new Date(x.expiryDate).getTime()-Date.now()<=60*86400000).length}:null,[data]);const open=async(doc:Doc)=>{try{const blob=await apiBlob(doc.fileEndpoint.replace(/^\/api/,""));const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(e){setError(e instanceof Error?e.message:"Unable to open private document.");}};if(!data&&!error)return <div className="record-hub-loading-v8"><span className="loading-ring small"/>Loading custody and private records…</div>;if(error)return <div className="error-box">{error}</div>;if(!data)return null;return <section className="integrated-record-hub-v8"><div className="record-hub-title-v8"><div><span className="eyebrow-v2">PHASE 8 · INTEGRATED RECORD HUB</span><h2>Custody, electrical assets & private records</h2><p>Vehicle 360 now includes records that previously lived in separate control modules, without weakening their permissions.</p></div><span className="record-hub-badge-v8"><Icon name="shield" size={15}/>Permission scoped</span></div><div className="record-hub-summary-v8"><span><b>{data.access.battery?data.batteries.length:"—"}</b> batteries fitted</span><span className={watch?.pendingHandovers?"warn":""}><b>{data.access.handover?watch?.pendingHandovers:"—"}</b> pending handovers</span><span className={watch?.expiringDocs?"warn":""}><b>{data.access.document?watch?.expiringDocs:"—"}</b> documents due ≤60d</span></div><div className="record-hub-grid-v8">
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">BATTERY ACCOUNTABILITY</span><h3>Current electrical fitment</h3></div>{data.access.battery&&<Link to="/batteries">Battery Lifecycle →</Link>}</div>{data.access.battery?<div className="panel-body-v2 compact-stack">{data.batteries.map(x=><div className={`record-card-v6 ${x.warrantyEnd&&new Date(x.warrantyEnd).getTime()<Date.now()?"attention":""}`} key={x.id}><div><b>{x.position||"Position not set"} · {x.serialNumber}</b><small>{x.brand}{x.model?` ${x.model}`:""}</small></div><span>{x.status}<small>{x.warrantyEnd?` · warranty ${date(x.warrantyEnd)}`:" · no warranty date"}</small></span></div>)}{!data.batteries.length&&<div className="empty-strip">No serialized battery currently fitted.</div>}</div>:<Restricted/>}</section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">CUSTODY TIMELINE</span><h3>Vehicle handovers</h3></div>{data.access.handover&&<Link to="/handovers">Handover ledger →</Link>}</div>{data.access.handover?<div className="panel-body-v2 compact-stack">{data.handovers.slice(0,8).map(x=><div className={`record-card-v6 ${x.status==="PENDING"?"attention":""}`} key={x.id}><div><b>{x.handoverNumber} · {x.type}</b><small>{x.fromDriverName||"Fleet custody"} → {x.toDriverName||"Fleet custody"}</small></div><span>{x.status}<small> · {x.odometerKm.toLocaleString()} km · fuel {x.fuelPercent??"—"}%</small></span></div>)}{!data.handovers.length&&<div className="empty-strip">No custody handovers recorded.</div>}</div>:<Restricted/>}</section>
<section className="panel-v2 record-hub-docs-v8"><div className="panel-head-v2"><div><span className="panel-kicker">PRIVATE DOCUMENTS</span><h3>Vehicle document vault</h3></div>{data.access.document&&<Link to="/documents">Document Vault →</Link>}</div>{data.access.document?<div className="panel-body-v2 record-doc-grid-v8">{data.documents.slice(0,10).map(x=>{const expired=x.expiryDate?new Date(x.expiryDate).getTime()<Date.now():false;return <button className={`record-doc-v8 ${expired?"expired":""}`} key={x.id} onClick={()=>void open(x)}><span className="record-doc-icon-v8"><Icon name="audit" size={17}/></span><span><b>{x.title}</b><small>{x.documentType} · {x.issuer||"Issuer not recorded"}</small></span><em>{x.expiryDate?date(x.expiryDate):"No expiry"}</em></button>})}{!data.documents.length&&<div className="empty-strip">No private vehicle documents linked yet.</div>}</div>:<Restricted/>}</section>
</div></section>}
