import { randomUUID } from "node:crypto";
import { Router } from "express";
import multer from "multer";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { requirePermission } from "../../middleware/authorize.js";
import { deletePrivateFile, detectPrivateEvidenceMime, readPrivateFile, saveVaultDocument } from "../../lib/fileStorage.js";

export const documentsRouter=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{files:1,fileSize:10*1024*1024}}).single("file");
const idParam=(v:string|string[]|undefined)=>typeof v==="string"?v:null;
const entityTypes=["VEHICLE","DRIVER","MAINTENANCE","INCIDENT","HANDOVER","VENDOR","OTHER"] as const;
type EntityType=(typeof entityTypes)[number];
type DocumentRow={id:string;organizationId:string;entityType:EntityType;entityId:string;documentType:string;title:string;referenceNumber:string|null;issuer:string|null;issueDate:Date|null;expiryDate:Date|null;storageLocator:string;mimeType:string;originalName:string;sizeBytes:number;uploadedByUserId:string;createdAt:Date;updatedAt:Date};

async function entityExists(organizationId:string,type:EntityType,id:string){
 if(type==="OTHER")return true;
 if(type==="VEHICLE")return Boolean(await prisma.vehicle.findFirst({where:{id,organizationId,archivedAt:null},select:{id:true}}));
 if(type==="DRIVER")return Boolean(await prisma.driver.findFirst({where:{id,organizationId,archivedAt:null},select:{id:true}}));
 if(type==="MAINTENANCE")return Boolean(await prisma.maintenanceWorkOrder.findFirst({where:{id,organizationId},select:{id:true}}));
 if(type==="INCIDENT")return Boolean((await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "IncidentReport" WHERE "id"=${id}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`)[0]);
 if(type==="HANDOVER")return Boolean((await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "VehicleHandover" WHERE "id"=${id}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`)[0]);
 return Boolean((await prisma.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "Vendor" WHERE "id"=${id}::uuid AND "organizationId"=${organizationId}::uuid LIMIT 1`)[0]);
}

documentsRouter.get("/",requirePermission(PERMISSIONS.DOCUMENT_VIEW),async(req,res)=>{const type=z.enum(entityTypes).optional().parse(req.query.entityType);const entityId=z.string().uuid().optional().parse(req.query.entityId);const expiring=String(req.query.expiring??"")==="true";let rows:DocumentRow[];if(type&&entityId){rows=await prisma.$queryRaw<DocumentRow[]>`SELECT * FROM "DocumentVaultItem" WHERE "organizationId"=${req.auth!.organizationId}::uuid AND "entityType"=${type} AND "entityId"=${entityId}::uuid ORDER BY "createdAt" DESC`;}else if(expiring){rows=await prisma.$queryRaw<DocumentRow[]>`SELECT * FROM "DocumentVaultItem" WHERE "organizationId"=${req.auth!.organizationId}::uuid AND "expiryDate" IS NOT NULL AND "expiryDate" <= CURRENT_TIMESTAMP + INTERVAL '90 days' ORDER BY "expiryDate" ASC LIMIT 300`;}else{rows=await prisma.$queryRaw<DocumentRow[]>`SELECT * FROM "DocumentVaultItem" WHERE "organizationId"=${req.auth!.organizationId}::uuid ORDER BY "createdAt" DESC LIMIT 500`;}return res.json({items:rows.map(({storageLocator,...row})=>({...row,fileEndpoint:`/api/documents/${row.id}/file`,storedPrivately:Boolean(storageLocator)}))});});

documentsRouter.post("/",requirePermission(PERMISSIONS.DOCUMENT_MANAGE),(req,res,next)=>upload(req,res,error=>error?next(error):next()),async(req,res)=>{if(!req.file)return res.status(400).json({error:"Choose a PDF or image document to upload."});const meta=z.object({entityType:z.enum(entityTypes),entityId:z.string().uuid(),documentType:z.string().min(2).max(120),title:z.string().min(2).max(200),referenceNumber:z.string().max(150).optional(),issuer:z.string().max(200).optional(),issueDate:z.coerce.date().optional(),expiryDate:z.coerce.date().optional()}).refine(v=>!v.issueDate||!v.expiryDate||v.expiryDate>=v.issueDate,{message:"Expiry date cannot be before issue date."}).parse(req.body);if(!await entityExists(req.auth!.organizationId,meta.entityType,meta.entityId))return res.status(400).json({error:"The linked record does not belong to this organization."});const mime=detectPrivateEvidenceMime(req.file.buffer);if(!mime)return res.status(415).json({error:"Document must be a valid PDF, JPEG, PNG or WebP file."});const id=randomUUID();const locator=await saveVaultDocument({organizationId:req.auth!.organizationId,entityType:meta.entityType,entityId:meta.entityId,buffer:req.file.buffer,mime});try{await prisma.$executeRaw`INSERT INTO "DocumentVaultItem"("id","organizationId","entityType","entityId","documentType","title","referenceNumber","issuer","issueDate","expiryDate","storageLocator","mimeType","originalName","sizeBytes","uploadedByUserId") VALUES (${id}::uuid,${req.auth!.organizationId}::uuid,${meta.entityType},${meta.entityId}::uuid,${meta.documentType},${meta.title},${meta.referenceNumber??null},${meta.issuer??null},${meta.issueDate??null},${meta.expiryDate??null},${locator},${mime},${req.file.originalname||"document"},${req.file.size},${req.auth!.userId}::uuid)`;}catch(error){await deletePrivateFile(locator).catch(()=>undefined);throw error;}await audit(req,{action:"UPLOAD",recordType:"DOCUMENT_VAULT",recordId:id,newValue:{entityType:meta.entityType,entityId:meta.entityId,documentType:meta.documentType,title:meta.title,mime,bytes:req.file.size,expiryDate:meta.expiryDate??null}});return res.status(201).json({id,fileEndpoint:`/api/documents/${id}/file`});});

documentsRouter.get("/:id/file",requirePermission(PERMISSIONS.DOCUMENT_VIEW),async(req,res)=>{const id=idParam(req.params.id);if(!id)return res.status(400).end();const row=(await prisma.$queryRaw<DocumentRow[]>`SELECT * FROM "DocumentVaultItem" WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`)[0];if(!row)return res.status(404).end();const buffer=await readPrivateFile(row.storageLocator);const mime=detectPrivateEvidenceMime(buffer);if(!mime)return res.status(500).end();res.set({"Content-Type":mime,"Content-Disposition":mime==="application/pdf"?`inline; filename="${row.originalName.replaceAll('"','')}"`:"inline","Cache-Control":"private, max-age=120","X-Content-Type-Options":"nosniff"});return res.send(buffer);});

documentsRouter.delete("/:id",requirePermission(PERMISSIONS.DOCUMENT_MANAGE),async(req,res)=>{const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid document id."});const row=(await prisma.$queryRaw<DocumentRow[]>`SELECT * FROM "DocumentVaultItem" WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`)[0];if(!row)return res.status(404).json({error:"Document not found."});await prisma.$executeRaw`DELETE FROM "DocumentVaultItem" WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`;await audit(req,{action:"DELETE",recordType:"DOCUMENT_VAULT",recordId:id,oldValue:{entityType:row.entityType,entityId:row.entityId,title:row.title,documentType:row.documentType}});await deletePrivateFile(row.storageLocator).catch(error=>console.error("Unable to delete vault file",error));return res.status(204).end();});
