export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  USER_VIEW: "user.view",
  USER_CREATE: "user.create",
  USER_CREATE_DRIVER: "user.create_driver",
  USER_DISABLE: "user.disable",
  BRANCH_VIEW: "branch.view",
  BRANCH_MANAGE: "branch.manage",
  DEPARTMENT_VIEW: "department.view",
  DEPARTMENT_MANAGE: "department.manage",
  VEHICLE_VIEW: "vehicle.view",
  VEHICLE_CREATE: "vehicle.create",
  VEHICLE_EDIT: "vehicle.edit",
  DRIVER_VIEW: "driver.view",
  DRIVER_VIEW_SELF: "driver.view_self",
  DRIVER_CREATE: "driver.create",
  DRIVER_EDIT: "driver.edit",
  DRIVER_PHOTO_MANAGE: "driver.photo.manage",
  DRIVER_PHOTO_UPLOAD_SELF: "driver.photo.upload_self",
  ASSIGNMENT_VIEW: "assignment.view",
  ASSIGNMENT_VIEW_SELF: "assignment.view_self",
  ASSIGNMENT_CREATE: "assignment.create",
  ASSIGNMENT_END: "assignment.end",
  TRIP_VIEW: "trip.view",
  TRIP_VIEW_SELF: "trip.view_self",
  TRIP_REQUEST: "trip.request",
  TRIP_APPROVE: "trip.approve",
  TRIP_ALLOCATE: "trip.allocate",
  TRIP_START: "trip.start",
  TRIP_COMPLETE: "trip.complete",
  TRIP_CLOSE: "trip.close",
  INSPECTION_VIEW: "inspection.view",
  INSPECTION_CREATE: "inspection.create",
  INSPECTION_TEMPLATE_MANAGE: "inspection.template.manage",
  AUDIT_VIEW: "audit.view",
  MAINTENANCE_OPEN: "maintenance.open",
  MAINTENANCE_APPROVE: "maintenance.approve",
  MAINTENANCE_RELEASE: "maintenance.release",
  FUEL_CREATE: "fuel.create",
  FUEL_APPROVE: "fuel.approve",
  REPORT_EXPORT: "report.export"
} as const;

export const PERMISSION_CATALOG = Object.values(PERMISSIONS).map((key) => ({ key, description: key.replaceAll(".", " ") }));

const P = PERMISSIONS;
export const ROLE_TEMPLATES: Record<string, string[]> = {
  "SUPER_ADMINISTRATOR": Object.values(P),
  "ORGANIZATION_ADMINISTRATOR": Object.values(P),
  "FLEET_MANAGER": [
    P.DASHBOARD_VIEW,P.USER_VIEW,P.USER_CREATE_DRIVER,P.USER_DISABLE,P.BRANCH_VIEW,P.DEPARTMENT_VIEW,
    P.VEHICLE_VIEW,P.VEHICLE_CREATE,P.VEHICLE_EDIT,P.DRIVER_VIEW,P.DRIVER_CREATE,P.DRIVER_EDIT,P.DRIVER_PHOTO_MANAGE,
    P.ASSIGNMENT_VIEW,P.ASSIGNMENT_CREATE,P.ASSIGNMENT_END,
    P.TRIP_VIEW,P.TRIP_REQUEST,P.TRIP_APPROVE,P.TRIP_ALLOCATE,P.TRIP_START,P.TRIP_COMPLETE,P.TRIP_CLOSE,
    P.INSPECTION_VIEW,P.INSPECTION_CREATE,P.INSPECTION_TEMPLATE_MANAGE,
    P.AUDIT_VIEW,P.MAINTENANCE_OPEN,P.MAINTENANCE_APPROVE,P.MAINTENANCE_RELEASE,P.FUEL_CREATE,P.FUEL_APPROVE,P.REPORT_EXPORT
  ],
  "WORKSHOP_MANAGER": [P.DASHBOARD_VIEW,P.VEHICLE_VIEW,P.DRIVER_VIEW,P.INSPECTION_VIEW,P.INSPECTION_CREATE,P.INSPECTION_TEMPLATE_MANAGE,P.MAINTENANCE_OPEN,P.MAINTENANCE_APPROVE,P.MAINTENANCE_RELEASE,P.REPORT_EXPORT],
  "WORKSHOP_SUPERVISOR": [P.DASHBOARD_VIEW,P.VEHICLE_VIEW,P.DRIVER_VIEW,P.INSPECTION_VIEW,P.INSPECTION_CREATE,P.MAINTENANCE_OPEN,P.REPORT_EXPORT],
  "TECHNICIAN": [P.VEHICLE_VIEW,P.INSPECTION_VIEW,P.INSPECTION_CREATE,P.MAINTENANCE_OPEN],
  "DRIVER": [
    P.DRIVER_VIEW_SELF,P.DRIVER_PHOTO_UPLOAD_SELF,
    P.ASSIGNMENT_VIEW_SELF,P.TRIP_VIEW_SELF,P.TRIP_REQUEST,P.TRIP_START,P.TRIP_COMPLETE,P.INSPECTION_VIEW,P.INSPECTION_CREATE,P.FUEL_CREATE
  ],
  "FINANCE_OFFICER": [P.DASHBOARD_VIEW,P.VEHICLE_VIEW,P.DRIVER_VIEW,P.TRIP_VIEW,P.FUEL_APPROVE,P.REPORT_EXPORT],
  "MANAGEMENT_DIRECTOR": [P.DASHBOARD_VIEW,P.VEHICLE_VIEW,P.DRIVER_VIEW,P.ASSIGNMENT_VIEW,P.TRIP_VIEW,P.INSPECTION_VIEW,P.AUDIT_VIEW,P.REPORT_EXPORT]
};
