import { randomUUID } from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { BLOCKED_FROM_OPERATION, canDriverOperate, type VehicleStatus } from "../../domain/rules.js";
import { validateDispatchWindow } from "../../domain/controlIntelligence.js";
import { requirePermission } from "../../middleware/authorize.js";

export const dispatchRouter = Router();
const routeId=(value:string|string[]|undefined)=>typeof value==="string"?value:null;
const activeStatuses=["PLANNED","READY","DISPATCHED","BLOCKED"] as const;
function dispatchNumber():string{const day=new Date().toISOString().slice(0,10).replaceAll("-","");return `DSP-${day}-${randomUUID().slice(0,8).toUpperCase()}`;}

async function enrich(organizationId:string){
  const items=await prisma.dispatchPlan.findMany({where:{organizationId},orderBy:[{status:"asc"},{plannedDeparture:"asc"}],take:500});
  const tripIds=[...new Set(items.map(i=>i.tripId))],vehicleIds=[...new Set(items.map(i=>i.vehicleId))],driverIds=[...new Set(items.map(i=>i.driverId))],routeIds=[...new Set(items.map(i=>i.routePlanId).filter((x):x is string=>Boolean(x)))];
  const [trips,vehicles,drivers,routes]=await Promise.all([
    prisma.trip.findMany({where:{id:{in:tripIds}},select:{id:true,tripNumber:true,purpose:true,origin:true,destination:true,status:true,requestedDeparture:true,expectedReturn:true}}),
    prisma.vehicle.findMany({where:{id:{in:vehicleIds}},select:{id:true,registrationNumber:true,fleetNumber:true,make:true,model:true,status:true}}),
    prisma.driver.findMany({where:{id:{in:driverIds}},select:{id:true,employeeNumber:true,fullName:true,status:true,licenceExpiry:true}}),
    routeIds.length?prisma.routePlan.findMany({where:{id:{in:routeIds}},select:{id:true,name:true,origin:true,destination:true}}):[]
  ]);
  const tm=new Map(trips.map(x=>[x.id,x])),vm=new Map(vehicles.map(x=>[x.id,x])),dm=new Map(drivers.map(x=>[x.id,x])),rm=new Map(routes.map(x=>[x.id,x]));
  return items.map(item=>({...item,trip:tm.get(item.tripId)??null,vehicle:vm.get(item.vehicleId)??null,driver:dm.get(item.driverId)??null,route:item.routePlanId?rm.get(item.routePlanId)??null:null}));
}

dispatchRouter.get("/",requirePermission(PERMISSIONS.DISPATCH_VIEW),async(req,res)=>res.json({items:await enrich(req.auth!.organizationId)}));

dispatchRouter.post("/",requirePermission(PERMISSIONS.DISPATCH_MANAGE),async(req,res)=>{
  const input=z.object({tripId:z.string().uuid(),routePlanId:z.string().uuid().optional(),geofenceId:z.string().uuid().optional(),plannedDeparture:z.coerce.date(),plannedReturn:z.coerce.date(),priority:z.number().int().min(1).max(5).default(3),dispatchNotes:z.string().max(2500).optional()}).parse(req.body);
  try{validateDispatchWindow(input.plannedDeparture,input.plannedReturn);}catch(error){return res.status(400).json({error:error instanceof Error?error.message:"Invalid dispatch window."});}
  const organizationId=req.auth!.organizationId;
  const trip=await prisma.trip.findFirst({where:{id:input.tripId,organizationId},select:{id:true,tripNumber:true,status:true,vehicleId:true,driverId:true}});if(!trip)return res.status(404).json({error:"Trip not found."});if(!["APPROVED","ALLOCATED","PRE_TRIP_INSPECTION","READY_TO_DEPART"].includes(trip.status))return res.status(409).json({error:`Dispatch planning requires an approved trip before departure; current trip status is ${trip.status}.`});if(!trip.vehicleId||!trip.driverId)return res.status(409).json({error:"Trip must have both vehicle and driver allocation before dispatch planning."});
  const currentPlan=await prisma.dispatchPlan.findFirst({where:{organizationId,tripId:trip.id,status:{not:"CANCELLED"}},select:{dispatchNumber:true,status:true}});if(currentPlan)return res.status(409).json({error:`Trip already has current dispatch plan ${currentPlan.dispatchNumber} (${currentPlan.status}). Cancel it before replanning.`});
  const [vehicle,driver,route,geofence]=await Promise.all([
    prisma.vehicle.findFirst({where:{id:trip.vehicleId,organizationId,archivedAt:null}}),prisma.driver.findFirst({where:{id:trip.driverId,organizationId,archivedAt:null}}),
    input.routePlanId?prisma.routePlan.findFirst({where:{id:input.routePlanId,organizationId,isActive:true}}):Promise.resolve(null),input.geofenceId?prisma.geofence.findFirst({where:{id:input.geofenceId,organizationId,isActive:true}}):Promise.resolve(null)
  ]);if(!vehicle||!driver)return res.status(409).json({error:"Allocated vehicle or driver is unavailable."});if(input.routePlanId&&!route)return res.status(400).json({error:"Route plan does not belong to this organization or is inactive."});if(input.geofenceId&&!geofence)return res.status(400).json({error:"Geofence does not belong to this organization or is inactive."});
  if(BLOCKED_FROM_OPERATION.has(vehicle.status as VehicleStatus))return res.status(409).json({error:`Vehicle cannot enter dispatch planning while status is ${vehicle.status}.`});if(!canDriverOperate(driver.status,driver.licenceExpiry))return res.status(409).json({error:"Allocated driver is not currently authorized to operate."});
  const conflict=await prisma.dispatchPlan.findFirst({where:{organizationId,status:{in:[...activeStatuses]},OR:[{vehicleId:vehicle.id},{driverId:driver.id}],plannedDeparture:{lt:input.plannedReturn},plannedReturn:{gt:input.plannedDeparture}},select:{dispatchNumber:true,vehicleId:true,driverId:true}});if(conflict)return res.status(409).json({error:`Dispatch window conflicts with ${conflict.dispatchNumber} for the allocated ${conflict.vehicleId===vehicle.id?"vehicle":"driver"}.`});
  const created=await prisma.dispatchPlan.create({data:{organizationId,dispatchNumber:dispatchNumber(),tripId:trip.id,vehicleId:vehicle.id,driverId:driver.id,routePlanId:input.routePlanId??null,geofenceId:input.geofenceId??null,plannedDeparture:input.plannedDeparture,plannedReturn:input.plannedReturn,priority:input.priority,status:"PLANNED",dispatchNotes:input.dispatchNotes??null,createdByUserId:req.auth!.userId}});await audit(req,{action:"CREATE",recordType:"DISPATCH_PLAN",recordId:created.id,newValue:created});return res.status(201).json(created);
});

dispatchRouter.post("/:id/ready",requirePermission(PERMISSIONS.DISPATCH_MANAGE),async(req,res)=>{const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid dispatch id."});const row=await prisma.dispatchPlan.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!row)return res.status(404).json({error:"Dispatch plan not found."});if(!["PLANNED","BLOCKED"].includes(row.status))return res.status(409).json({error:"Only a planned or blocked dispatch can be re-evaluated for readiness."});const [trip,vehicle,driver]=await Promise.all([prisma.trip.findFirst({where:{id:row.tripId,organizationId:req.auth!.organizationId}}),prisma.vehicle.findFirst({where:{id:row.vehicleId,organizationId:req.auth!.organizationId,archivedAt:null}}),prisma.driver.findFirst({where:{id:row.driverId,organizationId:req.auth!.organizationId,archivedAt:null}})]);if(!trip||!vehicle||!driver)return res.status(409).json({error:"Trip, vehicle or driver is no longer available."});const reasons:string[]=[];if(trip.status!=="READY_TO_DEPART")reasons.push(`trip status ${trip.status}`);if(BLOCKED_FROM_OPERATION.has(vehicle.status as VehicleStatus))reasons.push(`vehicle status ${vehicle.status}`);if(!canDriverOperate(driver.status,driver.licenceExpiry))reasons.push("driver not authorized");const status=reasons.length?"BLOCKED":"READY";const updated=await prisma.dispatchPlan.update({where:{id:row.id},data:{status}});await audit(req,{action:"READINESS_CHECK",recordType:"DISPATCH_PLAN",recordId:row.id,oldValue:{status:row.status},newValue:{status:updated.status,reasons}});return res.json({...updated,reasons});});

dispatchRouter.post("/:id/dispatch",requirePermission(PERMISSIONS.DISPATCH_MANAGE),async(req,res)=>{const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid dispatch id."});const row=await prisma.dispatchPlan.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!row)return res.status(404).json({error:"Dispatch plan not found."});if(row.status!=="READY")return res.status(409).json({error:"Dispatch must pass readiness control before it can be marked dispatched."});const trip=await prisma.trip.findFirst({where:{id:row.tripId,organizationId:req.auth!.organizationId},select:{status:true}});if(!trip||trip.status!=="ACTIVE")return res.status(409).json({error:"Dispatch status cannot become DISPATCHED until the trip has been authorized and started through Trip Control."});const updated=await prisma.dispatchPlan.update({where:{id:row.id},data:{status:"DISPATCHED",dispatchedByUserId:req.auth!.userId,dispatchedAt:new Date()}});await audit(req,{action:"DISPATCH",recordType:"DISPATCH_PLAN",recordId:row.id,oldValue:{status:row.status},newValue:{status:updated.status,dispatchedAt:updated.dispatchedAt}});return res.json(updated);});

dispatchRouter.post("/:id/complete",requirePermission(PERMISSIONS.DISPATCH_MANAGE),async(req,res)=>{const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid dispatch id."});const row=await prisma.dispatchPlan.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!row)return res.status(404).json({error:"Dispatch plan not found."});if(row.status!=="DISPATCHED")return res.status(409).json({error:"Only dispatched plans can be completed."});const trip=await prisma.trip.findFirst({where:{id:row.tripId,organizationId:req.auth!.organizationId},select:{status:true}});if(!trip||trip.status!=="CLOSED")return res.status(409).json({error:"Trip must be closed through Trip Control before dispatch completion."});const updated=await prisma.dispatchPlan.update({where:{id:row.id},data:{status:"COMPLETED",completedAt:new Date()}});await audit(req,{action:"COMPLETE",recordType:"DISPATCH_PLAN",recordId:row.id,oldValue:{status:row.status},newValue:{status:updated.status}});return res.json(updated);});

dispatchRouter.post("/:id/cancel",requirePermission(PERMISSIONS.DISPATCH_MANAGE),async(req,res)=>{const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid dispatch id."});const input=z.object({reason:z.string().min(5).max(1500)}).parse(req.body);const row=await prisma.dispatchPlan.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!row)return res.status(404).json({error:"Dispatch plan not found."});if(!["PLANNED","READY","BLOCKED"].includes(row.status))return res.status(409).json({error:"An active or completed dispatch cannot be cancelled here."});const updated=await prisma.dispatchPlan.update({where:{id:row.id},data:{status:"CANCELLED",cancelledAt:new Date(),cancelReason:input.reason}});await audit(req,{action:"CANCEL",recordType:"DISPATCH_PLAN",recordId:row.id,oldValue:{status:row.status},newValue:{status:updated.status},reason:input.reason});return res.json(updated);});
