import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { requirePermission } from "../../middleware/authorize.js";

export const vendorsRouter=Router();
const routeId=(value:string|string[]|undefined)=>typeof value==="string"?value:null;

vendorsRouter.get("/",requirePermission(PERMISSIONS.VENDOR_VIEW),async(req,res)=>{const items=await prisma.vendor.findMany({where:{organizationId:req.auth!.organizationId},orderBy:[{status:"asc"},{name:"asc"}],take:500});return res.json({items});});

vendorsRouter.post("/",requirePermission(PERMISSIONS.VENDOR_MANAGE),async(req,res)=>{const input=z.object({code:z.string().min(2).max(50),name:z.string().min(2).max(200),category:z.string().min(2).max(100),contactPerson:z.string().max(160).optional(),email:z.string().email().optional(),phone:z.string().max(50).optional(),taxId:z.string().max(100).optional(),paymentTerms:z.string().max(300).optional(),rating:z.number().int().min(1).max(5).optional(),notes:z.string().max(2000).optional()}).parse(req.body);const created=await prisma.vendor.create({data:{organizationId:req.auth!.organizationId,code:input.code.trim().toUpperCase(),name:input.name.trim(),category:input.category.trim().toUpperCase(),contactPerson:input.contactPerson??null,email:input.email?.toLowerCase()??null,phone:input.phone??null,taxId:input.taxId??null,paymentTerms:input.paymentTerms??null,status:"ACTIVE",rating:input.rating??null,notes:input.notes??null}});await audit(req,{action:"CREATE",recordType:"VENDOR",recordId:created.id,newValue:created});return res.status(201).json(created);});

vendorsRouter.patch("/:id",requirePermission(PERMISSIONS.VENDOR_MANAGE),async(req,res)=>{const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid vendor id."});const input=z.object({name:z.string().min(2).max(200).optional(),category:z.string().min(2).max(100).optional(),contactPerson:z.string().max(160).nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().max(50).nullable().optional(),taxId:z.string().max(100).nullable().optional(),paymentTerms:z.string().max(300).nullable().optional(),status:z.enum(["ACTIVE","SUSPENDED","INACTIVE"]).optional(),rating:z.number().int().min(1).max(5).nullable().optional(),notes:z.string().max(2000).nullable().optional()}).parse(req.body);const row=await prisma.vendor.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!row)return res.status(404).json({error:"Vendor not found."});const data:Record<string,unknown>={};for(const key of ["name","category","contactPerson","email","phone","taxId","paymentTerms","status","rating","notes"] as const)if(input[key]!==undefined)data[key]=input[key];if(typeof data.category==="string")data.category=data.category.toUpperCase();if(typeof data.email==="string")data.email=data.email.toLowerCase();const updated=await prisma.vendor.update({where:{id:row.id},data});await audit(req,{action:"UPDATE",recordType:"VENDOR",recordId:row.id,oldValue:row,newValue:updated});return res.json(updated);});
