import { randomUUID } from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { validateOdometer } from "../../domain/rules.js";
import { requirePermission } from "../../middleware/authorize.js";

export const batteriesRouter=Router();
const idParam=(v:string|string[]|undefined)=>typeof v==="string"?v:null;
type BatteryRow={id:string;organizationId:string;serialNumber:string;brand:string;model:string|null;capacityAh:string|null;voltage:string|null;purchaseDate:Date|null;purchaseCost:string|null;warrantyEnd:Date|null;status:string;currentVehicleId:string|null;position:string|null;fittedAt:Date|null;removedAt:Date|null;odometerKmAtFit:number|null;odometerKmAtRemoval:number|null;notes:string|null;createdAt:Date;updatedAt:Date;registrationNumber?:string|null;fleetNumber?:string|null;vehicleMake?:string|null;vehicleModel?:string|null;vehicleStatus?:string|null};

batteriesRouter.get("/",requirePermission(PERMISSIONS.BATTERY_VIEW),async(req,res)=>{
 const rows=await prisma.$queryRaw<BatteryRow[]>`SELECT b.*,v."registrationNumber",v."fleetNumber",v."make" AS "vehicleMake",v."model" AS "vehicleModel",v."status"::text AS "vehicleStatus" FROM "BatteryAsset" b LEFT JOIN "Vehicle" v ON v."id"=b."currentVehicleId" WHERE b."organizationId"=${req.auth!.organizationId}::uuid ORDER BY b."status",b."createdAt" DESC LIMIT 500`;
 return res.json({items:rows.map(r=>({...r,vehicle:r.currentVehicleId?{id:r.currentVehicleId,registrationNumber:r.registrationNumber,fleetNumber:r.fleetNumber,make:r.vehicleMake,model:r.vehicleModel,status:r.vehicleStatus}:null}))});
});

batteriesRouter.post("/",requirePermission(PERMISSIONS.BATTERY_MANAGE),async(req,res)=>{
 const input=z.object({serialNumber:z.string().min(2).max(120),brand:z.string().min(1).max(120),model:z.string().max(120).optional(),capacityAh:z.number().min(0).optional(),voltage:z.number().min(0).optional(),purchaseDate:z.coerce.date().optional(),purchaseCost:z.number().min(0).optional(),warrantyEnd:z.coerce.date().optional(),notes:z.string().max(2000).optional()}).parse(req.body);const id=randomUUID();const now=new Date();
 await prisma.$executeRaw`INSERT INTO "BatteryAsset"("id","organizationId","serialNumber","brand","model","capacityAh","voltage","purchaseDate","purchaseCost","warrantyEnd","notes","createdAt","updatedAt") VALUES (${id}::uuid,${req.auth!.organizationId}::uuid,${input.serialNumber.trim()},${input.brand.trim()},${input.model??null},${input.capacityAh??null},${input.voltage??null},${input.purchaseDate??null},${input.purchaseCost??null},${input.warrantyEnd??null},${input.notes??null},${now},${now})`;
 await audit(req,{action:"CREATE",recordType:"BATTERY",recordId:id,newValue:{serialNumber:input.serialNumber,brand:input.brand,status:"IN_STOCK"}});return res.status(201).json({id});
});

batteriesRouter.post("/:id/fit",requirePermission(PERMISSIONS.BATTERY_MANAGE),async(req,res)=>{
 const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid battery id."});const input=z.object({vehicleId:z.string().uuid(),position:z.string().min(1).max(60),odometerKm:z.number().int().min(0)}).parse(req.body);
 const rows=await prisma.$queryRaw<BatteryRow[]>`SELECT * FROM "BatteryAsset" WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`;const battery=rows[0];if(!battery)return res.status(404).json({error:"Battery not found."});if(["FITTED","SCRAPPED"].includes(battery.status))return res.status(409).json({error:`Battery cannot be fitted while status is ${battery.status}.`});
 const vehicle=await prisma.vehicle.findFirst({where:{id:input.vehicleId,organizationId:req.auth!.organizationId,archivedAt:null},select:{id:true,currentOdometerKm:true,registrationNumber:true}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});validateOdometer(vehicle.currentOdometerKm,input.odometerKm);const fitmentId=randomUUID(),now=new Date(),position=input.position.trim().toUpperCase();
 await prisma.$transaction(async tx=>{await tx.$executeRaw`INSERT INTO "BatteryFitment"("id","organizationId","batteryId","vehicleId","position","fittedAt","odometerKmAtFit","performedByUserId") VALUES (${fitmentId}::uuid,${req.auth!.organizationId}::uuid,${id}::uuid,${vehicle.id}::uuid,${position},${now},${input.odometerKm},${req.auth!.userId}::uuid)`;await tx.$executeRaw`UPDATE "BatteryAsset" SET "status"='FITTED',"currentVehicleId"=${vehicle.id}::uuid,"position"=${position},"fittedAt"=${now},"removedAt"=NULL,"odometerKmAtFit"=${input.odometerKm},"odometerKmAtRemoval"=NULL,"updatedAt"=${now} WHERE "id"=${id}::uuid`;});
 await audit(req,{action:"FIT",recordType:"BATTERY",recordId:id,oldValue:{status:battery.status},newValue:{status:"FITTED",vehicleId:vehicle.id,registrationNumber:vehicle.registrationNumber,position,odometerKm:input.odometerKm}});return res.json({id,status:"FITTED",vehicleId:vehicle.id,position});
});

batteriesRouter.post("/:id/remove",requirePermission(PERMISSIONS.BATTERY_MANAGE),async(req,res)=>{
 const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid battery id."});const input=z.object({odometerKm:z.number().int().min(0),nextStatus:z.enum(["IN_STOCK","REPAIR","SCRAPPED"]),reason:z.string().min(2).max(1000)}).parse(req.body);const rows=await prisma.$queryRaw<BatteryRow[]>`SELECT * FROM "BatteryAsset" WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`;const battery=rows[0];if(!battery||battery.status!=="FITTED"||!battery.currentVehicleId||battery.odometerKmAtFit===null)return res.status(409).json({error:"Only a currently fitted battery can be removed."});if(input.odometerKm<battery.odometerKmAtFit)return res.status(400).json({error:"Removal odometer cannot be below fitment odometer."});const now=new Date();
 await prisma.$transaction(async tx=>{await tx.$executeRaw`UPDATE "BatteryFitment" SET "removedAt"=${now},"odometerKmAtRemoval"=${input.odometerKm},"removalReason"=${input.reason} WHERE "batteryId"=${id}::uuid AND "removedAt" IS NULL`;await tx.$executeRaw`UPDATE "BatteryAsset" SET "status"=${input.nextStatus},"currentVehicleId"=NULL,"position"=NULL,"removedAt"=${now},"odometerKmAtRemoval"=${input.odometerKm},"updatedAt"=${now} WHERE "id"=${id}::uuid`;});
 await audit(req,{action:"REMOVE",recordType:"BATTERY",recordId:id,oldValue:{status:battery.status,vehicleId:battery.currentVehicleId,position:battery.position},newValue:{status:input.nextStatus,odometerKm:input.odometerKm},reason:input.reason});return res.json({id,status:input.nextStatus});
});

batteriesRouter.get("/:id/history",requirePermission(PERMISSIONS.BATTERY_VIEW),async(req,res)=>{const id=idParam(req.params.id);if(!id)return res.status(400).json({error:"Invalid battery id."});const battery=(await prisma.$queryRaw<BatteryRow[]>`SELECT * FROM "BatteryAsset" WHERE "id"=${id}::uuid AND "organizationId"=${req.auth!.organizationId}::uuid`)[0];if(!battery)return res.status(404).json({error:"Battery not found."});const history=await prisma.$queryRaw<Array<{id:string;vehicleId:string;position:string;fittedAt:Date;removedAt:Date|null;odometerKmAtFit:number;odometerKmAtRemoval:number|null;removalReason:string|null;registrationNumber:string;fleetNumber:string|null}>>`SELECT f."id",f."vehicleId",f."position",f."fittedAt",f."removedAt",f."odometerKmAtFit",f."odometerKmAtRemoval",f."removalReason",v."registrationNumber",v."fleetNumber" FROM "BatteryFitment" f JOIN "Vehicle" v ON v."id"=f."vehicleId" WHERE f."organizationId"=${req.auth!.organizationId}::uuid AND f."batteryId"=${id}::uuid ORDER BY f."fittedAt" DESC`;return res.json({battery,items:history.map(x=>({...x,distanceKm:x.odometerKmAtRemoval===null?null:x.odometerKmAtRemoval-x.odometerKmAtFit}))});});
