import { Router } from "express";
import { authRouter } from "./modules/auth/routes.js";
import { usersRouter } from "./modules/users/routes.js";
import { branchesRouter } from "./modules/branches/routes.js";
import { departmentsRouter } from "./modules/departments/routes.js";
import { vehiclesRouter } from "./modules/vehicles/routes.js";
import { driversRouter } from "./modules/drivers/routes.js";
import { dashboardRouter } from "./modules/dashboard/routes.js";
import { auditRouter } from "./modules/audit/routes.js";
import { assignmentsRouter } from "./modules/assignments/routes.js";
import { tripsRouter } from "./modules/trips/routes.js";
import { inspectionsRouter } from "./modules/inspections/routes.js";
import { maintenanceRouter } from "./modules/maintenance/routes.js";
import { fuelRouter } from "./modules/fuel/routes.js";
import { complianceRouter } from "./modules/compliance/routes.js";
import { reportsRouter } from "./modules/reports/routes.js";
import { tyresRouter } from "./modules/tyres/routes.js";
import { incidentsRouter } from "./modules/incidents/routes.js";
import { inventoryRouter } from "./modules/inventory/routes.js";
import { preventiveMaintenanceRouter } from "./modules/preventiveMaintenance/routes.js";
import { alertsRouter } from "./modules/alerts/routes.js";
import { telemetryRouter } from "./modules/telemetry/routes.js";
import { dispatchRouter } from "./modules/dispatch/routes.js";
import { geofencesRouter } from "./modules/geofences/routes.js";
import { safetyRouter } from "./modules/safety/routes.js";
import { vendorsRouter } from "./modules/vendors/routes.js";
import { lifecycleRouter } from "./modules/lifecycle/routes.js";
import { notificationsRouter } from "./modules/notifications/routes.js";
import { workspaceRouter } from "./modules/workspace/routes.js";
import { requireAuth } from "./middleware/auth.js";

export const apiRouter=Router();
apiRouter.get("/health",(_req,res)=>res.json({status:"ok",service:"acriland-fleet-api"}));
apiRouter.use("/auth",authRouter);
apiRouter.use(requireAuth);
apiRouter.use("/users",usersRouter);
apiRouter.use("/branches",branchesRouter);
apiRouter.use("/departments",departmentsRouter);
apiRouter.use("/vehicles",vehiclesRouter);
apiRouter.use("/drivers",driversRouter);
apiRouter.use("/dashboard",dashboardRouter);
apiRouter.use("/audit",auditRouter);
apiRouter.use("/assignments",assignmentsRouter);
apiRouter.use("/trips",tripsRouter);
apiRouter.use("/inspections",inspectionsRouter);
apiRouter.use("/maintenance",maintenanceRouter);
apiRouter.use("/fuel",fuelRouter);
apiRouter.use("/compliance",complianceRouter);
apiRouter.use("/reports",reportsRouter);
apiRouter.use("/tyres",tyresRouter);
apiRouter.use("/incidents",incidentsRouter);
apiRouter.use("/inventory",inventoryRouter);
apiRouter.use("/preventive-maintenance",preventiveMaintenanceRouter);
apiRouter.use("/alerts",alertsRouter);
apiRouter.use("/telemetry",telemetryRouter);
apiRouter.use("/dispatch",dispatchRouter);
apiRouter.use("/geofences",geofencesRouter);
apiRouter.use("/safety",safetyRouter);
apiRouter.use("/vendors",vendorsRouter);
apiRouter.use("/lifecycle",lifecycleRouter);
apiRouter.use("/notifications",notificationsRouter);
apiRouter.use("/workspace",workspaceRouter);
