import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { requirePermission } from "../../middleware/authorize.js";

export const telemetryRouter=Router();
function routeId(value:string|string[]|undefined):string|null{return typeof value==="string"?value:null;}

telemetryRouter.get("/latest",requirePermission(PERMISSIONS.TELEMETRY_VIEW),async(req,res)=>{
  const rows=await prisma.telemetrySnapshot.findMany({where:{organizationId:req.auth!.organizationId},orderBy:{recordedAt:"desc"},take:1000});const latest=new Map<string,(typeof rows)[number]>();for(const row of rows)if(!latest.has(row.vehicleId))latest.set(row.vehicleId,row);const items=[...latest.values()];const vehicleIds=items.map(i=>i.vehicleId);const vehicles=vehicleIds.length?await prisma.vehicle.findMany({where:{id:{in:vehicleIds}},select:{id:true,registrationNumber:true,fleetNumber:true,make:true,model:true,status:true,currentOdometerKm:true,currentLocation:true}}):[];const map=new Map(vehicles.map(v=>[v.id,v]));return res.json({items:items.map(i=>({...i,vehicle:map.get(i.vehicleId)??null}))});
});

telemetryRouter.get("/vehicles/:id/history",requirePermission(PERMISSIONS.TELEMETRY_VIEW),async(req,res)=>{
  const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid vehicle id."});const vehicle=await prisma.vehicle.findFirst({where:{id,organizationId:req.auth!.organizationId,archivedAt:null},select:{id:true,registrationNumber:true,fleetNumber:true,make:true,model:true,status:true}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});const limit=Math.min(500,Math.max(1,Number(req.query.limit??100)));const items=await prisma.telemetrySnapshot.findMany({where:{organizationId:req.auth!.organizationId,vehicleId:vehicle.id},orderBy:{recordedAt:"desc"},take:limit});return res.json({vehicle,items});
});

telemetryRouter.post("/ingest",requirePermission(PERMISSIONS.TELEMETRY_INGEST),async(req,res)=>{
  const input=z.object({vehicleId:z.string().uuid(),provider:z.string().min(2).max(120),externalDeviceId:z.string().max(150).optional(),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),speedKph:z.number().min(0).max(500).optional(),ignitionOn:z.boolean().optional(),odometerKm:z.number().int().min(0).optional(),fuelPercent:z.number().int().min(0).max(100).optional(),headingDegrees:z.number().int().min(0).max(359).optional(),recordedAt:z.coerce.date(),rawPayload:z.record(z.string(),z.unknown()).optional()}).parse(req.body);const vehicle=await prisma.vehicle.findFirst({where:{id:input.vehicleId,organizationId:req.auth!.organizationId,archivedAt:null}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});
  const snapshot=await prisma.$transaction(async tx=>{const row=await tx.telemetrySnapshot.create({data:{organizationId:req.auth!.organizationId,vehicleId:vehicle.id,provider:input.provider,externalDeviceId:input.externalDeviceId??null,latitude:input.latitude,longitude:input.longitude,speedKph:input.speedKph??null,ignitionOn:input.ignitionOn??null,odometerKm:input.odometerKm??null,fuelPercent:input.fuelPercent??null,headingDegrees:input.headingDegrees??null,recordedAt:input.recordedAt,rawPayload:input.rawPayload??undefined}});const location=`${input.latitude.toFixed(6)}, ${input.longitude.toFixed(6)}`;await tx.vehicle.update({where:{id:vehicle.id},data:{currentLocation:location,...(input.odometerKm!==undefined&&input.odometerKm>=vehicle.currentOdometerKm?{currentOdometerKm:input.odometerKm}:{})}});const blocked=["GROUNDED","BREAKDOWN","ACCIDENT","UNDER_MAINTENANCE","SERVICE_OVERDUE","OUT_OF_SERVICE","DISPOSED"].includes(vehicle.status);if(blocked&&(input.speedKph??0)>5){await tx.operationalAlert.upsert({where:{organizationId_sourceType_sourceId_category:{organizationId:req.auth!.organizationId,sourceType:"VEHICLE",sourceId:vehicle.id,category:"BLOCKED_VEHICLE_MOVEMENT"}},update:{severity:"CRITICAL",status:"OPEN",title:`${vehicle.registrationNumber} moving while ${vehicle.status.replaceAll("_"," ")}`,message:`Telemetry from ${input.provider} recorded ${input.speedKph?.toFixed(1)} km/h at ${location}.`,vehicleId:vehicle.id},create:{organizationId:req.auth!.organizationId,category:"BLOCKED_VEHICLE_MOVEMENT",severity:"CRITICAL",sourceType:"VEHICLE",sourceId:vehicle.id,title:`${vehicle.registrationNumber} moving while ${vehicle.status.replaceAll("_"," ")}`,message:`Telemetry from ${input.provider} recorded ${input.speedKph?.toFixed(1)} km/h at ${location}.`,vehicleId:vehicle.id}});}return row;});
  if(["GROUNDED","BREAKDOWN","ACCIDENT","UNDER_MAINTENANCE","SERVICE_OVERDUE","OUT_OF_SERVICE","DISPOSED"].includes(vehicle.status)&&(input.speedKph??0)>5)await audit(req,{action:"TELEMETRY_EXCEPTION",recordType:"VEHICLE",recordId:vehicle.id,newValue:{snapshotId:snapshot.id,status:vehicle.status,speedKph:input.speedKph,latitude:input.latitude,longitude:input.longitude}});return res.status(201).json(snapshot);
});
