import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { ROLE_TEMPLATES } from "../src/domain/permissions.ts";

const hasDatabase=Boolean(process.env.DATABASE_URL);

test("Phase 7 permissions are seeded and driver access remains narrow",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const keys=["battery.view","battery.manage","handover.view","handover.create","handover.manage","handover.accept_self","document.view","document.manage","approval.view","approval.configure","approval.decide"];const count=await prisma.permission.count({where:{key:{in:keys}}});assert.equal(count,keys.length);assert.ok(ROLE_TEMPLATES.DRIVER?.includes("handover.accept_self"));assert.equal(ROLE_TEMPLATES.DRIVER?.includes("handover.view"),false);assert.equal(ROLE_TEMPLATES.DRIVER?.includes("document.view"),false);}finally{await prisma.$disconnect();}});

test("database prevents two active batteries in the same vehicle position",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();const org=randomUUID(),user=randomUUID(),vehicle=randomUUID(),a=randomUUID(),b=randomUUID();try{await prisma.$executeRaw`INSERT INTO "Organization"("id","name","slug","createdAt","updatedAt") VALUES (${org}::uuid,'Phase7 Battery Org',${`p7-${org}`},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "User"("id","organizationId","email","fullName","passwordHash","status","mustChangePassword","failedLoginCount","createdAt","updatedAt") VALUES (${user}::uuid,${org}::uuid,${`${user}@test.local`},'Battery Tester','hash','ACTIVE',FALSE,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "Vehicle"("id","organizationId","registrationNumber","vin","make","model","category","manufacturingYear","fuelType","initialOdometerKm","currentOdometerKm","status","createdAt","updatedAt") VALUES (${vehicle}::uuid,${org}::uuid,${`BAT-${vehicle.slice(0,6)}`},${`VIN${vehicle.replaceAll('-','')}`},'Test','Truck','TRUCK',2026,'DIESEL',0,100,'AVAILABLE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;for(const [id,serial] of [[a,`A-${a}`],[b,`B-${b}`]] as const)await prisma.$executeRaw`INSERT INTO "BatteryAsset"("id","organizationId","serialNumber","brand","status") VALUES (${id}::uuid,${org}::uuid,${serial},'Test','IN_STOCK')`;await prisma.$executeRaw`INSERT INTO "BatteryFitment"("id","organizationId","batteryId","vehicleId","position","odometerKmAtFit","performedByUserId") VALUES (${randomUUID()}::uuid,${org}::uuid,${a}::uuid,${vehicle}::uuid,'BATTERY-1',100,${user}::uuid)`;await assert.rejects(()=>prisma.$executeRaw`INSERT INTO "BatteryFitment"("id","organizationId","batteryId","vehicleId","position","odometerKmAtFit","performedByUserId") VALUES (${randomUUID()}::uuid,${org}::uuid,${b}::uuid,${vehicle}::uuid,'battery-1',100,${user}::uuid)`);}finally{await prisma.$disconnect();}});

test("handover fuel and driver constraints are enforced",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();const org=randomUUID(),user=randomUUID(),vehicle=randomUUID(),driver=randomUUID();try{await prisma.$executeRaw`INSERT INTO "Organization"("id","name","slug","createdAt","updatedAt") VALUES (${org}::uuid,'Phase7 Handover Org',${`p7-${org}`},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "User"("id","organizationId","email","fullName","passwordHash","status","mustChangePassword","failedLoginCount","createdAt","updatedAt") VALUES (${user}::uuid,${org}::uuid,${`${user}@test.local`},'Handover Tester','hash','ACTIVE',FALSE,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "Vehicle"("id","organizationId","registrationNumber","vin","make","model","category","manufacturingYear","fuelType","initialOdometerKm","currentOdometerKm","status","createdAt","updatedAt") VALUES (${vehicle}::uuid,${org}::uuid,${`HO-${vehicle.slice(0,6)}`},${`VIN${vehicle.replaceAll('-','')}`},'Test','Truck','TRUCK',2026,'DIESEL',0,100,'AVAILABLE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "Driver"("id","organizationId","employeeNumber","fullName","licenceNumber","licenceClass","licenceExpiry","status","createdAt","updatedAt") VALUES (${driver}::uuid,${org}::uuid,${`D-${driver.slice(0,6)}`},'Driver Tester',${`L-${driver}`},'CM',CURRENT_TIMESTAMP+INTERVAL '1 year','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await assert.rejects(()=>prisma.$executeRaw`INSERT INTO "VehicleHandover"("id","organizationId","handoverNumber","vehicleId","toDriverId","type","status","odometerKm","fuelPercent","createdByUserId") VALUES (${randomUUID()}::uuid,${org}::uuid,'INVALID-FUEL',${vehicle}::uuid,${driver}::uuid,'ISSUE','PENDING',100,101,${user}::uuid)`);await assert.rejects(()=>prisma.$executeRaw`INSERT INTO "VehicleHandover"("id","organizationId","handoverNumber","vehicleId","type","status","odometerKm","createdByUserId") VALUES (${randomUUID()}::uuid,${org}::uuid,'NO-DRIVER',${vehicle}::uuid,'RETURN','PENDING',100,${user}::uuid)`);}finally{await prisma.$disconnect();}});

test("approval definition requires positive ordered thresholds",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();const org=randomUUID(),user=randomUUID(),definition=randomUUID();try{await prisma.$executeRaw`INSERT INTO "Organization"("id","name","slug","createdAt","updatedAt") VALUES (${org}::uuid,'Phase7 Approval Org',${`p7-${org}`},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "User"("id","organizationId","email","fullName","passwordHash","status","mustChangePassword","failedLoginCount","createdAt","updatedAt") VALUES (${user}::uuid,${org}::uuid,${`${user}@test.local`},'Approval Tester','hash','ACTIVE',FALSE,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;await prisma.$executeRaw`INSERT INTO "ApprovalDefinition"("id","organizationId","moduleKey","name","createdByUserId") VALUES (${definition}::uuid,${org}::uuid,'TEST','Test Approval',${user}::uuid)`;await assert.rejects(()=>prisma.$executeRaw`INSERT INTO "ApprovalDefinitionStep"("id","definitionId","stepOrder","roleName","minApprovals") VALUES (${randomUUID()}::uuid,${definition}::uuid,0,'FLEET_MANAGER',1)`);await assert.rejects(()=>prisma.$executeRaw`INSERT INTO "ApprovalDefinitionStep"("id","definitionId","stepOrder","roleName","minApprovals") VALUES (${randomUUID()}::uuid,${definition}::uuid,1,'FLEET_MANAGER',0)`);}finally{await prisma.$disconnect();}});
