import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import test from "node:test";

const hasDatabase=Boolean(process.env.DATABASE_URL);
const phase5Permissions=["dispatch.view","dispatch.manage","route.view","route.manage","geofence.view","geofence.manage","safety.view","safety.view_self","safety.recalculate","vendor.view","vendor.manage","lifecycle.view","lifecycle.cost.manage","disposal.view","disposal.request","disposal.approve","notification.view","notification.manage","notification.dispatch"];

async function fixture(prisma:any,prefix:string){
  const suffix=randomUUID().slice(0,8);const organization=await prisma.organization.create({data:{name:`${prefix} ${suffix}`,slug:`${prefix.toLowerCase().replaceAll(" ","-")}-${suffix}`}});const user=await prisma.user.create({data:{organizationId:organization.id,email:`${prefix.toLowerCase().replaceAll(" ","-")}-${suffix}@example.test`,fullName:"Control User",passwordHash:"test-only"}});const vehicle=await prisma.vehicle.create({data:{organizationId:organization.id,registrationNumber:`P5-${suffix}`,vin:`P5VIN-${suffix}`,make:"Test",model:"Truck",category:"TRUCK",manufacturingYear:2026,fuelType:"DIESEL"}});const driver=await prisma.driver.create({data:{organizationId:organization.id,employeeNumber:`DRV-${suffix}`,fullName:"Phase Five Driver",licenceNumber:`LIC-${suffix}`,licenceClass:"C",licenceExpiry:new Date("2030-01-01T00:00:00Z")}});const trip=await prisma.trip.create({data:{organizationId:organization.id,tripNumber:`TRIP-${suffix}`,requesterUserId:user.id,purpose:"Phase 5 test movement",origin:"Kampala",destination:"Jinja",requestedDeparture:new Date("2026-08-20T08:00:00Z"),expectedReturn:new Date("2026-08-20T18:00:00Z"),vehicleId:vehicle.id,driverId:driver.id}});return{organization,user,vehicle,driver,trip,suffix};
}

test("Phase 5 permissions are seeded",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const rows=await prisma.permission.findMany({where:{key:{in:phase5Permissions}},select:{key:true}});assert.deepEqual(new Set(rows.map(r=>r.key)),new Set(phase5Permissions));}finally{await prisma.$disconnect();}});

test("database rejects inverted dispatch windows",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Dispatch Window");await assert.rejects(()=>prisma.dispatchPlan.create({data:{organizationId:f.organization.id,dispatchNumber:`DSP-${f.suffix}`,tripId:f.trip.id,vehicleId:f.vehicle.id,driverId:f.driver.id,plannedDeparture:new Date("2026-08-20T18:00:00Z"),plannedReturn:new Date("2026-08-20T08:00:00Z"),createdByUserId:f.user.id}}));}finally{await prisma.$disconnect();}});

test("database permits only one non-cancelled dispatch plan per trip",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Dispatch Unique");const common={organizationId:f.organization.id,tripId:f.trip.id,vehicleId:f.vehicle.id,driverId:f.driver.id,plannedDeparture:new Date("2026-08-20T08:00:00Z"),plannedReturn:new Date("2026-08-20T18:00:00Z"),createdByUserId:f.user.id};await prisma.dispatchPlan.create({data:{...common,dispatchNumber:`DSP-A-${f.suffix}`}});await assert.rejects(()=>prisma.dispatchPlan.create({data:{...common,dispatchNumber:`DSP-B-${f.suffix}`}}));}finally{await prisma.$disconnect();}});

test("cancelled dispatch history does not block controlled replanning",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Dispatch Replan");const common={organizationId:f.organization.id,tripId:f.trip.id,vehicleId:f.vehicle.id,driverId:f.driver.id,plannedDeparture:new Date("2026-08-20T08:00:00Z"),plannedReturn:new Date("2026-08-20T18:00:00Z"),createdByUserId:f.user.id};await prisma.dispatchPlan.create({data:{...common,dispatchNumber:`DSP-CANCEL-${f.suffix}`,status:"CANCELLED",cancelledAt:new Date(),cancelReason:"Schedule changed during control test"}});const replanned=await prisma.dispatchPlan.create({data:{...common,dispatchNumber:`DSP-REPLAN-${f.suffix}`,plannedDeparture:new Date("2026-08-21T08:00:00Z"),plannedReturn:new Date("2026-08-21T18:00:00Z")}});assert.equal(replanned.status,"PLANNED");}finally{await prisma.$disconnect();}});

test("database enforces disposal maker checker separation",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Disposal Checker");await assert.rejects(()=>prisma.vehicleDisposal.create({data:{organizationId:f.organization.id,vehicleId:f.vehicle.id,status:"APPROVED",requestedByUserId:f.user.id,approvedByUserId:f.user.id,approvedAt:new Date(),disposalMethod:"SALE",reason:"Lifecycle test disposal with sufficient explanation"}}));}finally{await prisma.$disconnect();}});

test("database permits only one active disposal per vehicle",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Disposal Unique");await prisma.vehicleDisposal.create({data:{organizationId:f.organization.id,vehicleId:f.vehicle.id,requestedByUserId:f.user.id,disposalMethod:"SALE",reason:"First active disposal request for uniqueness test"}});await assert.rejects(()=>prisma.vehicleDisposal.create({data:{organizationId:f.organization.id,vehicleId:f.vehicle.id,requestedByUserId:f.user.id,disposalMethod:"SCRAP",reason:"Second active disposal request must be rejected"}}));}finally{await prisma.$disconnect();}});

test("database rejects negative lifecycle cost",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Lifecycle Cost");await assert.rejects(()=>prisma.vehicleCostEntry.create({data:{organizationId:f.organization.id,vehicleId:f.vehicle.id,category:"OTHER",amount:-1,currency:"UGX",occurredAt:new Date(),description:"Invalid negative cost",createdByUserId:f.user.id}}));}finally{await prisma.$disconnect();}});

test("database requires valid circle geofence geometry",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Geofence Shape");await assert.rejects(()=>prisma.geofence.create({data:{organizationId:f.organization.id,name:`Invalid Circle ${f.suffix}`,shape:"CIRCLE",policy:"MONITOR",createdByUserId:f.user.id}}));}finally{await prisma.$disconnect();}});

test("geofence transition requires telemetry evidence",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Geofence Evidence");const fence=await prisma.geofence.create({data:{organizationId:f.organization.id,name:`Evidence Fence ${f.suffix}`,shape:"CIRCLE",policy:"MONITOR",centerLatitude:0,centerLongitude:0,radiusMetres:100,createdByUserId:f.user.id}});await assert.rejects(()=>prisma.geofenceEvent.create({data:{organizationId:f.organization.id,geofenceId:fence.id,vehicleId:f.vehicle.id,telemetrySnapshotId:null as never,type:"ENTRY",latitude:0,longitude:0,occurredAt:new Date()}}));}finally{await prisma.$disconnect();}});

test("notification delivery dedupe key is unique",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Notification Dedupe");const data={organizationId:f.organization.id,userId:f.user.id,channel:"EMAIL" as const,destination:f.user.email,subject:"Test alert",body:"Test notification body",dedupeKey:`dedupe-${f.suffix}`};await prisma.notificationDelivery.create({data});await assert.rejects(()=>prisma.notificationDelivery.create({data}));}finally{await prisma.$disconnect();}});

test("database rejects driver score outside 0 to 100",{skip:!hasDatabase},async()=>{const{PrismaClient}=await import("@prisma/client");const prisma=new PrismaClient();try{const f=await fixture(prisma,"Safety Score");await assert.rejects(()=>prisma.driverScoreSnapshot.create({data:{organizationId:f.organization.id,driverId:f.driver.id,periodStart:new Date("2026-06-01T00:00:00Z"),periodEnd:new Date("2026-08-31T23:59:59Z"),score:101,safetyEventPoints:0,incidentPoints:0,inspectionPoints:0,riskBand:"EXCELLENT",calculatedByUserId:f.user.id}}));}finally{await prisma.$disconnect();}});
