import { useEffect,useMemo,useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { Icon } from "../components/Icon";

type Row={type:string;id:string;title:string;subtitle:string;severity:"INFO"|"WARNING"|"CRITICAL";href:string;createdAt:string};type Payload={items:Row[];summary?:{total:number;critical:number;approvals:number}};
const typeLabel=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const actionFilters=[["ALL","All"],["CRITICAL","Critical"],["WARNING","Warnings"],["APPROVALS","Approvals"]] as const;
export function ActionCentrePage(){const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[filter,setFilter]=useState<(typeof actionFilters)[number][0]>("ALL"),[loading,setLoading]=useState(true);const load=()=>{setLoading(true);setError("");return Promise.allSettled([api<Payload>("/workspace/action-centre"),api<Payload>("/record-hub/action-centre")]).then(results=>{const merged:Row[]=[];for(const result of results)if(result.status==="fulfilled")merged.push(...result.value.items);const seen=new Set<string>();const items=merged.filter(row=>{const key=`${row.type}:${row.id}`;if(seen.has(key))return false;seen.add(key);return true;}).sort((a,b)=>({CRITICAL:0,WARNING:1,INFO:2}[a.severity]-{CRITICAL:0,WARNING:1,INFO:2}[b.severity])||(new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime()));setData({items,summary:{total:items.length,critical:items.filter(x=>x.severity==="CRITICAL").length,approvals:items.filter(x=>x.type.endsWith("APPROVAL")||x.type==="CONFIGURABLE_APPROVAL").length}});if(results.every(result=>result.status==="rejected"))setError("Unable to load action centre.");}).finally(()=>setLoading(false));};useEffect(()=>{void load();},[]);const visible=useMemo(()=>data?.items.filter(row=>filter==="ALL"?true:filter==="APPROVALS"?(row.type.endsWith("APPROVAL")||row.type==="CONFIGURABLE_APPROVAL"):row.severity===filter)??[],[data,filter]);return <>
<section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">MANAGEMENT QUEUE · EXCEPTIONS BEFORE INFORMATION</span><h2>Fleet Action Centre</h2><p>A single decision surface for approvals, configurable governance, critical exceptions and unresolved operational risks across the fleet.</p></div><button className="button-v2 secondary" onClick={()=>void load()}><Icon name="command" size={15}/>Refresh queue</button></section>
{error&&<div className="error-box">{error}</div>}
<div className="mini-kpi-grid-v2 four-v2"><div><span>Open actions</span><b>{data?.summary?.total??0}</b><small>Authorized items requiring attention</small></div><div className={(data?.summary?.critical??0)>0?"danger":"good"}><span>Critical exceptions</span><b>{data?.summary?.critical??0}</b><small>Highest operational severity</small></div><div className={(data?.summary?.approvals??0)>0?"warning":"good"}><span>Approval queue</span><b>{data?.summary?.approvals??0}</b><small>Authoritative + configurable decisions</small></div><div className="info"><span>Control mode</span><b>LIVE</b><small>Permission-aware workspace</small></div></div>
<section className="panel-v2 action-centre-panel"><div className="fleet-toolbar-v2"><div><span className="panel-kicker">PRIORITIZED CONTROL QUEUE</span><h3>What requires a decision now</h3></div><div className="filter-tabs-v2">{actionFilters.map(([v,l])=><button key={v} className={filter===v?"active":""} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>{loading?<div className="search-state"><span className="loading-ring small"/>Loading decision queue…</div>:<div className="action-centre-list">{visible.map((row,index)=><article className={`action-centre-row sev-${row.severity}`} key={`${row.type}-${row.id}`}><div className="action-index">{String(index+1).padStart(2,"0")}</div><div className="action-severity-icon"><Icon name={row.severity==="CRITICAL"?"alert":row.type.includes("APPROVAL")?"shield":"bell"} size={18}/></div><div className="action-centre-copy"><div className="action-meta"><span>{typeLabel(row.type)}</span><time>{new Date(row.createdAt).toLocaleString()}</time></div><b>{row.title}</b><p>{row.subtitle}</p></div><span className={`status-pill-v2 action-${row.severity}`}><i/>{row.severity}</span><Link className="button-v2 secondary small-v6" to={row.href}>Open control →</Link></article>)}{!visible.length&&<div className="empty-state-v2 action-empty"><Icon name="shield" size={28}/><b>No actions in this view</b><span>The selected queue is clear. New authorized exceptions and approvals will surface here automatically.</span></div>}</div>}</section>
<div className="manager-control-note-v2"><Icon name="shield"/><div><b>Separation of duties remains enforced</b><span>The Action Centre only routes you into the authoritative source workflow or configured approval request. It never bypasses trip, fuel, maintenance, procurement, disposal or maker/checker controls.</span></div></div>
</>}
