import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type Assignment={id:string;assignmentType:string;status:string;purpose?:string|null;startAt:string;endAt?:string|null;handoverConfirmed:boolean;vehicle:{id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string};driver:{id:string;employeeNumber:string;fullName:string;status:string;licenceExpiry:string};assignedBy:{fullName:string}};
type Vehicle={id:string;registrationNumber:string;make:string;model:string;status:string};
type Driver={id:string;employeeNumber:string;fullName:string;status:string;licenceExpiry:string};
const assignmentFilters=[["ACTIVE","Active"],["PRIMARY","Primary"],["TEMPORARY","Temporary"],["ALL","All history"]] as const;

export function AssignmentsPage(){
  const{me}=useAuth();
  const[items,setItems]=useState<Assignment[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[drivers,setDrivers]=useState<Driver[]>([]);
  const[show,setShow]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("ACTIVE");
  const selfOnly=!me?.permissions.includes("assignment.view");
  const load=async()=>{try{const result=await api<{items:Assignment[]}>("/assignments");setItems(result.items);if(me?.permissions.includes("assignment.create")){const[vehicleResult,driverResult]=await Promise.all([api<{items:Vehicle[]}>("/vehicles?limit=100"),api<{items:Driver[]}>("/drivers?limit=100")]);setVehicles(vehicleResult.items.filter(v=>["AVAILABLE","PARKED","SERVICE_DUE"].includes(v.status)));setDrivers(driverResult.items.filter(d=>d.status==="ACTIVE"&&new Date(d.licenceExpiry)>=new Date()));}}catch(e){setError(e instanceof Error?e.message:"Unable to load assignments.");}};
  useEffect(()=>{void load();},[]);
  const stats=useMemo(()=>({active:items.filter(a=>a.status==="ACTIVE").length,primary:items.filter(a=>a.status==="ACTIVE"&&a.assignmentType==="PRIMARY").length,temporary:items.filter(a=>a.status==="ACTIVE"&&a.assignmentType==="TEMPORARY").length,pending:items.filter(a=>a.status==="ACTIVE"&&!a.handoverConfirmed).length}),[items]);
  const visible=useMemo(()=>items.filter(a=>{const q=query.trim().toLowerCase();const matchesQ=!q||[a.vehicle.registrationNumber,a.vehicle.fleetNumber??"",a.vehicle.make,a.vehicle.model,a.driver.fullName,a.driver.employeeNumber,a.purpose??""].some(v=>v.toLowerCase().includes(q));const matchesFilter=filter==="ALL"?true:filter==="ACTIVE"?a.status==="ACTIVE":a.status==="ACTIVE"&&a.assignmentType===filter;return matchesQ&&matchesFilter;}),[items,query,filter]);
  const current=selfOnly?items.find(a=>a.status==="ACTIVE")??null:null;
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{await api("/assignments",{method:"POST",body:JSON.stringify({vehicleId:f.get("vehicleId"),driverId:f.get("driverId"),assignmentType:f.get("assignmentType"),purpose:f.get("purpose")||undefined,handoverConfirmed:f.get("handoverConfirmed")==="on"})});event.currentTarget.reset();setShow(false);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create assignment.");}finally{setBusy(false);}};
  const endAssignment=async(a:Assignment)=>{const reason=window.prompt(`Reason for ending ${a.vehicle.registrationNumber} → ${a.driver.fullName}:`);if(!reason)return;try{await api(`/assignments/${a.id}/end`,{method:"POST",body:JSON.stringify({reason,handoverConfirmed:true})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to end assignment.");}};

  if(selfOnly)return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">DRIVER · VEHICLE ACCOUNTABILITY</span><h2>My Vehicle</h2><p>Your assigned truck, handover status and the controls that must be satisfied before movement.</p></div></section>
    {error&&<div className="error-box">{error}</div>}
    {current?<div className="driver-vehicle-layout-v2"><section className="driver-vehicle-card-v2"><div className="driver-vehicle-hero-v2"><div className="driver-truck-icon"><Icon name="vehicle" size={28}/></div><div><span>CURRENT ASSIGNMENT</span><h3>{current.vehicle.registrationNumber}</h3><p>{current.vehicle.make} {current.vehicle.model}</p></div><span className={`status-pill-v2 s-${current.vehicle.status}`}><i/>{current.vehicle.status.replaceAll("_"," ")}</span></div><div className="driver-vehicle-facts-v2"><div><span>Fleet number</span><b>{current.vehicle.fleetNumber||"—"}</b></div><div><span>Assignment type</span><b>{current.assignmentType.replaceAll("_"," ")}</b></div><div><span>Assigned since</span><b>{new Date(current.startAt).toLocaleDateString()}</b></div><div><span>Handover</span><b>{current.handoverConfirmed?"Confirmed":"Pending"}</b></div></div>{current.purpose&&<div className="driver-assignment-purpose"><span>Assignment purpose</span><b>{current.purpose}</b></div>}<div className="driver-vehicle-actions-v2"><Link to="/trips" className="button-v2 primary"><Icon name="trip" size={16}/> My trips</Link><Link to="/inspections" className="button-v2 secondary"><Icon name="inspection" size={16}/> Start inspection</Link></div></section><aside className="driver-gate-card-v2"><span className="panel-kicker">BEFORE YOU MOVE</span><h3>Dispatch safety gate</h3><div className="gate-list-v2"><div><Icon name="check"/><span>Vehicle must be operational</span></div><div><Icon name="check"/><span>Trip must be approved and allocated</span></div><div><Icon name="check"/><span>Pre-trip inspection must pass</span></div><div><Icon name="check"/><span>Starting odometer must be recorded</span></div></div><p>No driver can override a grounded, workshop or failed-inspection state.</p></aside></div>:<div className="empty-state-card-v2"><Icon name="vehicle" size={34}/><h3>No active vehicle assignment</h3><p>Fleet Management must allocate a truck before it appears in your driver workspace.</p></div>}
    <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">ASSIGNMENT HISTORY</span><h3>My vehicle accountability record</h3><p>Previous and current assignments linked to your driver account.</p></div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Vehicle</th><th>Type</th><th>Start</th><th>End</th><th>Handover</th><th>Status</th></tr></thead><tbody>{items.length?items.map(a=><tr key={a.id}><td><b>{a.vehicle.registrationNumber}</b><span className="cell-sub-v2">{a.vehicle.make} {a.vehicle.model}</span></td><td>{a.assignmentType.replaceAll("_"," ")}</td><td>{new Date(a.startAt).toLocaleString()}</td><td>{a.endAt?new Date(a.endAt).toLocaleString():"—"}</td><td>{a.handoverConfirmed?"Confirmed":"Pending"}</td><td><span className={`status-pill-v2 assignment-${a.status}`}><i/>{a.status}</span></td></tr>):<tr><td colSpan={6}><div className="empty-state-v2"><Icon name="assignment"/><b>No assignment history yet</b></div></td></tr>}</tbody></table></div></section>
  </>;

  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">DRIVER ↔ VEHICLE CONTROL · ONE ACTIVE LINK</span><h2>Vehicle Assignments</h2><p>Control who is responsible for each truck, when that responsibility started, and whether physical handover is confirmed.</p></div>{me?.permissions.includes("assignment.create")&&<button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"plus"} size={16}/>{show?"Close form":"Assign vehicle"}</button>}</section>
    {error&&<div className="error-box">{error}</div>}
    <div className="mini-kpi-grid-v2 four-v2"><div className="good"><span>Active assignments</span><b>{stats.active}</b><small>Current accountability links</small></div><div><span>Primary</span><b>{stats.primary}</b><small>Primary driver ↔ vehicle</small></div><div className="info"><span>Temporary</span><b>{stats.temporary}</b><small>Relief or short-term allocation</small></div><div className={stats.pending?"warning":"good"}><span>Handover pending</span><b>{stats.pending}</b><small>Requires physical confirmation</small></div></div>
    {show&&<form className="panel-v2 create-panel-v2" onSubmit={create}><div className="panel-head-v2"><div><span className="panel-kicker">NEW ACCOUNTABILITY LINK</span><h3>Assign driver to vehicle</h3><p>Only eligible vehicles and active drivers with valid licences are shown. Server rules remain authoritative.</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Vehicle<select name="vehicleId" required><option value="">Select eligible vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.make} {v.model} · {v.status}</option>)}</select></label><label>Driver<select name="driverId" required><option value="">Select authorized driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.employeeNumber} · {d.fullName}</option>)}</select></label><label>Assignment type<select name="assignmentType" defaultValue="PRIMARY"><option value="PRIMARY">Primary</option><option value="TEMPORARY">Temporary</option></select></label><label>Purpose<input name="purpose" placeholder="Primary truck / relief duty / temporary cover"/></label><label className="check-v2"><input name="handoverConfirmed" type="checkbox"/> Physical handover confirmed</label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy?"Assigning…":"Create assignment"}</button><button className="button-v2 secondary" type="button" onClick={()=>setShow(false)}>Cancel</button></div></div></form>}
    <div className="manager-control-note-v2"><Icon name="shield"/><div><b>Assignment guardrails</b><span>Grounded, workshop and unavailable vehicles are blocked. Suspended, inactive and expired-licence drivers cannot be assigned, and the database prevents duplicate active vehicle or driver assignments.</span></div></div>
    <section className="panel-v2"><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vehicle, driver, fleet no. or purpose"/></div><div className="filter-tabs-v2">{assignmentFilters.map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Vehicle</th><th>Driver</th><th>Accountability</th><th>Started</th><th>Handover</th><th>Status</th><th>Created by</th><th>Control</th></tr></thead><tbody>{visible.length?visible.map(a=><tr key={a.id}><td><div className="vehicle-cell-v2"><span className="vehicle-symbol-v2"><Icon name="vehicle" size={17}/></span><div><b>{a.vehicle.registrationNumber}</b><span>{a.vehicle.make} {a.vehicle.model}</span></div></div></td><td><b>{a.driver.fullName}</b><span className="cell-sub-v2">{a.driver.employeeNumber}</span></td><td><span className={`assignment-type-v2 ${a.assignmentType.toLowerCase()}`}>{a.assignmentType}</span><span className="cell-sub-v2">{a.purpose||"No purpose note"}</span></td><td>{new Date(a.startAt).toLocaleString()}</td><td><span className={a.handoverConfirmed?"handover-ok":"handover-pending"}>{a.handoverConfirmed?"Confirmed":"Pending"}</span></td><td><span className={`status-pill-v2 assignment-${a.status}`}><i/>{a.status}</span></td><td>{a.assignedBy.fullName}</td><td>{a.status==="ACTIVE"&&me?.permissions.includes("assignment.end")?<button className="mini-action-v2 danger" onClick={()=>void endAssignment(a)}>End assignment</button>:"—"}</td></tr>):<tr><td colSpan={8}><div className="empty-state-v2"><Icon name="assignment" size={24}/><b>No assignments match this view</b><span>Change the filter or search term.</span></div></td></tr>}</tbody></table></div></section>
  </>;
}
