import { useEffect, useState, type FormEvent } from "react";
import { api } from "../api/client";
import { DataTable } from "../components/DataTable";
import { useAuth } from "../auth/AuthContext";

type Assignment = { id:string; assignmentType:string; status:string; purpose?:string|null; startAt:string; endAt?:string|null; handoverConfirmed:boolean; vehicle:{id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string}; driver:{id:string;employeeNumber:string;fullName:string;status:string;licenceExpiry:string}; assignedBy:{fullName:string} };
type Vehicle={id:string;registrationNumber:string;make:string;model:string;status:string}; type Driver={id:string;employeeNumber:string;fullName:string;status:string;licenceExpiry:string};
export function AssignmentsPage(){const{me}=useAuth();const[items,setItems]=useState<Assignment[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[show,setShow]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
const load=async()=>{try{const result=await api<{items:Assignment[]}>("/assignments");setItems(result.items);if(me?.permissions.includes("assignment.create")){const[vehicleResult,driverResult]=await Promise.all([api<{items:Vehicle[]}>("/vehicles?limit=100"),api<{items:Driver[]}>("/drivers?limit=100")]);setVehicles(vehicleResult.items.filter(v=>["AVAILABLE","PARKED","SERVICE_DUE"].includes(v.status)));setDrivers(driverResult.items.filter(d=>d.status==="ACTIVE"&&new Date(d.licenceExpiry)>=new Date()));}}catch(e){setError(e instanceof Error?e.message:"Unable to load assignments.");}};useEffect(()=>{void load();},[]);
const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");const f=new FormData(event.currentTarget);try{await api("/assignments",{method:"POST",body:JSON.stringify({vehicleId:f.get("vehicleId"),driverId:f.get("driverId"),assignmentType:f.get("assignmentType"),purpose:f.get("purpose")||undefined,handoverConfirmed:f.get("handoverConfirmed")==="on"})});event.currentTarget.reset();setShow(false);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create assignment.");}finally{setBusy(false);}};
const endAssignment=async(a:Assignment)=>{const reason=window.prompt(`Reason for ending ${a.vehicle.registrationNumber} → ${a.driver.fullName}:`);if(!reason)return;try{await api(`/assignments/${a.id}/end`,{method:"POST",body:JSON.stringify({reason,handoverConfirmed:true})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to end assignment.");}};const selfOnly=!me?.permissions.includes("assignment.view");return <><div className="section-head"><div><span className="eyebrow">Driver–vehicle control</span><h2>{selfOnly?"My Vehicle":"Vehicle Assignments"}</h2></div>{me?.permissions.includes("assignment.create")&&<button className="primary compact" onClick={()=>setShow(!show)}>{show?"Close":"+ Assign vehicle"}</button>}</div>{error&&<div className="error-box">{error}</div>}{show&&<form className="panel form-grid" onSubmit={create}><label>Vehicle<select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.make} {v.model}</option>)}</select></label><label>Driver<select name="driverId" required><option value="">Select authorized driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.employeeNumber} · {d.fullName}</option>)}</select></label><label>Assignment type<select name="assignmentType" defaultValue="PRIMARY"><option value="PRIMARY">Primary</option><option value="TEMPORARY">Temporary</option></select></label><label>Purpose<input name="purpose" placeholder="Primary truck / relief duty"/></label><label className="check"><input name="handoverConfirmed" type="checkbox"/> Handover confirmed</label><button className="primary" disabled={busy}>{busy?"Assigning…":"Create assignment"}</button></form>}<div className="callout"><b>Control:</b> grounded, overdue-service, workshop and otherwise unavailable vehicles cannot be assigned. Suspended, inactive or expired-licence drivers are blocked server-side.</div><div className="panel"><DataTable headers={["Vehicle","Driver","Type","Start","Status","Handover","Action"]} rows={items.map(a=>[<b>{a.vehicle.registrationNumber}</b>,`${a.driver.employeeNumber} · ${a.driver.fullName}`,a.assignmentType.replaceAll("_"," "),new Date(a.startAt).toLocaleString(),<span className={`badge ${a.status==="ACTIVE"?"s-AVAILABLE":""}`}>{a.status}</span>,a.handoverConfirmed?"Confirmed":"Pending",a.status==="ACTIVE"&&me?.permissions.includes("assignment.end")?<button className="ghost table-action" onClick={()=>void endAssignment(a)}>End</button>:"—"])}/></div></>}
