import { useEffect,useMemo,useState,type FormEvent } from "react";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type Alert={id:string;kind:string;severity:"critical"|"warning"|"info";entityType:string;entityId:string;entityLabel:string;title:string;detail:string;dueAt?:string};
type AlertResponse={items:Alert[];summary:{critical:number;warning:number;info:number;total:number}};
type DocumentRow={id:string;type:string;referenceNumber:string;provider?:string|null;issueDate?:string|null;expiryDate:string;notes?:string|null;documentUrl?:string|null;vehicle:{id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string};createdBy:{fullName:string}};
type Vehicle={id:string;registrationNumber:string;make:string;model:string;status:string};
const alertFilters=[["ALL","All alerts"],["critical","Critical"],["warning","Warning"],["info","Upcoming"]] as const;
const docTypes=["INSURANCE","ROAD_LICENCE","FITNESS","THIRD_PARTY","TAX","WARRANTY","OTHER"] as const;

export function CompliancePage(){
  const{me}=useAuth();const canManage=me?.permissions.includes("compliance.manage")??false;const[alerts,setAlerts]=useState<AlertResponse>({items:[],summary:{critical:0,warning:0,info:0,total:0}}),[documents,setDocuments]=useState<DocumentRow[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[show,setShow]=useState(false),[filter,setFilter]=useState("ALL"),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{try{const jobs:[Promise<AlertResponse>,Promise<{items:DocumentRow[]}>]=[api<AlertResponse>("/compliance/alerts"),api<{items:DocumentRow[]}>("/compliance/documents")];const[a,d]=await Promise.all(jobs);setAlerts(a);setDocuments(d.items);if(canManage&&me?.permissions.includes("vehicle.view")){const v=await api<{items:Vehicle[]}>("/vehicles?limit=100");setVehicles(v.items);}}catch(e){setError(e instanceof Error?e.message:"Unable to load compliance controls.");}};
  useEffect(()=>{void load();},[]);
  const visibleAlerts=useMemo(()=>alerts.items.filter(a=>{const q=query.trim().toLowerCase();const matches=!q||[a.entityLabel,a.title,a.detail,a.kind].some(v=>v.toLowerCase().includes(q));return matches&&(filter==="ALL"||a.severity===filter);}),[alerts.items,query,filter]);
  const expiryStats=useMemo(()=>{const now=Date.now();return{expired:documents.filter(d=>new Date(d.expiryDate).getTime()<now).length,due30:documents.filter(d=>{const x=(new Date(d.expiryDate).getTime()-now)/86400000;return x>=0&&x<=30;}).length,valid:documents.filter(d=>(new Date(d.expiryDate).getTime()-now)/86400000>30).length};},[documents]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const form=e.currentTarget,f=new FormData(form);try{await api("/compliance/documents",{method:"POST",body:JSON.stringify({vehicleId:f.get("vehicleId"),type:f.get("type"),referenceNumber:f.get("referenceNumber"),provider:f.get("provider")||undefined,issueDate:f.get("issueDate")||undefined,expiryDate:f.get("expiryDate"),notes:f.get("notes")||undefined,documentUrl:f.get("documentUrl")||undefined})});form.reset();setShow(false);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to save compliance document.");}finally{setBusy(false);}};
  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">RISK CONTROL · EXPIRY · ROADWORTHINESS · SERVICE EXPOSURE</span><h2>Alerts & Compliance</h2><p>One risk register across vehicle documents, driver licence expiry, service due/overdue states, grounded vehicles and critical inspection failures.</p></div>{canManage&&<button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"plus"} size={16}/>{show?"Close form":"Add compliance document"}</button>}</section>
    {error&&<div className="error-box">{error}</div>}
    <div className="mini-kpi-grid-v2 five-v2"><div className={alerts.summary.critical?"danger":"good"}><span>Critical alerts</span><b>{alerts.summary.critical}</b><small>Expired, grounded or safety failure</small></div><div className={alerts.summary.warning?"warning":"good"}><span>Warnings</span><b>{alerts.summary.warning}</b><small>Near-term action required</small></div><div className="info"><span>Upcoming</span><b>{alerts.summary.info}</b><small>Planning horizon alerts</small></div><div className={expiryStats.expired?"danger":"good"}><span>Expired documents</span><b>{expiryStats.expired}</b><small>Compliance records past expiry</small></div><div><span>Valid documents</span><b>{expiryStats.valid}</b><small>{expiryStats.due30} due within 30 days</small></div></div>
    {show&&<form className="panel-v2 create-panel-v2" onSubmit={create}><div className="panel-head-v2"><div><span className="panel-kicker">VEHICLE COMPLIANCE REGISTER</span><h3>Add controlled document</h3><p>Expiry dates automatically feed the live management alert queue.</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Vehicle<select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.make} {v.model}</option>)}</select></label><label>Document type<select name="type" required>{docTypes.map(t=><option key={t} value={t}>{t.replaceAll("_"," ")}</option>)}</select></label><label>Reference number<input name="referenceNumber" required/></label><label>Provider / authority<input name="provider"/></label><label>Issue date<input name="issueDate" type="date"/></label><label>Expiry date<input name="expiryDate" type="date" required/></label><label className="span-2">Document URL<input name="documentUrl" type="url" placeholder="Optional secure document location"/></label><label className="span-2">Notes<textarea name="notes" rows={3}/></label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy?"Saving…":"Save compliance document"}</button><button className="button-v2 secondary" type="button" onClick={()=>setShow(false)}>Cancel</button></div></div></form>}
    <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">PRIORITY RISK QUEUE</span><h3>Management attention</h3><p>Automatically derived from operational and compliance records.</p></div></div><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vehicle, driver, alert type or issue"/></div><div className="filter-tabs-v2">{alertFilters.map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="compliance-alert-grid-v3">{visibleAlerts.length?visibleAlerts.map(alert=><article key={alert.id} className={`compliance-alert-v3 ${alert.severity}`}><span className="alert-icon-v3"><Icon name={alert.severity==="critical"?"alert":alert.kind==="SERVICE"?"wrench":"calendar"} size={18}/></span><div><div className="alert-meta-v3"><span>{alert.kind.replaceAll("_"," ")}</span><b>{alert.entityLabel}</b></div><h4>{alert.title}</h4><p>{alert.detail}</p>{alert.dueAt&&<time>{new Date(alert.dueAt).toLocaleDateString()}</time>}</div><span className={`severity-chip-v3 ${alert.severity}`}>{alert.severity}</span></article>):<div className="empty-state-v2"><Icon name="check" size={28}/><b>No alerts match this view</b><span>The current filter has no fleet risks to surface.</span></div>}</div></section>
    <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">CONTROLLED DOCUMENT REGISTER</span><h3>Vehicle compliance documents</h3><p>Insurance, licensing, fitness, tax, warranty and other expiry-controlled records.</p></div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Vehicle</th><th>Document</th><th>Reference</th><th>Provider</th><th>Issue</th><th>Expiry</th><th>State</th><th>Recorded by</th></tr></thead><tbody>{documents.length?documents.map(doc=>{const days=Math.ceil((new Date(doc.expiryDate).getTime()-Date.now())/86400000);const state=days<0?"EXPIRED":days<=30?"DUE SOON":"VALID";return <tr key={doc.id}><td><b>{doc.vehicle.registrationNumber}</b><span className="cell-sub-v2">{doc.vehicle.make} {doc.vehicle.model}</span></td><td>{doc.type.replaceAll("_"," ")}</td><td><b>{doc.referenceNumber}</b></td><td>{doc.provider||"—"}</td><td>{doc.issueDate?new Date(doc.issueDate).toLocaleDateString():"—"}</td><td>{new Date(doc.expiryDate).toLocaleDateString()}<span className="cell-sub-v2">{days<0?`${Math.abs(days)} days overdue`:`${days} days remaining`}</span></td><td><span className={`compliance-state-v3 ${state.replaceAll(" ","-").toLowerCase()}`}>{state}</span></td><td>{doc.createdBy.fullName}</td></tr>}):<tr><td colSpan={8}><div className="empty-state-v2"><Icon name="calendar"/><b>No compliance documents recorded</b></div></td></tr>}</tbody></table></div></section>
  </>;
}
