import { useEffect,useMemo,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { api } from "../api/client";
import { DriverAvatar } from "../components/DriverAvatar";
import { Icon } from "../components/Icon";

type Data={driver:{id:string;employeeNumber:string;fullName:string;phone?:string|null;email?:string|null;licenceNumber:string;licenceClass:string;licenceExpiry:string;status:string;photoEndpoint?:string|null;branch?:{name:string}|null;department?:{name:string}|null;user?:{id:string;email:string;status:string;lastLoginAt?:string|null}|null};assignment?:{startAt:string;assignmentType:string;purpose?:string|null;vehicle:{id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string;currentOdometerKm:number}}|null;trips:Array<{id:string;tripNumber:string;purpose:string;origin:string;destination:string;status:string;requestedDeparture:string;distanceKm?:number|null}>;score?:{score:number;riskBand:string;periodStart:string;periodEnd:string;safetyEventPoints:number;incidentPoints:number;inspectionPoints:number;calculatedAt:string}|null;safetyEvents:Array<{id:string;type:string;penaltyPoints:number;description:string;occurredAt:string}>;incidents:Array<{id:string;incidentNumber:string;type:string;severity:string;status:string;occurredAt:string;location:string}>;inspections:Array<{id:string;type:string;status:string;odometerKm:number;completedAt?:string|null;createdAt:string;vehicle:{registrationNumber:string}}>;fuel:Array<{id:string;requestNumber:string;status:string;requestedLitres:string|number;issuedLitres?:string|number|null;totalCost?:string|number|null;requestedAt:string;vehicle:{registrationNumber:string}}>;dispatches:Array<{id:string;dispatchNumber:string;status:string;plannedDeparture:string;plannedReturn:string}>;summary:{totalDistanceKm:number;completedTrips:number;failedInspections:number;openIncidents:number;licenceDaysRemaining:number}};
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString():"—";const scoreTone=(score:number)=>score>=90?"good":score>=75?"info":score>=60?"warning":"danger";

export function Driver360Page(){const{id}=useParams();const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{if(!id)return;setLoading(true);void api<Data>(`/workspace/drivers/${id}`).then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load Driver 360.")).finally(()=>setLoading(false));},[id]);const readiness=useMemo(()=>data?{licence:data.summary.licenceDaysRemaining,score:data.score?.score??null,active:data.driver.status==="ACTIVE",portal:data.driver.user?.status==="ACTIVE"}:null,[data]);if(loading)return <div className="loading-screen inline-loading">Loading Driver 360…</div>;if(error||!data)return <div className="error-box">{error||"Driver profile unavailable."}</div>;const d=data.driver;return <>
<section className="page-hero-v2 driver360-hero"><div><span className="eyebrow-v2">DRIVER 360 · READINESS & ACCOUNTABILITY</span><div className="driver360-title"><DriverAvatar name={d.fullName} photoEndpoint={d.photoEndpoint??null} size="medium"/><div><h2>{d.fullName}</h2><p>{d.employeeNumber} · Licence {d.licenceNumber} · Class {d.licenceClass}</p></div></div></div><div className="hero-actions-v3"><Link className="button-v2 secondary" to="/drivers">← Driver register</Link>{data.assignment&&<Link className="button-v2 primary" to={`/vehicles/${data.assignment.vehicle.id}`}><Icon name="vehicle" size={15}/>Open assigned vehicle</Link>}</div></section>
<div className="driver360-statusbar"><span className={`status-pill-v2 driver-${d.status}`}><i/>{d.status.replaceAll("_"," ")}</span><span className={readiness?.licence!=null&&readiness.licence<=30?"danger-text-v4":""}><b>{readiness?.licence??"—"}</b> licence days remaining</span><span><b>{data.summary.completedTrips}</b> completed trips</span><span><b>{data.summary.totalDistanceKm.toLocaleString()} km</b> recorded distance</span></div>
<div className="mini-kpi-grid-v2 five-v2"><div className={readiness?.active?"good":"danger"}><span>Driver status</span><b>{readiness?.active?"READY":"BLOCKED"}</b><small>{d.status.replaceAll("_"," ")}</small></div><div className={data.score?scoreTone(data.score.score):"warning"}><span>Safety score</span><b>{data.score?.score??"—"}</b><small>{data.score?.riskBand??"Not yet calculated"}</small></div><div className={data.summary.openIncidents?"danger":"good"}><span>Open incidents</span><b>{data.summary.openIncidents}</b><small>Unresolved safety cases</small></div><div className={data.summary.failedInspections?"warning":"good"}><span>Failed inspections</span><b>{data.summary.failedInspections}</b><small>Recent inspection history</small></div><div className={readiness?.portal?"good":"warning"}><span>Portal readiness</span><b>{readiness?.portal?"ACTIVE":"CHECK"}</b><small>{d.user?.status??"No portal account"}</small></div></div>
<div className="vehicle360-grid">
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">DRIVER MASTER</span><h3>Identity & authorization</h3></div></div><div className="detail-grid-v2 panel-body-v2"><div><span>Employee number</span><b>{d.employeeNumber}</b></div><div><span>Driver status</span><b>{d.status.replaceAll("_"," ")}</b></div><div><span>Licence number</span><b>{d.licenceNumber}</b></div><div><span>Licence class</span><b>{d.licenceClass}</b></div><div><span>Licence expiry</span><b>{date(d.licenceExpiry)}</b></div><div><span>Branch</span><b>{d.branch?.name||"—"}</b></div><div><span>Department</span><b>{d.department?.name||"—"}</b></div><div><span>Phone</span><b>{d.phone||"—"}</b></div><div className="detail-wide"><span>Email</span><b>{d.email||d.user?.email||"—"}</b></div></div></section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">CURRENT ACCOUNTABILITY</span><h3>Vehicle assignment</h3></div><Link to="/assignments">Assignments →</Link></div><div className="panel-body-v2">{data.assignment?<div className="current-vehicle-card-v6"><span className="vehicle360-mark"><Icon name="vehicle" size={24}/></span><div><b>{data.assignment.vehicle.registrationNumber}</b><small>{data.assignment.vehicle.make} {data.assignment.vehicle.model} · {data.assignment.assignmentType}</small><span>{data.assignment.vehicle.currentOdometerKm.toLocaleString()} km · {data.assignment.vehicle.status.replaceAll("_"," ")}</span></div><Link to={`/vehicles/${data.assignment.vehicle.id}`}>Vehicle 360 →</Link></div>:<div className="empty-state-v2"><Icon name="assignment" size={24}/><b>No active vehicle assignment</b><span>The driver is not currently accountable for a fleet vehicle.</span></div>}</div></section>
</div>
{data.score&&<section className="panel-v2 score-breakdown-v6"><div className="panel-head-v2"><div><span className="panel-kicker">TRANSPARENT SAFETY SCORING</span><h3>{data.score.score}/100 · {data.score.riskBand}</h3><p>Calculated from recorded fleet evidence for {date(data.score.periodStart)} – {date(data.score.periodEnd)}.</p></div><Link to="/driver-safety">Safety workspace →</Link></div><div className="score-breakdown-grid"><div><span>Safety events</span><b>-{data.score.safetyEventPoints}</b></div><div><span>Incidents</span><b>-{data.score.incidentPoints}</b></div><div><span>Inspection failures</span><b>-{data.score.inspectionPoints}</b></div><div><span>Calculated</span><b>{date(data.score.calculatedAt)}</b></div></div></section>}
<div className="vehicle360-grid wide-left">
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">MOVEMENT HISTORY</span><h3>Recent trips</h3></div><Link to="/trips">Trip Control →</Link></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Trip</th><th>Route</th><th>Status</th><th>Distance</th></tr></thead><tbody>{data.trips.map(x=><tr key={x.id}><td><b>{x.tripNumber}</b><span className="cell-sub-v2">{date(x.requestedDeparture)}</span></td><td><b>{x.origin} → {x.destination}</b><span className="cell-sub-v2">{x.purpose}</span></td><td><span className={`status-pill-v2 s-${x.status}`}><i/>{x.status.replaceAll("_"," ")}</span></td><td>{x.distanceKm?.toLocaleString()??"—"} km</td></tr>)}{!data.trips.length&&<tr><td colSpan={4}>No trip history.</td></tr>}</tbody></table></div></section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">SAFETY EVIDENCE</span><h3>Recent events</h3></div></div><div className="panel-body-v2 compact-stack">{data.safetyEvents.slice(0,8).map(x=><div className={`record-card-v6 ${x.penaltyPoints>0?"attention":""}`} key={x.id}><div><b>{x.type.replaceAll("_"," ")}</b><small>{x.description}</small></div><span>{x.penaltyPoints>0?`-${x.penaltyPoints} pts`:"0 pts"}<small> · {date(x.occurredAt)}</small></span></div>)}{!data.safetyEvents.length&&<div className="empty-strip">No recorded safety events.</div>}</div></section>
</div>
<div className="vehicle360-grid"><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">ROADWORTHINESS</span><h3>Inspection record</h3></div><Link to="/inspections">Inspections →</Link></div><div className="panel-body-v2 compact-stack">{data.inspections.slice(0,8).map(x=><div className={`record-card-v6 ${x.status==="FAILED"?"attention":""}`} key={x.id}><div><b>{x.vehicle.registrationNumber} · {x.type.replaceAll("_"," ")}</b><small>{x.odometerKm.toLocaleString()} km</small></div><span>{x.status.replaceAll("_"," ")}<small> · {date(x.completedAt??x.createdAt)}</small></span></div>)}{!data.inspections.length&&<div className="empty-strip">No inspections recorded.</div>}</div></section><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">INCIDENT HISTORY</span><h3>Safety cases</h3></div><Link to="/incidents">Incidents →</Link></div><div className="panel-body-v2 compact-stack">{data.incidents.map(x=><div className={`record-card-v6 ${x.status!=="CLOSED"?"attention":""}`} key={x.id}><div><b>{x.incidentNumber} · {x.type}</b><small>{x.location} · {date(x.occurredAt)}</small></div><span>{x.severity}<small> · {x.status}</small></span></div>)}{!data.incidents.length&&<div className="empty-strip">No incidents recorded.</div>}</div></section></div>
<div className="security-strip-v6"><Icon name="shield"/><div><b>Portal account</b><span>{d.user?`${d.user.status} · ${d.user.email} · last login ${d.user.lastLoginAt?new Date(d.user.lastLoginAt).toLocaleString():"never"}`:"No driver portal account provisioned."}</span></div></div>
</>}
