import { useEffect,useMemo,useState,type FormEvent } from "react";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type FuelRow={id:string;requestNumber:string;status:string;fuelType:string;requestedLitres:string|number;issuedLitres?:string|number|null;unitPrice?:string|number|null;totalCost?:string|number|null;station?:string|null;odometerKm:number;receiptNumber?:string|null;notes?:string|null;rejectionReason?:string|null;requestedAt:string;approvedAt?:string|null;issuedAt?:string|null;vehicle:{id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;fuelType:string;currentOdometerKm:number};driver?:{id:string;employeeNumber:string;fullName:string}|null;trip?:{id:string;tripNumber:string;origin:string;destination:string}|null;requestedBy:{fullName:string};approvedBy?:{fullName:string}|null};
type Vehicle={id:string;registrationNumber:string;make:string;model:string;status:string;currentOdometerKm:number;fuelType:string};
type Assignment={id:string;status:string;vehicle:{id:string;registrationNumber:string;make:string;model:string;status:string;currentOdometerKm?:number;fuelType?:string}};
type Trip={id:string;tripNumber:string;status:string;vehicle?:{id:string;registrationNumber:string;currentOdometerKm:number}|null};
const filters=[["ALL","All"],["REQUESTED","Pending approval"],["APPROVED","Approved"],["ISSUED","Issued"],["REJECTED","Rejected"]] as const;
const money=(value:string|number|null|undefined)=>`UGX ${Number(value??0).toLocaleString(undefined,{maximumFractionDigits:0})}`;

export function FuelPage(){
  const{me}=useAuth();const isDriver=me?.roles.includes("DRIVER")??false;const canCreate=me?.permissions.includes("fuel.create")??false,canApprove=me?.permissions.includes("fuel.approve")??false;
  const[items,setItems]=useState<FuelRow[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[trips,setTrips]=useState<Trip[]>([]),[show,setShow]=useState(false),[filter,setFilter]=useState("ALL"),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{try{const rows=await api<{items:FuelRow[]}>("/fuel");setItems(rows.items);if(canCreate){if(isDriver){const[a,t]=await Promise.all([api<{items:Assignment[]}>("/assignments"),api<{items:Trip[]}>("/trips")]);setAssignments(a.items);setTrips(t.items);}else if(me?.permissions.includes("vehicle.view")){const[v,t]=await Promise.all([api<{items:Vehicle[]}>("/vehicles?limit=100"),api<{items:Trip[]}>("/trips")]);setVehicles(v.items);setTrips(t.items);}}}catch(e){setError(e instanceof Error?e.message:"Unable to load fuel operations.");}};
  useEffect(()=>{void load();},[]);
  const driverVehicles=useMemo(()=>assignments.filter(a=>a.status==="ACTIVE").map(a=>({id:a.vehicle.id,registrationNumber:a.vehicle.registrationNumber,make:a.vehicle.make,model:a.vehicle.model,status:a.vehicle.status,currentOdometerKm:a.vehicle.currentOdometerKm??0,fuelType:a.vehicle.fuelType??"DIESEL"})),[assignments]);
  const vehicleOptions=isDriver?driverVehicles:vehicles;
  const stats=useMemo(()=>({pending:items.filter(i=>i.status==="REQUESTED").length,approved:items.filter(i=>i.status==="APPROVED").length,issued:items.filter(i=>i.status==="ISSUED").length,litres:items.filter(i=>i.status==="ISSUED").reduce((s,i)=>s+Number(i.issuedLitres??0),0),spend:items.filter(i=>i.status==="ISSUED").reduce((s,i)=>s+Number(i.totalCost??0),0)}),[items]);
  const visible=useMemo(()=>items.filter(i=>{const q=query.trim().toLowerCase();const matches=!q||[i.requestNumber,i.vehicle.registrationNumber,i.driver?.fullName??"",i.trip?.tripNumber??"",i.station??"",i.receiptNumber??""].some(v=>v.toLowerCase().includes(q));return matches&&(filter==="ALL"||i.status===filter);}),[items,query,filter]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const form=e.currentTarget,f=new FormData(form);try{await api("/fuel",{method:"POST",body:JSON.stringify({vehicleId:f.get("vehicleId"),tripId:f.get("tripId")||undefined,requestedLitres:Number(f.get("requestedLitres")),odometerKm:Number(f.get("odometerKm")),station:f.get("station")||undefined,notes:f.get("notes")||undefined})});form.reset();setShow(false);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to request fuel.");}finally{setBusy(false);}};
  const decide=async(row:FuelRow,decision:"APPROVED"|"REJECTED")=>{const comments=window.prompt(decision==="APPROVED"?"Approval note (optional):":"Reason for rejecting fuel request:","");if(decision==="REJECTED"&&!comments)return;try{await api(`/fuel/${row.id}/decision`,{method:"POST",body:JSON.stringify({decision,comments:comments||undefined})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to decide fuel request.");}};
  const issue=async(row:FuelRow)=>{const litres=window.prompt("Litres issued:",String(row.requestedLitres));if(!litres)return;const unitPrice=window.prompt("Unit price (UGX per litre):",String(row.unitPrice??""));if(!unitPrice)return;const station=window.prompt("Fuel station / vendor:",row.station??"");if(!station)return;const receipt=window.prompt("Receipt / voucher number (optional):",row.receiptNumber??"");try{await api(`/fuel/${row.id}/issue`,{method:"POST",body:JSON.stringify({issuedLitres:Number(litres),unitPrice:Number(unitPrice),station,receiptNumber:receipt||undefined,odometerKm:row.odometerKm})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to issue fuel.");}};

  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">FUEL GOVERNANCE · REQUEST → APPROVAL → ISSUE</span><h2>{isDriver?"My Fuel Requests":"Fuel Control"}</h2><p>{isDriver?"Request fuel only for the vehicle currently assigned to you and track approval or issue status from your phone.":"Control fuel requests, independent approval, litres issued, vendor receipts, odometer integrity and fleet fuel spend."}</p></div>{canCreate&&<button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"gauge"} size={16}/>{show?"Close form":"Request fuel"}</button>}</section>
    {error&&<div className="error-box">{error}</div>}
    <div className="mini-kpi-grid-v2 five-v2"><div className={stats.pending?"warning":"good"}><span>Pending approval</span><b>{stats.pending}</b><small>Requests waiting decision</small></div><div className={stats.approved?"info":"good"}><span>Approved to issue</span><b>{stats.approved}</b><small>Authorized, not yet issued</small></div><div className="good"><span>Issued records</span><b>{stats.issued}</b><small>Completed fuel transactions</small></div><div><span>Total litres</span><b>{stats.litres.toLocaleString(undefined,{maximumFractionDigits:1})} L</b><small>Issued in loaded history</small></div><div><span>Fuel spend</span><b>{money(stats.spend)}</b><small>Receipt-backed issued value</small></div></div>
    {show&&<form className="panel-v2 create-panel-v2" onSubmit={create}><div className="panel-head-v2"><div><span className="panel-kicker">FUEL REQUEST</span><h3>Request controlled fuel issue</h3><p>{isDriver?"Only your active assigned vehicle is accepted by the server.":"The request remains pending until an authorized approver records a decision."}</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Vehicle<select name="vehicleId" required onChange={e=>{const v=vehicleOptions.find(x=>x.id===e.target.value);const odo=e.currentTarget.form?.elements.namedItem("odometerKm") as HTMLInputElement|null;if(v&&odo)odo.value=String(v.currentOdometerKm);}}><option value="">Select vehicle</option>{vehicleOptions.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.make} {v.model} · {v.status}</option>)}</select></label><label>Linked trip (optional)<select name="tripId"><option value="">No linked trip</option>{trips.filter(t=>Boolean(t.vehicle)).map(t=><option key={t.id} value={t.id}>{t.tripNumber} · {t.status}</option>)}</select></label><label>Requested litres<input name="requestedLitres" type="number" min="0.1" step="0.1" required/></label><label>Odometer (km)<input name="odometerKm" type="number" min="0" required/></label><label>Preferred station<input name="station" placeholder="Station / vendor (optional)"/></label><label className="span-2">Request note<textarea name="notes" rows={3} placeholder="Route need, tank level, voucher reference or operational note"/></label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy?"Submitting…":"Submit fuel request"}</button><button className="button-v2 secondary" type="button" onClick={()=>setShow(false)}>Cancel</button></div></div></form>}
    <div className="manager-control-note-v2"><Icon name="shield"/><div><b>Independent fuel approval</b><span>The requester cannot approve their own fuel request. Issued litres, unit price, total cost, station, receipt and odometer are preserved for reporting and audit.</span></div></div>
    <section className="panel-v2"><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search request, vehicle, driver, trip, station or receipt"/></div><div className="filter-tabs-v2">{filters.map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Request</th><th>Vehicle / driver</th><th>Fuel</th><th>Odometer</th><th>Approval</th><th>Issue</th><th>Value</th><th>Control</th></tr></thead><tbody>{visible.length?visible.map(row=><tr key={row.id}><td><b>{row.requestNumber}</b><span className="cell-sub-v2">{new Date(row.requestedAt).toLocaleString()}</span></td><td><div className="vehicle-cell-v2"><span className="vehicle-symbol-v2"><Icon name="vehicle" size={16}/></span><div><b>{row.vehicle.registrationNumber}</b><span>{row.driver?.fullName??row.requestedBy.fullName}</span></div></div></td><td><b>{Number(row.issuedLitres??row.requestedLitres).toLocaleString(undefined,{maximumFractionDigits:1})} L</b><span className="cell-sub-v2">{row.fuelType} · {row.status==="ISSUED"?"issued":"requested"}</span></td><td>{row.odometerKm.toLocaleString()} km</td><td><span className={`status-pill-v2 fuel-${row.status}`}><i/>{row.status.replaceAll("_"," ")}</span>{row.approvedBy&&<span className="cell-sub-v2">{row.approvedBy.fullName}</span>}</td><td>{row.station?<><b>{row.station}</b><span className="cell-sub-v2">{row.receiptNumber||"No receipt ref"}</span></>:"—"}</td><td>{row.totalCost!=null?<b>{money(row.totalCost)}</b>:"—"}</td><td><div className="row-actions">{canApprove&&row.status==="REQUESTED"&&<><button className="mini-action-v2 success" onClick={()=>void decide(row,"APPROVED")}>Approve</button><button className="mini-action-v2 danger" onClick={()=>void decide(row,"REJECTED")}>Reject</button></>}{canApprove&&row.status==="APPROVED"&&<button className="mini-action-v2 success" onClick={()=>void issue(row)}>Issue fuel</button>}</div></td></tr>):<tr><td colSpan={8}><div className="empty-state-v2"><Icon name="gauge" size={24}/><b>No fuel records match this view</b><span>Create a request or change the filter.</span></div></td></tr>}</tbody></table></div></section>
  </>;
}
