import { useEffect,useMemo,useState,type FormEvent } from "react";
import { Link,useSearchParams } from "react-router-dom";
import { api,apiBlob } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type TemplateItem={id:string;code:string;label:string;description?:string|null;isCritical:boolean;sortOrder:number};
type Template={id:string;name:string;type:string;description?:string|null;items:TemplateItem[]};
type Trip={id:string;tripNumber:string;status:string;vehicle?:{id:string;registrationNumber:string;currentOdometerKm:number}|null;driver?:{fullName:string}|null};
type Assignment={id:string;status:string;vehicle:{id:string;registrationNumber:string;currentOdometerKm?:number;make:string;model:string}};
type Vehicle={id:string;registrationNumber:string;currentOdometerKm:number;make:string;model:string};
type Inspection={id:string;type:string;status:string;odometerKm:number;completedAt?:string|null;createdAt:string;vehicle:{id:string;registrationNumber:string;make:string;model:string;status:string};driver?:{fullName:string}|null;trip?:{tripNumber:string}|null;results:{labelSnapshot:string;result:string;isCritical:boolean;comment?:string|null}[];loadState?:string|null;currentLocation?:string|null;vehicleBehavior?:string|null;repairRequest?:string|null;driverCanContinue?:boolean|null;healthState?:string;managerStatus?:string;managerNote?:string|null;workOrderId?:string|null;evidenceCount?:number};
type Evidence={id:string;mimeType:string;originalName:string;sizeBytes:number;createdAt:string;fileEndpoint:string};
type HealthSummary={healthy:number;attention:number;critical:number;open:number};
const resultOptions=[["PASS","Good"],["ATTENTION_REQUIRED","Needs attention"],["FAIL","Faulty"],["NOT_APPLICABLE","N/A"]] as const;
const loadOptions=[["EMPTY","Empty"],["PART_LOADED","Part loaded"],["LOADED","Loaded"],["OVERLOAD_SUSPECTED","Possible overload"]] as const;
const healthLabel=(value?:string)=>value??"UNKNOWN";

export function InspectionsPage(){
 const{me}=useAuth();const[params]=useSearchParams();const presetTripId=params.get("tripId"),presetType=params.get("type");const isDriver=me?.roles.includes("DRIVER")??false;const canManage=me?.permissions.includes("alert.manage")??false;const canOpenWork=me?.permissions.includes("maintenance.open")??false;
 const[templates,setTemplates]=useState<Template[]>([]),[trips,setTrips]=useState<Trip[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[history,setHistory]=useState<Inspection[]>([]),[summary,setSummary]=useState<HealthSummary>({healthy:0,attention:0,critical:0,open:0});
 const[templateId,setTemplateId]=useState(""),[tripId,setTripId]=useState(presetTripId??""),[vehicleId,setVehicleId]=useState(""),[answers,setAnswers]=useState<Record<string,string>>({}),[comments,setComments]=useState<Record<string,string>>({}),[odometer,setOdometer]=useState(0),[loadState,setLoadState]=useState("EMPTY"),[location,setLocation]=useState(""),[behavior,setBehavior]=useState(""),[repairRequest,setRepairRequest]=useState(""),[canContinue,setCanContinue]=useState(true),[notes,setNotes]=useState(""),[photos,setPhotos]=useState<File[]>([]);
 const[show,setShow]=useState(isDriver||Boolean(presetTripId)),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("ACTIVE"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Inspection|null>(null),[evidence,setEvidence]=useState<Record<string,string[]>>({}),[managerNote,setManagerNote]=useState("");
 const load=async()=>{try{const[templateResult,inspectionResult,tripResult,assignmentResult]=await Promise.all([api<{items:Template[]}>(`/inspections/templates${presetType?`?type=${presetType}`:""}`),api<{items:Inspection[];healthSummary:HealthSummary}>("/inspections"),api<{items:Trip[]}>("/trips"),api<{items:Assignment[]}>("/assignments")]);setTemplates(templateResult.items);setHistory(inspectionResult.items);setSummary(inspectionResult.healthSummary??{healthy:0,attention:0,critical:0,open:0});setTrips(tripResult.items);setAssignments(assignmentResult.items);if(!isDriver&&me?.permissions.includes("vehicle.view")){const vr=await api<{items:Vehicle[]}>("/vehicles?limit=100");setVehicles(vr.items);}const selectedTrip=presetTripId?tripResult.items.find(t=>t.id===presetTripId):undefined;const active=assignmentResult.items.find(a=>a.status==="ACTIVE");if(selectedTrip?.vehicle){setTripId(selectedTrip.id);setVehicleId(selectedTrip.vehicle.id);setOdometer(selectedTrip.vehicle.currentOdometerKm);}else if(isDriver&&active){setVehicleId(active.vehicle.id);setOdometer(active.vehicle.currentOdometerKm??0);}const preferred=templateResult.items.find(t=>isDriver&&t.type==="DAILY")??templateResult.items.find(t=>!presetType||t.type===presetType)??templateResult.items[0];if(preferred)setTemplateId(preferred.id);}catch(e){setError(e instanceof Error?e.message:"Unable to load vehicle health data.");}};
 useEffect(()=>{void load();},[]);
 const selectedTemplate=useMemo(()=>templates.find(t=>t.id===templateId),[templates,templateId]);
 const vehicleOptions=useMemo(()=>{const map=new Map<string,Vehicle>();for(const v of vehicles)map.set(v.id,v);for(const a of assignments)map.set(a.vehicle.id,{id:a.vehicle.id,registrationNumber:a.vehicle.registrationNumber,make:a.vehicle.make,model:a.vehicle.model,currentOdometerKm:a.vehicle.currentOdometerKm??0});for(const t of trips)if(t.vehicle)map.set(t.vehicle.id,{id:t.vehicle.id,registrationNumber:t.vehicle.registrationNumber,make:"",model:"",currentOdometerKm:t.vehicle.currentOdometerKm});return[...map.values()];},[vehicles,assignments,trips]);
 const completed=selectedTemplate?.items.filter(item=>Boolean(answers[item.id])).length??0;const completionPct=selectedTemplate?.items.length?Math.round(completed/selectedTemplate.items.length*100):0;
 const preview=useMemo(()=>{if(!selectedTemplate||completionPct<100)return "UNKNOWN";if(!canContinue||loadState==="OVERLOAD_SUSPECTED"||selectedTemplate.items.some(i=>i.isCritical&&answers[i.id]==="FAIL"))return "CRITICAL";if(Boolean(repairRequest.trim())||selectedTemplate.items.some(i=>["ATTENTION_REQUIRED","FAIL"].includes(answers[i.id]??"")))return "ATTENTION";return "HEALTHY";},[selectedTemplate,completionPct,canContinue,loadState,answers,repairRequest]);
 const visible=useMemo(()=>history.filter(i=>{const q=query.trim().toLowerCase();const matches=!q||[i.vehicle.registrationNumber,i.vehicle.make,i.vehicle.model,i.driver?.fullName??"",i.trip?.tripNumber??"",i.type,i.healthState??""].some(x=>x.toLowerCase().includes(q));const state=i.managerStatus??"RESOLVED";return matches&&(filter==="ALL"?true:filter==="ACTIVE"?state!=="RESOLVED":healthLabel(i.healthState)===filter);}),[history,query,filter]);
 const selectTrip=(next:string)=>{setTripId(next);const t=trips.find(i=>i.id===next);if(t?.vehicle){setVehicleId(t.vehicle.id);setOdometer(t.vehicle.currentOdometerKm);}};
 const choosePhotos=(files:FileList|null)=>{const next=[...(files?Array.from(files):[])].slice(0,6);const tooLarge=next.find(file=>file.size>6*1024*1024);if(tooLarge){setError(`${tooLarge.name} is larger than 6 MB.`);return;}setError("");setPhotos(next);};
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selectedTemplate)return;const missing=selectedTemplate.items.find(i=>!answers[i.id]);if(missing){setError(`Complete ${missing.label}.`);return;}if((preview==="ATTENTION"||preview==="CRITICAL")&&!repairRequest.trim()){setError("Describe the repair or attention you believe is required.");return;}setBusy(true);setError("");setMessage("");try{const fd=new FormData();fd.set("payload",JSON.stringify({templateId:selectedTemplate.id,vehicleId,tripId:tripId||undefined,odometerKm:odometer,notes:notes||undefined,loadState,currentLocation:location||undefined,vehicleBehavior:behavior||undefined,repairRequest:repairRequest||undefined,driverCanContinue:canContinue,results:selectedTemplate.items.map(i=>({templateItemId:i.id,result:answers[i.id],comment:comments[i.id]||undefined}))}));for(const photo of photos)fd.append("photos",photo);const created=await api<{status:string;criticalFailure:boolean;healthState:string;managerStatus:string;evidenceCount:number}>("/inspections",{method:"POST",body:fd});setMessage(created.healthState==="CRITICAL"?"Critical vehicle defect submitted. Fleet Management has been alerted and the safety gate has been applied.":created.healthState==="ATTENTION"?"Repair attention submitted to Fleet Management.":"Vehicle health check submitted. Current condition is HEALTHY.");setAnswers({});setComments({});setBehavior("");setRepairRequest("");setNotes("");setPhotos([]);setCanContinue(true);if(!isDriver)setShow(false);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to submit vehicle health check.");}finally{setBusy(false);}};
 const loadEvidence=async(row:Inspection)=>{setSelected(row);setManagerNote(row.managerNote??"");if(evidence[row.id]||!(row.evidenceCount??0))return;try{const data=await api<{items:Evidence[]}>(`/inspections/${row.id}/evidence`);const urls:string[]=[];for(const item of data.items){const path=item.fileEndpoint.startsWith("/api")?item.fileEndpoint.slice(4):item.fileEndpoint;urls.push(URL.createObjectURL(await apiBlob(path)));}setEvidence(current=>({...current,[row.id]:urls}));}catch(e){setError(e instanceof Error?e.message:"Unable to load condition photos.");}};
 const act=async(row:Inspection,action:"ack-defect"|"resolve-defect"|"create-work-order")=>{setBusy(true);setError("");try{const body=action==="resolve-defect"?JSON.stringify({managerNote}):JSON.stringify({});await api(`/inspections/${row.id}/${action}`,{method:"POST",body});setMessage(action==="ack-defect"?"Fleet Management acknowledged the driver report.":action==="create-work-order"?"Workshop work order created from the driver findings.":"Defect follow-up resolved. Vehicle health has been recalculated.");setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update vehicle health follow-up.");}finally{setBusy(false);}};
 return <>
  <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">DRIVER CONDITION INTELLIGENCE · SAFETY & REPAIR FEEDBACK</span><h2>Vehicle Health Checks</h2><p>Drivers capture what the vehicle is doing in the real world: checklist condition, mileage, load state, behaviour, repair needs and photo evidence. Fleet Management receives accountable follow-up while healthy trucks stay visibly healthy.</p></div><button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"inspection"} size={16}/>{show?"Close health check":"New health check"}</button></section>
  {error&&<div className="error-box">{error}</div>}{message&&<div className="success-box">{message}</div>}
  <div className="health-kpis-v10"><div className="healthy"><span>Healthy reports</span><b>{summary.healthy}</b><small>Driver-confirmed good condition</small></div><div className="attention"><span>Repair attention</span><b>{summary.attention}</b><small>Open non-critical defects</small></div><div className="critical"><span>Critical alerts</span><b>{summary.critical}</b><small>Unsafe / urgent conditions</small></div><div><span>Open follow-up</span><b>{summary.open}</b><small>Needs management closure</small></div></div>
  {show&&<form className="health-form-v10" onSubmit={submit}>
   <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">1 · VEHICLE CONTEXT</span><h3>What truck are you reporting on?</h3><p>The system keeps the report tied to the assigned vehicle and current mileage.</p></div><span className={`health-preview-v10 ${preview.toLowerCase()}`}><i/>{preview}</span></div><div className="panel-body-v2 health-context-v10"><label>Health-check template<select value={templateId} onChange={e=>{setTemplateId(e.target.value);setAnswers({});setComments({});}} required><option value="">Select checklist</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Trip (optional)<select value={tripId} onChange={e=>selectTrip(e.target.value)}><option value="">Daily / non-trip check</option>{trips.filter(t=>Boolean(t.vehicle)).map(t=><option key={t.id} value={t.id}>{t.tripNumber} · {t.status}</option>)}</select></label><label>Vehicle<select value={vehicleId} onChange={e=>{setVehicleId(e.target.value);const v=vehicleOptions.find(x=>x.id===e.target.value);if(v)setOdometer(v.currentOdometerKm);}} disabled={isDriver||Boolean(tripId)} required><option value="">Select assigned vehicle</option>{vehicleOptions.map(v=><option value={v.id} key={v.id}>{v.registrationNumber} · {v.make} {v.model}</option>)}</select></label><label>Current odometer (km)<input type="number" min="0" value={odometer} onChange={e=>setOdometer(Number(e.target.value))} required/></label><label>Load condition<select value={loadState} onChange={e=>setLoadState(e.target.value)}>{loadOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Current location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Kampala yard / route / customer site"/></label></div></section>
   {selectedTemplate&&<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">2 · WALK-AROUND & BEHAVIOUR CHECK</span><h3>{selectedTemplate.name}</h3><p>{selectedTemplate.description}</p></div><div className="inspection-progress-badge">{completionPct}% complete</div></div><div className="panel-body-v2 health-checklist-v10">{selectedTemplate.items.map((item,index)=>{const value=answers[item.id]??"";return <article className={`health-item-v10 ${item.isCritical?"critical":""} ${value?value.toLowerCase():""}`} key={item.id}><div className="health-item-head-v10"><span>{index+1}</span><div><b>{item.label}</b>{item.description&&<small>{item.description}</small>}{item.isCritical&&<em><Icon name="alert" size={11}/> Safety-critical</em>}</div></div><div className="health-answer-v10">{resultOptions.map(([v,l])=><button type="button" key={v} className={value===v?"selected":""} onClick={()=>setAnswers(c=>({...c,[item.id]:v}))}>{l}</button>)}</div>{value&&value!=="PASS"&&value!=="NOT_APPLICABLE"&&<textarea value={comments[item.id]??""} onChange={e=>setComments(c=>({...c,[item.id]:e.target.value}))} placeholder="What did you notice? Noise, vibration, leak, damage, warning light, poor response…"/>}</article>})}</div></section>}
   <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">3 · DRIVER OBSERVATION</span><h3>Tell Fleet Management what the truck is actually doing</h3><p>Simple language is fine. The detail helps workshop staff diagnose the problem faster.</p></div></div><div className="panel-body-v2 health-observation-v10"><label className="wide">Vehicle behaviour<textarea value={behavior} onChange={e=>setBehavior(e.target.value)} placeholder="Example: pulls slightly left under braking; vibration starts above 70 km/h; power drops on hills; engine otherwise normal."/></label><label className="wide">Repair / attention required<textarea value={repairRequest} onChange={e=>setRepairRequest(e.target.value)} required={preview==="ATTENTION"||preview==="CRITICAL"} placeholder="What should be checked or repaired? If everything is good, leave this blank."/></label><label className="wide">Additional note<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Any other information Fleet Management should know."/></label><div className={`continue-choice-v10 ${canContinue?"yes":"no"}`}><div><b>Is the vehicle safe to continue?</b><span>Your answer is a safety declaration, not a repair approval.</span></div><div><button type="button" className={canContinue?"active":""} onClick={()=>setCanContinue(true)}>Yes, safe to continue</button><button type="button" className={!canContinue?"active":""} onClick={()=>setCanContinue(false)}>No — stop and attend</button></div></div></div></section>
   <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">4 · PHOTO EVIDENCE</span><h3>Show the condition, not just describe it</h3><p>Take up to six private photos. They are available only to authorized ACRILAND users.</p></div><span className="photo-count-v10">{photos.length}/6</span></div><div className="panel-body-v2 health-photo-v10"><label className="camera-button-v10"><Icon name="camera" size={22}/><b>Take / choose photos</b><span>JPEG, PNG or WebP · max 6 MB each</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple onChange={e=>choosePhotos(e.target.files)}/></label><div className="photo-file-list-v10">{photos.map((file,index)=><div key={`${file.name}-${index}`}><span>{index+1}</span><div><b>{file.name}</b><small>{(file.size/1024/1024).toFixed(1)} MB</small></div><button type="button" onClick={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}><Icon name="close" size={13}/></button></div>)}</div></div></section>
   <div className={`health-submit-v10 ${preview.toLowerCase()}`}><div><span>Calculated condition</span><b>{preview}</b><small>{preview==="CRITICAL"?"Submission will create a critical red operational alert and may ground the vehicle.":preview==="ATTENTION"?"Fleet Management will receive a repair-attention alert.":preview==="HEALTHY"?"Vehicle will be recorded as healthy unless another unresolved defect is still open.":"Complete the checklist to calculate health."}</small></div><button className="button-v2 primary" disabled={busy||completionPct<100||!vehicleId}>{busy?"Submitting…":"Submit vehicle health check"}</button></div>
  </form>}
  <section className="panel-v2"><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vehicle, driver, trip or health"/></div><div className="filter-tabs-v2">{["ACTIVE","CRITICAL","ATTENTION","HEALTHY","ALL"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Submitted</th><th>Vehicle</th><th>Driver / context</th><th>Mileage / load</th><th>Health</th><th>Follow-up</th><th>Evidence</th><th/></tr></thead><tbody>{visible.length?visible.map(row=><tr key={row.id}><td>{new Date(row.completedAt??row.createdAt).toLocaleString()}</td><td><b>{row.vehicle.registrationNumber}</b><span className="cell-sub-v2">{row.vehicle.make} {row.vehicle.model}</span></td><td>{row.driver?.fullName??"—"}<span className="cell-sub-v2">{row.type.replaceAll("_"," ")}{row.trip?` · ${row.trip.tripNumber}`:""}</span></td><td><b>{row.odometerKm.toLocaleString()} km</b><span className="cell-sub-v2">{row.loadState?.replaceAll("_"," ")??"Load not recorded"}</span></td><td><span className={`health-chip-v10 ${healthLabel(row.healthState).toLowerCase()}`}><i/>{healthLabel(row.healthState)}</span></td><td><span className={`follow-chip-v10 ${(row.managerStatus??"RESOLVED").toLowerCase()}`}>{(row.managerStatus??"RESOLVED").replaceAll("_"," ")}</span></td><td>{row.evidenceCount??0} photo{(row.evidenceCount??0)===1?"":"s"}</td><td><button className="table-detail-button" onClick={()=>void loadEvidence(row)}>View</button></td></tr>):<tr><td colSpan={8}><div className="empty-state-v2"><Icon name="check" size={24}/><b>No health checks match this view</b><span>Driver submissions will appear here automatically.</span></div></td></tr>}</tbody></table></div></section>
  {selected&&<div className="health-detail-backdrop-v10" onClick={()=>setSelected(null)}><aside className="health-detail-v10" onClick={e=>e.stopPropagation()}><div className="health-detail-head-v10"><div><span>DRIVER VEHICLE HEALTH REPORT</span><h3>{selected.vehicle.registrationNumber}</h3><p>{selected.driver?.fullName??"Authorized inspector"} · {new Date(selected.completedAt??selected.createdAt).toLocaleString()}</p></div><button onClick={()=>setSelected(null)}><Icon name="close"/></button></div><div className="health-detail-status-v10"><span className={`health-chip-v10 ${healthLabel(selected.healthState).toLowerCase()}`}><i/>{healthLabel(selected.healthState)}</span><span className={`follow-chip-v10 ${(selected.managerStatus??"RESOLVED").toLowerCase()}`}>{(selected.managerStatus??"RESOLVED").replaceAll("_"," ")}</span></div><div className="health-detail-facts-v10"><div><span>Odometer</span><b>{selected.odometerKm.toLocaleString()} km</b></div><div><span>Load</span><b>{selected.loadState?.replaceAll("_"," ")??"—"}</b></div><div><span>Safe to continue</span><b>{selected.driverCanContinue===false?"NO":"YES"}</b></div><div><span>Location</span><b>{selected.currentLocation??"—"}</b></div></div>{selected.vehicleBehavior&&<div className="health-copy-v10"><span>Vehicle behaviour</span><p>{selected.vehicleBehavior}</p></div>}{selected.repairRequest&&<div className="health-copy-v10 repair"><span>Driver repair request</span><p>{selected.repairRequest}</p></div>}<div className="health-findings-v10">{selected.results.filter(r=>r.result!=="PASS"&&r.result!=="NOT_APPLICABLE").map((r,index)=><div key={index} className={r.result==="FAIL"?"fail":"attention"}><b>{r.labelSnapshot}</b><span>{r.result.replaceAll("_"," ")}</span>{r.comment&&<p>{r.comment}</p>}</div>)}</div>{(selected.evidenceCount??0)>0&&<div className="health-evidence-v10">{evidence[selected.id]?.map((url,index)=><img src={url} alt={`Condition evidence ${index+1}`} key={url}/> )??<span>Loading private photos…</span>}</div>}{canManage&&selected.healthState!=="HEALTHY"&&selected.managerStatus!=="RESOLVED"&&<div className="health-manager-v10"><span>MANAGEMENT FOLLOW-UP</span><textarea value={managerNote} onChange={e=>setManagerNote(e.target.value)} placeholder="Resolution / verification note"/><div>{selected.managerStatus==="OPEN"&&<button className="button-v2 secondary" disabled={busy} onClick={()=>void act(selected,"ack-defect")}>Acknowledge</button>}{canOpenWork&&!selected.workOrderId&&<button className="button-v2 secondary" disabled={busy} onClick={()=>void act(selected,"create-work-order")}><Icon name="wrench" size={14}/> Create work order</button>}<button className="button-v2 primary" disabled={busy||managerNote.trim().length<3} onClick={()=>void act(selected,"resolve-defect")}>Resolve follow-up</button></div></div>}{selected.workOrderId&&<Link className="button-v2 secondary full-v10" to="/maintenance">Open linked workshop queue</Link>}</aside></div>}
 </>;
}
