import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type TemplateItem={id:string;code:string;label:string;description?:string|null;isCritical:boolean;sortOrder:number};
type Template={id:string;name:string;type:string;description?:string|null;items:TemplateItem[]};
type Trip={id:string;tripNumber:string;status:string;vehicle?:{id:string;registrationNumber:string;currentOdometerKm:number}|null;driver?:{fullName:string}|null};
type Assignment={id:string;status:string;vehicle:{id:string;registrationNumber:string;currentOdometerKm?:number;make:string;model:string}};
type Vehicle={id:string;registrationNumber:string;currentOdometerKm:number;make:string;model:string};
type Inspection={id:string;type:string;status:string;odometerKm:number;completedAt?:string|null;createdAt:string;vehicle:{registrationNumber:string;make:string;model:string};driver?:{fullName:string}|null;trip?:{tripNumber:string}|null;results:{result:string;isCritical:boolean}[]};

const historyFilters=[["ALL","All inspections"],["FAILED","Failed"],["COMPLETED_WITH_ATTENTION","Attention"],["PASSED","Passed"]] as const;
const inspectionResultOptions=[["PASS","Pass"],["ATTENTION_REQUIRED","Attention"],["FAIL","Fail"],["NOT_APPLICABLE","N/A"]] as const;

export function InspectionsPage(){
  const{me}=useAuth();const[params]=useSearchParams();const presetTripId=params.get("tripId"),presetType=params.get("type");
  const[templates,setTemplates]=useState<Template[]>([]),[trips,setTrips]=useState<Trip[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[history,setHistory]=useState<Inspection[]>([]);
  const[templateId,setTemplateId]=useState(""),[tripId,setTripId]=useState(presetTripId??""),[vehicleId,setVehicleId]=useState(""),[answers,setAnswers]=useState<Record<string,string>>({}),[comments,setComments]=useState<Record<string,string>>({}),[odometer,setOdometer]=useState(0),[show,setShow]=useState(Boolean(presetTripId)),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[historyFilter,setHistoryFilter]=useState("ALL"),[query,setQuery]=useState("");
  const isDriver=me?.roles.includes("DRIVER")??false;
  const load=async()=>{try{const[templateResult,inspectionResult,tripResult,assignmentResult]=await Promise.all([api<{items:Template[]}>(`/inspections/templates${presetType?`?type=${presetType}`:""}`),api<{items:Inspection[]}>("/inspections"),api<{items:Trip[]}>("/trips"),api<{items:Assignment[]}>("/assignments")]);setTemplates(templateResult.items);setHistory(inspectionResult.items);setTrips(tripResult.items);setAssignments(assignmentResult.items);if(!isDriver&&me?.permissions.includes("vehicle.view")){const vehicleResult=await api<{items:Vehicle[]}>("/vehicles?limit=100");setVehicles(vehicleResult.items);}const selectedTrip=presetTripId?tripResult.items.find(t=>t.id===presetTripId):undefined;if(selectedTrip?.vehicle){setTripId(selectedTrip.id);setVehicleId(selectedTrip.vehicle.id);setOdometer(selectedTrip.vehicle.currentOdometerKm);}const preferred=templateResult.items.find(t=>!presetType||t.type===presetType)??templateResult.items[0];if(preferred)setTemplateId(preferred.id);}catch(e){setError(e instanceof Error?e.message:"Unable to load inspection data.");}};
  useEffect(()=>{void load();},[]);
  const selectedTemplate=useMemo(()=>templates.find(t=>t.id===templateId),[templates,templateId]);
  const vehicleOptions=useMemo(()=>{const map=new Map<string,Vehicle>();for(const v of vehicles)map.set(v.id,v);for(const a of assignments)map.set(a.vehicle.id,{id:a.vehicle.id,registrationNumber:a.vehicle.registrationNumber,make:a.vehicle.make,model:a.vehicle.model,currentOdometerKm:a.vehicle.currentOdometerKm??0});for(const t of trips)if(t.vehicle)map.set(t.vehicle.id,{id:t.vehicle.id,registrationNumber:t.vehicle.registrationNumber,make:"",model:"",currentOdometerKm:t.vehicle.currentOdometerKm});return[...map.values()];},[vehicles,assignments,trips]);
  const stats=useMemo(()=>({passed:history.filter(i=>i.status==="PASSED").length,attention:history.filter(i=>i.status==="COMPLETED_WITH_ATTENTION").length,failed:history.filter(i=>i.status==="FAILED").length,critical:history.filter(i=>i.results.some(r=>r.isCritical&&r.result==="FAIL")).length}),[history]);
  const visibleHistory=useMemo(()=>history.filter(i=>{const q=query.trim().toLowerCase();const matchesQ=!q||[i.vehicle.registrationNumber,i.vehicle.make,i.vehicle.model,i.driver?.fullName??"",i.trip?.tripNumber??"",i.type].some(v=>v.toLowerCase().includes(q));return matchesQ&&(historyFilter==="ALL"||i.status===historyFilter);}),[history,query,historyFilter]);
  const completedCount=selectedTemplate?.items.filter(item=>Boolean(answers[item.id])).length??0;const completionPct=selectedTemplate?.items.length?Math.round((completedCount/selectedTemplate.items.length)*100):0;
  const selectTrip=(next:string)=>{setTripId(next);const t=trips.find(i=>i.id===next);if(t?.vehicle){setVehicleId(t.vehicle.id);setOdometer(t.vehicle.currentOdometerKm);}};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selectedTemplate)return;setBusy(true);setError("");setMessage("");const missing=selectedTemplate.items.find(i=>!answers[i.id]);if(missing){setError(`Complete the inspection result for ${missing.label}.`);setBusy(false);return;}try{const created=await api<{status:string;criticalFailure:boolean}>("/inspections",{method:"POST",body:JSON.stringify({templateId:selectedTemplate.id,vehicleId,tripId:tripId||undefined,odometerKm:odometer,results:selectedTemplate.items.map(i=>({templateItemId:i.id,result:answers[i.id],comment:comments[i.id]||undefined}))})});setMessage(created.criticalFailure?"Critical failure recorded. The vehicle has been grounded automatically.":`Inspection completed: ${created.status.replaceAll("_"," ")}.`);setAnswers({});setComments({});setShow(false);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to complete inspection.");}finally{setBusy(false);}};

  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">DIGITAL ROADWORTHINESS · SAFETY GATE</span><h2>Vehicle Inspections</h2><p>Standardized mobile checks with critical-item enforcement, odometer integrity, trip linkage and permanent inspection history.</p></div><button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"inspection"} size={16}/>{show?"Close inspection":"Start inspection"}</button></section>
    {error&&<div className="error-box">{error}</div>}{message&&<div className="success-box">{message}</div>}
    <div className="mini-kpi-grid-v2 four-v2"><div className="good"><span>Passed</span><b>{stats.passed}</b><small>Completed roadworthy inspections</small></div><div className="warning"><span>Attention required</span><b>{stats.attention}</b><small>Corrective action recorded</small></div><div className="danger"><span>Failed</span><b>{stats.failed}</b><small>Failed safety inspections</small></div><div className={stats.critical?"danger":"good"}><span>Critical failures</span><b>{stats.critical}</b><small>Automatic grounding trigger</small></div></div>
    {show&&<form className="inspection-workspace-v2" onSubmit={submit}>
      <section className="panel-v2 inspection-config-v2"><div className="panel-head-v2"><div><span className="panel-kicker">INSPECTION CONTEXT</span><h3>Vehicle & template</h3><p>Choose the authorized context before completing roadworthiness items.</p></div><span className="inspection-progress-badge">{completionPct}% complete</span></div><div className="panel-body-v2 inspection-config-grid-v2"><label>Inspection template<select value={templateId} onChange={e=>{setTemplateId(e.target.value);setAnswers({});setComments({});}} required><option value="">Select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Trip (optional)<select value={tripId} onChange={e=>selectTrip(e.target.value)}><option value="">No linked trip</option>{trips.filter(t=>Boolean(t.vehicle)).map(t=><option key={t.id} value={t.id}>{t.tripNumber} · {t.status}</option>)}</select></label><label>Vehicle<select value={vehicleId} onChange={e=>{setVehicleId(e.target.value);const v=vehicleOptions.find(x=>x.id===e.target.value);if(v)setOdometer(v.currentOdometerKm);}} required disabled={Boolean(tripId)}><option value="">Select vehicle</option>{vehicleOptions.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} {v.make} {v.model}</option>)}</select></label><label>Odometer (km)<input type="number" min="0" value={odometer} onChange={e=>setOdometer(Number(e.target.value))} required/></label></div></section>
      {selectedTemplate&&<section className="panel-v2 inspection-checklist-v2"><div className="panel-head-v2"><div><span className="panel-kicker">{selectedTemplate.type.replaceAll("_"," ")}</span><h3>{selectedTemplate.name}</h3><p>{selectedTemplate.description||"Complete every checklist item before submission."}</p></div><div className="inspection-progress-track"><i style={{width:`${completionPct}%`}}/></div></div><div className="panel-body-v2 inspection-items-v2">{selectedTemplate.items.map((item,index)=>{const result=answers[item.id]??"";return <div className={`inspection-item-v2 ${item.isCritical?"critical":""} ${result?`result-${result}`:""}`} key={item.id}><div className="inspection-item-title"><span>{index+1}</span><div><b>{item.label}</b>{item.description&&<small>{item.description}</small>}{item.isCritical&&<em><Icon name="alert" size={11}/> CRITICAL SAFETY ITEM</em>}</div></div><div className="inspection-result-buttons-v2">{inspectionResultOptions.map(([value,label])=><button type="button" key={value} className={result===value?`selected r-${value}`:""} onClick={()=>setAnswers(c=>({...c,[item.id]:value}))}>{label}</button>)}</div><input className="inspection-comment-v2" placeholder="Observation / corrective note (optional)" value={comments[item.id]??""} onChange={e=>setComments(c=>({...c,[item.id]:e.target.value}))}/></div>})}</div><div className="inspection-submit-bar-v2"><div><b>{completedCount} of {selectedTemplate.items.length} items completed</b><span>{completionPct===100?"Ready to submit inspection":"Complete every item before submitting"}</span></div><button className="button-v2 primary" disabled={busy||completionPct<100}>{busy?"Submitting inspection…":"Complete inspection"}</button></div></section>}
    </form>}
    <div className="safety-automation-grid-v2"><div className="safety-rule-v2 danger"><span><Icon name="alert"/></span><div><b>Critical FAIL</b><p>Vehicle moves automatically to GROUNDED. Assignment and dispatch remain blocked until authorized release.</p></div></div><div className="safety-rule-v2 warning"><span><Icon name="wrench"/></span><div><b>Attention required</b><p>The issue remains visible in the permanent inspection trail for corrective follow-up.</p></div></div><div className="safety-rule-v2 success"><span><Icon name="check"/></span><div><b>Passing pre-trip</b><p>An allocated trip may advance to READY TO DEPART once the safety gate passes.</p></div></div></div>
    <section className="panel-v2"><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vehicle, driver, trip or inspection type"/></div><div className="filter-tabs-v2">{historyFilters.map(([value,label])=><button className={historyFilter===value?"active":""} key={value} onClick={()=>setHistoryFilter(value)}>{label}</button>)}</div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Completed</th><th>Vehicle</th><th>Inspection</th><th>Driver</th><th>Trip</th><th>Odometer</th><th>Outcome</th></tr></thead><tbody>{visibleHistory.length?visibleHistory.map(i=><tr key={i.id}><td>{new Date(i.completedAt??i.createdAt).toLocaleString()}</td><td><div className="vehicle-cell-v2"><span className="vehicle-symbol-v2"><Icon name="vehicle" size={16}/></span><div><b>{i.vehicle.registrationNumber}</b><span>{i.vehicle.make} {i.vehicle.model}</span></div></div></td><td><b>{i.type.replaceAll("_"," ")}</b><span className="cell-sub-v2">{i.results.length} checklist result{i.results.length===1?"":"s"}</span></td><td>{i.driver?.fullName??"—"}</td><td>{i.trip?<Link to="/trips">{i.trip.tripNumber}</Link>:"—"}</td><td><b>{i.odometerKm.toLocaleString()} km</b></td><td><span className={`status-pill-v2 inspection-${i.status}`}><i/>{i.status.replaceAll("_"," ")}</span></td></tr>):<tr><td colSpan={7}><div className="empty-state-v2"><Icon name="inspection" size={24}/><b>No inspections match this view</b><span>Change the result filter or search term.</span></div></td></tr>}</tbody></table></div></section>
  </>;
}
