import { useEffect,useMemo,useState } from "react";
import { api,apiBlob } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type VehicleEconomics={vehicleId:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string;distanceKm:number;fuelLitres:number;fuelCost:number;maintenanceCost:number;operatingCost:number;costPerKm:number|null;litresPer100Km:number|null;downtimeHours:number};
type Report={organization:{name:string;currency:string};period:{days:number;since:string;until:string};kpis:{fleetTotal:number;available:number;activeTrips:number;workshop:number;grounded:number;totalDistance:number;fuelLitres:number;fuelSpend:number;maintenanceSpend:number;operatingSpend:number;downtimeHours:number;complianceDue30:number;driverLicencesDue30:number;costPerKm:number|null};vehicleEconomics:VehicleEconomics[]};
const periods=[[30,"30 days"],[90,"90 days"],[365,"12 months"]] as const;

export function ReportsPage(){
  const{me}=useAuth();const[days,setDays]=useState(90),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[exporting,setExporting]=useState(false);const canExport=me?.permissions.includes("report.export")??false;
  const load=async(next=days)=>{setLoading(true);setError("");try{setReport(await api<Report>(`/reports/overview?days=${next}`));}catch(e){setError(e instanceof Error?e.message:"Unable to load fleet report.");}finally{setLoading(false);}};
  useEffect(()=>{void load(days);},[days]);
  const money=(value:number)=>`${report?.organization.currency??"UGX"} ${value.toLocaleString(undefined,{maximumFractionDigits:0})}`;
  const maxCost=useMemo(()=>Math.max(...(report?.vehicleEconomics.map(v=>v.operatingCost)??[1]),1),[report]);
  const exportCsv=async()=>{setExporting(true);setError("");try{const blob=await apiBlob(`/reports/export.csv?days=${days}`);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`acriland-fleet-report-${days}d.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to export report.");}finally{setExporting(false);}};
  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">MANAGEMENT INFORMATION · COST · UTILIZATION · RISK</span><h2>Fleet Reports & Analytics</h2><p>Convert trip distance, issued fuel, workshop cost, downtime and compliance exposure into management-level vehicle economics.</p></div><div className="hero-actions-v3"><div className="period-switch-v3">{periods.map(([value,label])=><button key={value} className={days===value?"active":""} onClick={()=>setDays(value)}>{label}</button>)}</div>{canExport&&<button className="button-v2 primary" onClick={()=>void exportCsv()} disabled={exporting}><Icon name="arrow" size={16}/>{exporting?"Exporting…":"Export CSV"}</button>}</div></section>
    {error&&<div className="error-box">{error}</div>}
    {loading&&!report?<div className="panel-v2"><div className="empty-state-v2"><span className="loading-ring small"/><b>Building management report…</b></div></div>:report&&<>
      <div className="report-kpi-grid-v3"><div><span>Operating spend</span><b>{money(report.kpis.operatingSpend)}</b><small>Fuel + closed maintenance</small></div><div><span>Distance covered</span><b>{report.kpis.totalDistance.toLocaleString()} km</b><small>Trips returned in period</small></div><div><span>Fleet cost / km</span><b>{report.kpis.costPerKm==null?"—":money(report.kpis.costPerKm)}</b><small>Operating spend ÷ distance</small></div><div><span>Fuel issued</span><b>{report.kpis.fuelLitres.toLocaleString(undefined,{maximumFractionDigits:1})} L</b><small>{money(report.kpis.fuelSpend)} spend</small></div><div><span>Workshop spend</span><b>{money(report.kpis.maintenanceSpend)}</b><small>{report.kpis.downtimeHours.toLocaleString()} downtime hours</small></div><div className={report.kpis.complianceDue30+report.kpis.driverLicencesDue30?"risk":""}><span>30-day compliance exposure</span><b>{report.kpis.complianceDue30+report.kpis.driverLicencesDue30}</b><small>{report.kpis.complianceDue30} vehicle docs · {report.kpis.driverLicencesDue30} licences</small></div></div>
      <div className="report-split-v3"><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">OPERATING PICTURE</span><h3>Fleet state & deployment</h3><p>{new Date(report.period.since).toLocaleDateString()} – {new Date(report.period.until).toLocaleDateString()}</p></div></div><div className="panel-body-v2 fleet-state-report-v3"><div><span>Fleet total</span><b>{report.kpis.fleetTotal}</b></div><div className="good"><span>Operational / accountable</span><b>{report.kpis.available}</b></div><div className="info"><span>Active trips</span><b>{report.kpis.activeTrips}</b></div><div className="warning"><span>Workshop exposure</span><b>{report.kpis.workshop}</b></div><div className="danger"><span>Grounded / out</span><b>{report.kpis.grounded}</b></div></div></section><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">COST MIX</span><h3>Fuel vs maintenance</h3><p>Period operating-cost composition.</p></div></div><div className="panel-body-v2 cost-mix-v3"><div><span>Fuel</span><b>{money(report.kpis.fuelSpend)}</b><i style={{width:`${report.kpis.operatingSpend?report.kpis.fuelSpend/report.kpis.operatingSpend*100:0}%`}}/></div><div><span>Maintenance</span><b>{money(report.kpis.maintenanceSpend)}</b><i style={{width:`${report.kpis.operatingSpend?report.kpis.maintenanceSpend/report.kpis.operatingSpend*100:0}%`}}/></div></div></section></div>
      <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">VEHICLE ECONOMICS</span><h3>Cost, consumption & downtime by asset</h3><p>Ranked by operating cost for the selected reporting period.</p></div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Vehicle</th><th>Status</th><th>Distance</th><th>Fuel</th><th>Fuel spend</th><th>Maintenance</th><th>Operating cost</th><th>Cost / km</th><th>L / 100 km</th><th>Downtime</th></tr></thead><tbody>{report.vehicleEconomics.length?report.vehicleEconomics.map(v=><tr key={v.vehicleId}><td><div className="vehicle-cell-v2"><span className="vehicle-symbol-v2"><Icon name="vehicle" size={16}/></span><div><b>{v.registrationNumber}</b><span>{v.make} {v.model}</span></div></div><div className="cost-bar-v3"><i style={{width:`${v.operatingCost/maxCost*100}%`}}/></div></td><td><span className={`status-pill-v2 s-${v.status}`}><i/>{v.status.replaceAll("_"," ")}</span></td><td>{v.distanceKm.toLocaleString()} km</td><td>{v.fuelLitres.toLocaleString(undefined,{maximumFractionDigits:1})} L</td><td>{money(v.fuelCost)}</td><td>{money(v.maintenanceCost)}</td><td><b>{money(v.operatingCost)}</b></td><td>{v.costPerKm==null?"—":money(v.costPerKm)}</td><td>{v.litresPer100Km==null?"—":`${v.litresPer100Km} L`}</td><td>{v.downtimeHours.toLocaleString()} h</td></tr>):<tr><td colSpan={10}><div className="empty-state-v2"><Icon name="audit"/><b>No period economics yet</b><span>Issued fuel, closed work orders and completed trips will populate this report.</span></div></td></tr>}</tbody></table></div></section>
      <div className="manager-control-note-v2"><Icon name="shield"/><div><b>Report integrity</b><span>These analytics are calculated from controlled operational records: completed trip odometers, issued fuel values, closed maintenance costs and actual downtime timestamps. They are not manually keyed dashboard totals.</span></div></div>
    </>}
  </>;
}
