import { useEffect,useState,type FormEvent } from "react";
import { api } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { Icon } from "../components/Icon";

type Payload={organization:{id:string;name:string;slug:string;currency:string;timezone:string;isActive:boolean;createdAt:string;updatedAt:string};security:{activeUsers:number;lockedUsers:number;activeSessions:number};structure:{branches:number;departments:number}};
export function SettingsPage(){const{me}=useAuth();const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false);const canManage=me?.permissions.includes("settings.manage")??false;const load=()=>api<Payload>("/workspace/settings").then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load organization settings."));useEffect(()=>{void load();},[]);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError("");setNotice("");try{await api("/workspace/settings",{method:"PATCH",body:JSON.stringify({name:f.get("name"),currency:String(f.get("currency")||"").toUpperCase(),timezone:f.get("timezone")})});await load();setEditing(false);setNotice("Organization settings updated and audit logged.");}catch(x){setError(x instanceof Error?x.message:"Unable to update settings.");}finally{setBusy(false);}};if(!data)return error?<div className="error-box">{error}</div>:<div className="loading-screen inline-loading">Loading organization controls…</div>;const o=data.organization;return <>
<section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">ORGANIZATION CONTROL · GOVERNANCE BASELINE</span><h2>{o.name}</h2><p>Review tenant identity, operating defaults, organization structure and current access-security posture.</p></div>{canManage&&<button className="button-v2 primary" onClick={()=>setEditing(v=>!v)}><Icon name={editing?"close":"shield"} size={15}/>{editing?"Cancel edit":"Edit settings"}</button>}</section>
{error&&<div className="error-box">{error}</div>}{notice&&<div className="success-box-v6">{notice}</div>}
<div className="mini-kpi-grid-v2 five-v2"><div><span>Active users</span><b>{data.security.activeUsers}</b><small>Enabled organization accounts</small></div><div className={data.security.lockedUsers?"warning":"good"}><span>Locked users</span><b>{data.security.lockedUsers}</b><small>Authentication attention</small></div><div className="info"><span>Active sessions</span><b>{data.security.activeSessions}</b><small>Unrevoked, unexpired sessions</small></div><div><span>Branches</span><b>{data.structure.branches}</b><small>Active operating locations</small></div><div><span>Departments</span><b>{data.structure.departments}</b><small>Active cost/accountability units</small></div></div>
{editing&&canManage&&<form className="panel-v2 create-panel-v2" onSubmit={submit}><div className="panel-head-v2"><div><span className="panel-kicker">AUDITED CONFIGURATION</span><h3>Organization operating defaults</h3><p>Slug and tenant identity are intentionally immutable from this screen. Changes below are audit logged.</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Organization name<input name="name" defaultValue={o.name} required/></label><label>Currency (ISO 4217)<input name="currency" defaultValue={o.currency} maxLength={3} minLength={3} required/></label><label className="span-2">Timezone<input name="timezone" defaultValue={o.timezone} required placeholder="Africa/Kampala"/></label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy?"Saving…":"Save audited settings"}</button></div></div></form>}
<div className="settings-grid-v6"><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">TENANT IDENTITY</span><h3>Organization profile</h3></div></div><div className="detail-grid-v2 panel-body-v2"><div><span>Name</span><b>{o.name}</b></div><div><span>Tenant slug</span><b>{o.slug}</b></div><div><span>Currency</span><b>{o.currency}</b></div><div><span>Timezone</span><b>{o.timezone}</b></div><div><span>Status</span><b>{o.isActive?"ACTIVE":"INACTIVE"}</b></div><div><span>Created</span><b>{new Date(o.createdAt).toLocaleDateString()}</b></div></div></section><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">SECURITY POSTURE</span><h3>Access controls</h3></div></div><div className="panel-body-v2 security-checks-v6"><div><Icon name="shield"/><span><b>Role-based authorization</b><small>Every operational workspace is permission gated server-side.</small></span><strong>ENFORCED</strong></div><div><Icon name="profile"/><span><b>Driver account provisioning</b><small>No public self-registration; authorized management creates driver access.</small></span><strong>CONTROLLED</strong></div><div><Icon name="audit"/><span><b>Audit trail</b><small>Settings, approvals, status changes and sensitive operations retain actor context.</small></span><strong>ACTIVE</strong></div><div><Icon name="logout"/><span><b>Session governance</b><small>{data.security.activeSessions} currently active sessions across the organization.</small></span><strong>TRACKED</strong></div></div></section></div>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">OPERATING STRUCTURE</span><h3>Hierarchy & accountability</h3><p>ACRILAND data remains organization scoped, then structured through branches and departments.</p></div></div><div className="organization-flow-v6"><div><span>1</span><b>{o.name}</b><small>Organization tenant</small></div><i>→</i><div><span>2</span><b>{data.structure.branches} branches</b><small>Operating locations</small></div><i>→</i><div><span>3</span><b>{data.structure.departments} departments</b><small>Cost and responsibility units</small></div><i>→</i><div><span>4</span><b>Fleet operations</b><small>Vehicles, drivers, trips and controls</small></div></div></section>
<div className="manager-control-note-v2"><Icon name="shield"/><div><b>Security architecture note</b><span>Current authentication includes password hashing, refresh sessions, first-login password change, lockout controls and login history. MFA remains a future security extension rather than being represented as already enabled.</span></div></div>
</>}
