import { useEffect,useMemo,useState,type FormEvent } from "react";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type Vehicle={id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string;currentOdometerKm:number;currentLocation?:string|null};
type Snapshot={id:string;vehicleId:string;provider:string;externalDeviceId?:string|null;latitude:string|number|null;longitude:string|number|null;speedKph?:string|number|null;ignitionOn?:boolean|null;odometerKm?:number|null;fuelPercent?:number|null;headingDegrees?:number|null;recordedAt:string|null;receivedAt:string|null;vehicle:Vehicle};

function ageLabel(recordedAt:string|null){if(!recordedAt)return "No GPS report";const minutes=Math.max(0,Math.round((Date.now()-new Date(recordedAt).getTime())/60000));if(minutes<1)return "Just now";if(minutes<60)return `${minutes} min ago`;const hours=Math.round(minutes/60);return `${hours} hr ago`;}
function mapsUrl(latitude:number,longitude:number){return `https://www.google.com/maps?q=${latitude},${longitude}`;}

export function TelemetryPage(){
 const{me}=useAuth();const[items,setItems]=useState<Snapshot[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[show,setShow]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[lastRefresh,setLastRefresh]=useState<Date|null>(null);const canIngest=me?.permissions.includes("telemetry.ingest")??false;
 const load=async()=>{try{const [t,v]=await Promise.all([api<{items:Snapshot[]}>("/telemetry/latest"),canIngest?api<{items:Vehicle[]}>("/vehicles?limit=200"):Promise.resolve({items:[]})]);setItems(t.items);setVehicles(v.items);setLastRefresh(new Date());}catch(e){setError(e instanceof Error?e.message:"Unable to load live fleet telemetry.");}};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer);},[canIngest]);
 const stats=useMemo(()=>({fleet:items.length,reporting:items.filter(i=>i.recordedAt).length,moving:items.filter(i=>Number(i.speedKph??0)>5).length,stale:items.filter(i=>i.recordedAt&&Date.now()-new Date(i.recordedAt).getTime()>15*60000).length}),[items]);
 const selected=items.find(i=>i.vehicleId===selectedId)??items.find(i=>i.recordedAt)??items[0]??null;
 const ingest=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await api("/telemetry/ingest",{method:"POST",body:JSON.stringify({vehicleId:f.get("vehicleId"),provider:f.get("provider"),externalDeviceId:f.get("externalDeviceId")||undefined,latitude:Number(f.get("latitude")),longitude:Number(f.get("longitude")),speedKph:f.get("speedKph")?Number(f.get("speedKph")):undefined,ignitionOn:f.get("ignitionOn")==="on",odometerKm:f.get("odometerKm")?Number(f.get("odometerKm")):undefined,fuelPercent:f.get("fuelPercent")?Number(f.get("fuelPercent")):undefined,headingDegrees:f.get("headingDegrees")?Number(f.get("headingDegrees")):undefined,recordedAt:new Date().toISOString()})});e.currentTarget.reset();setShow(false);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to ingest telemetry snapshot.");}finally{setBusy(false);}};
 return <><section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">FLEET CONTROL · LIVE POSITION & TELEMETRY</span><h2>Fleet Tracking</h2><p>See every active vehicle in one control view. GPS coordinates update the vehicle's current location; vehicles without a GPS report remain visible with their last manually recorded location.</p></div><div className="telemetry-header-actions-v11">{lastRefresh&&<span className="refresh-status-v11">Updated {lastRefresh.toLocaleTimeString()}</span>}<button className="button-v2 secondary" onClick={()=>void load()}><Icon name="route" size={15}/> Refresh</button>{canIngest&&<button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"route"} size={16}/>{show?"Close simulator":"GPS test input"}</button>}</div></section>{error&&<div className="error-box">{error}</div>}
 <div className="mini-kpi-grid-v2 four-v2"><div><span>Total fleet</span><b>{stats.fleet}</b><small>Active fleet register</small></div><div className="good"><span>GPS reporting</span><b>{stats.reporting}</b><small>Vehicles with a latest position</small></div><div className="info"><span>Moving now</span><b>{stats.moving}</b><small>Latest speed above 5 km/h</small></div><div className={stats.stale?"warning":"good"}><span>Stale GPS</span><b>{stats.stale}</b><small>No update for more than 15 minutes</small></div></div>
 {show&&<form className="panel-v2 create-panel-v2" onSubmit={ingest}><div className="panel-head-v2"><div><span className="panel-kicker">GPS INTEGRATION TEST</span><h3>Record a live vehicle position</h3><p>Use this only for testing until your GPS provider sends telemetry automatically to the authenticated ingestion endpoint.</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Vehicle<select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registrationNumber} · {v.make} {v.model}</option>)}</select></label><label>Provider<input name="provider" required placeholder="e.g. FLEET-GPS"/></label><label>Device ID<input name="externalDeviceId"/></label><label>Latitude<input name="latitude" type="number" step="0.0000001" min="-90" max="90" required/></label><label>Longitude<input name="longitude" type="number" step="0.0000001" min="-180" max="180" required/></label><label>Speed km/h<input name="speedKph" type="number" min="0" step="0.1"/></label><label>Odometer km<input name="odometerKm" type="number" min="0"/></label><label>Fuel %<input name="fuelPercent" type="number" min="0" max="100"/></label><label>Heading °<input name="headingDegrees" type="number" min="0" max="359"/></label><label className="checkbox-field-v2"><input name="ignitionOn" type="checkbox"/> Ignition on</label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy?"Recording…":"Record position"}</button></div></div></form>}
 <section className="tracking-console-v11"><div className="tracking-map-panel-v11 panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">LIVE MAP</span><h3>{selected?.vehicle.registrationNumber??"Fleet map"}</h3><p>{selected?.recordedAt?`GPS position · ${ageLabel(selected.recordedAt)}`:"Select a reporting vehicle to view its map position."}</p></div></div>{selected&&selected.latitude!=null&&selected.longitude!=null?<><iframe title={`Map for ${selected.vehicle.registrationNumber}`} className="fleet-map-v11" src={`https://www.openstreetmap.org/export/embed.html?bbox=${Number(selected.longitude)-0.035}%2C${Number(selected.latitude)-0.025}%2C${Number(selected.longitude)+0.035}%2C${Number(selected.latitude)+0.025}&layer=mapnik&marker=${Number(selected.latitude)}%2C${Number(selected.longitude)}`}/><div className="map-footer-v11"><div><b>{Number(selected.latitude).toFixed(6)}, {Number(selected.longitude).toFixed(6)}</b><span>{selected.provider} · {ageLabel(selected.recordedAt)}</span></div><a className="button-v2 secondary" href={mapsUrl(Number(selected.latitude),Number(selected.longitude))} target="_blank" rel="noreferrer">Open in Maps</a></div></>:<div className="map-empty-v11"><Icon name="route" size={30}/><b>No GPS coordinates for this vehicle</b><span>{selected?.vehicle.currentLocation||"Add a GPS report or record the vehicle's current location in Vehicle Operations."}</span></div>}</div>
 <aside className="tracking-list-panel-v11 panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">ALL VEHICLES</span><h3>Where is each vehicle?</h3></div></div><div className="tracking-list-v11">{items.map(row=>{const hasGps=row.latitude!=null&&row.longitude!=null;const moving=Number(row.speedKph??0)>5;return <button className={`tracking-row-v11 ${selected?.vehicleId===row.vehicleId?"selected":""}`} key={row.vehicleId} onClick={()=>setSelectedId(row.vehicleId)}><span className={`tracking-dot-v11 ${hasGps?moving?"moving":"online":"offline"}`}><Icon name="vehicle" size={15}/></span><span className="tracking-main-v11"><b>{row.vehicle.registrationNumber}</b><small>{row.vehicle.make} {row.vehicle.model} · {row.vehicle.status.replaceAll("_"," ")}</small><em>{hasGps?`${Number(row.latitude).toFixed(4)}, ${Number(row.longitude).toFixed(4)}`:row.vehicle.currentLocation||"Location not recorded"}</em></span><span className="tracking-meta-v11"><strong>{hasGps?moving?`${Number(row.speedKph??0).toFixed(0)} km/h`:"PARKED":"NO GPS"}</strong><small>{ageLabel(row.recordedAt)}</small></span></button>})}{!items.length&&<div className="empty-state-v2"><Icon name="vehicle" size={24}/><b>No vehicles in the fleet register</b></div>}</div></aside></section>
 <section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">POSITION HISTORY · PROVIDER-NEUTRAL</span><h3>Latest telemetry</h3><p>Every received GPS snapshot is retained for vehicle history and operational control.</p></div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Vehicle</th><th>Location</th><th>Movement</th><th>Ignition</th><th>Odometer / fuel</th><th>Last report</th></tr></thead><tbody>{items.map(row=><tr key={row.vehicleId}><td><div className="vehicle-cell-v2"><span className="vehicle-symbol-v2"><Icon name="vehicle" size={16}/></span><div><b>{row.vehicle.registrationNumber}</b><span>{row.vehicle.make} {row.vehicle.model}</span></div></div></td><td>{row.latitude!=null&&row.longitude!=null?<><b>{Number(row.latitude).toFixed(5)}, {Number(row.longitude).toFixed(5)}</b><span className="cell-sub-v2">GPS · <a href={mapsUrl(Number(row.latitude),Number(row.longitude))} target="_blank" rel="noreferrer">Map</a></span></>:<><b>{row.vehicle.currentLocation||"Not recorded"}</b><span className="cell-sub-v2">Manual / no GPS</span></>}</td><td>{row.recordedAt?<b>{Number(row.speedKph??0).toFixed(1)} km/h</b>:"—"}</td><td>{row.recordedAt?<span className={`status-pill-v2 ${row.ignitionOn?"telemetry-on":"telemetry-off"}`}><i/>{row.ignitionOn?"ON":"OFF / unknown"}</span>:"—"}</td><td><b>{row.odometerKm!=null?`${row.odometerKm.toLocaleString()} km`:row.vehicle.currentOdometerKm.toLocaleString()+" km"}</b><span className="cell-sub-v2">Fuel {row.fuelPercent!=null?`${row.fuelPercent}%`:"—"}</span></td><td>{ageLabel(row.recordedAt)}</td></tr>)}{!items.length&&<tr><td colSpan={6}><div className="empty-state-v2"><Icon name="route" size={24}/><b>No fleet vehicles found</b></div></td></tr>}</tbody></table></div></section>
 </>;
}
