import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { Icon } from "../components/Icon";

type Trip = { id:string; tripNumber:string; purpose:string; origin:string; destination:string; status:string; requestedDeparture:string; expectedReturn:string; actualDeparture?:string|null; actualReturn?:string|null; startingOdometerKm?:number|null; endingOdometerKm?:number|null; distanceKm?:number|null; requester:{fullName:string}; vehicle?:{id:string;registrationNumber:string;make:string;model:string;status:string;currentOdometerKm:number}|null; driver?:{id:string;employeeNumber:string;fullName:string;status:string;licenceExpiry:string}|null };
type Vehicle = { id:string; registrationNumber:string; make:string; model:string; status:string };
type Driver = { id:string; employeeNumber:string; fullName:string; status:string; licenceExpiry:string };
type Action = { kind:"allocate"|"start"|"return"; trip:Trip } | null;

const lifecycle = ["REQUESTED", "APPROVED", "ALLOCATED", "PRE_TRIP_INSPECTION", "READY_TO_DEPART", "ACTIVE", "RETURNED", "POST_TRIP_INSPECTION", "CLOSED"];

export function TripsPage() {
  const { me } = useAuth();
  const [items, setItems] = useState<Trip[]>([]);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [showRequest, setShowRequest] = useState(false);
  const [action, setAction] = useState<Action>(null);
  const [filter, setFilter] = useState("OPEN");
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const isDriver = me?.roles.includes("DRIVER") ?? false;

  const load = async () => { try { const result = await api<{items:Trip[]}>("/trips"); setItems(result.items); if (me?.permissions.includes("trip.allocate")) { const [vehicleResult, driverResult] = await Promise.all([api<{items:Vehicle[]}>("/vehicles?limit=100"), api<{items:Driver[]}>("/drivers?limit=100")]); setVehicles(vehicleResult.items); setDrivers(driverResult.items); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to load trips."); } };
  useEffect(() => { void load(); }, []);

  const counts = useMemo(() => ({
    approval: items.filter((t) => ["REQUESTED", "APPROVED"].includes(t.status)).length,
    pretrip: items.filter((t) => ["ALLOCATED", "PRE_TRIP_INSPECTION", "READY_TO_DEPART"].includes(t.status)).length,
    active: items.filter((t) => t.status === "ACTIVE").length,
    returnFlow: items.filter((t) => ["RETURNED", "POST_TRIP_INSPECTION"].includes(t.status)).length
  }), [items]);

  const visible = useMemo(() => items.filter((trip) => {
    const q = query.trim().toLowerCase(); const matchesQuery = !q || [trip.tripNumber, trip.purpose, trip.origin, trip.destination, trip.vehicle?.registrationNumber ?? "", trip.driver?.fullName ?? ""].some((value) => value.toLowerCase().includes(q));
    const matchesFilter = filter === "ALL" || (filter === "OPEN" ? !["CLOSED", "CANCELLED", "REJECTED"].includes(trip.status) : trip.status === filter);
    return matchesQuery && matchesFilter;
  }), [items, query, filter]);

  const requestTrip = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget; const f = new FormData(form); try { await api("/trips", { method:"POST", body:JSON.stringify({ purpose:f.get("purpose"), origin:f.get("origin"), destination:f.get("destination"), requestedDeparture:f.get("requestedDeparture"), expectedReturn:f.get("expectedReturn"), passengerCount:Number(f.get("passengerCount") || 0), cargoInfo:f.get("cargoInfo") || undefined }) }); form.reset(); setShowRequest(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to request trip."); } finally { setBusy(false); } };
  const decide = async (trip:Trip, decision:"APPROVED"|"REJECTED") => { const comments = decision === "REJECTED" ? window.prompt("Reason for rejecting this trip:") : "Approved by Fleet Management"; if (decision === "REJECTED" && !comments) return; try { await api(`/trips/${trip.id}/decision`, { method:"POST", body:JSON.stringify({ decision, comments }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to record trip decision."); } };
  const submitAction = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!action) return; setBusy(true); setError(""); const f = new FormData(event.currentTarget); try { if (action.kind === "allocate") await api(`/trips/${action.trip.id}/allocate`, { method:"POST", body:JSON.stringify({ vehicleId:f.get("vehicleId"), driverId:f.get("driverId") }) }); else if (action.kind === "start") await api(`/trips/${action.trip.id}/start`, { method:"POST", body:JSON.stringify({ startingOdometerKm:Number(f.get("odometer")), startingFuelPercent:f.get("fuel") ? Number(f.get("fuel")) : undefined }) }); else await api(`/trips/${action.trip.id}/return`, { method:"POST", body:JSON.stringify({ endingOdometerKm:Number(f.get("odometer")), endingFuelPercent:f.get("fuel") ? Number(f.get("fuel")) : undefined }) }); setAction(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete trip action."); } finally { setBusy(false); } };
  const closeTrip = async (trip:Trip) => { try { await api(`/trips/${trip.id}/close`, { method:"POST", body:JSON.stringify({}) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to close trip."); } };

  const actionsFor = (trip:Trip) => <div className="row-actions-v2">{trip.status === "REQUESTED" && me?.permissions.includes("trip.approve") && <><button className="mini-action-v2 success" onClick={() => void decide(trip, "APPROVED")}>Approve</button><button className="mini-action-v2 danger" onClick={() => void decide(trip, "REJECTED")}>Reject</button></>}{trip.status === "APPROVED" && me?.permissions.includes("trip.allocate") && <button className="mini-action-v2" onClick={() => setAction({ kind:"allocate", trip })}>Allocate</button>}{["ALLOCATED", "PRE_TRIP_INSPECTION"].includes(trip.status) && trip.vehicle && <Link className="mini-action-v2" to={`/inspections?tripId=${trip.id}&type=PRE_TRIP`}>Pre-trip</Link>}{trip.status === "READY_TO_DEPART" && me?.permissions.includes("trip.start") && <button className="mini-action-v2 success" onClick={() => setAction({ kind:"start", trip })}>Start</button>}{trip.status === "ACTIVE" && me?.permissions.includes("trip.complete") && <button className="mini-action-v2" onClick={() => setAction({ kind:"return", trip })}>Return</button>}{trip.status === "RETURNED" && trip.vehicle && <Link className="mini-action-v2" to={`/inspections?tripId=${trip.id}&type=POST_TRIP`}>Post-trip</Link>}{trip.status === "POST_TRIP_INSPECTION" && me?.permissions.includes("trip.close") && <button className="mini-action-v2 success" onClick={() => void closeTrip(trip)}>Close</button>}</div>;

  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">CONTROLLED MOVEMENT · APPROVAL CHAIN</span><h2>{isDriver ? "My Trips" : "Trip Control"}</h2><p>Request → independent approval → vehicle/driver allocation → pre-trip inspection → authorized movement → return → post-trip inspection → closure.</p></div>{me?.permissions.includes("trip.request") && <button className="button-v2 primary" onClick={() => setShowRequest((value) => !value)}><Icon name={showRequest ? "close" : "plus"} size={16} />{showRequest ? "Close request" : "Request trip"}</button>}</section>

    {error && <div className="error-box">{error}</div>}

    <div className="mini-kpi-grid-v2 four-v2"><div className="warning"><span>Approval queue</span><b>{counts.approval}</b><small>Requested or approved</small></div><div className="info"><span>Pre-departure control</span><b>{counts.pretrip}</b><small>Allocation and inspection</small></div><div className="good"><span>Active movement</span><b>{counts.active}</b><small>Trips currently underway</small></div><div><span>Return & closure</span><b>{counts.returnFlow}</b><small>Post-trip accountability</small></div></div>

    {showRequest && <form className="panel-v2 create-panel-v2" onSubmit={requestTrip}><div className="panel-head-v2"><div><span className="panel-kicker">MOVEMENT REQUEST</span><h3>Request authorized vehicle movement</h3><p>A request does not authorize departure. It must pass the independent fleet approval and allocation controls.</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Purpose<input name="purpose" required /></label><label>Origin<input name="origin" required /></label><label>Destination<input name="destination" required /></label><label>Passengers<input name="passengerCount" type="number" min="0" defaultValue="0" /></label><label>Requested departure<input name="requestedDeparture" type="datetime-local" required /></label><label>Expected return<input name="expectedReturn" type="datetime-local" required /></label><label className="span-2-v2">Cargo / load information<input name="cargoInfo" /></label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy ? "Submitting…" : "Submit for approval"}</button><button className="button-v2 secondary" type="button" onClick={() => setShowRequest(false)}>Cancel</button></div></div></form>}

    {action && <form className="panel-v2 action-panel-v2" onSubmit={submitAction}><div className="panel-head-v2"><div><span className="panel-kicker">{action.kind.toUpperCase()} · {action.trip.tripNumber}</span><h3>{action.trip.origin} → {action.trip.destination}</h3><p>{action.trip.purpose}</p></div><button className="icon-button-v2" type="button" onClick={() => setAction(null)}><Icon name="close" size={16} /></button></div><div className="panel-body-v2">{action.kind === "allocate" ? <div className="form-grid-v2 two-v2"><label>Vehicle<select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map((v) => <option key={v.id} value={v.id}>{v.registrationNumber} · {v.status}</option>)}</select></label><label>Driver<select name="driverId" required><option value="">Select driver</option>{drivers.map((d) => <option key={d.id} value={d.id}>{d.employeeNumber} · {d.fullName}</option>)}</select></label></div> : <div className="form-grid-v2 two-v2"><label>{action.kind === "start" ? "Starting" : "Ending"} odometer<input name="odometer" type="number" min="0" defaultValue={action.kind === "start" ? action.trip.vehicle?.currentOdometerKm : action.trip.startingOdometerKm ?? 0} required /></label><label>Fuel level %<input name="fuel" type="number" min="0" max="100" /></label></div>}<div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy ? "Saving…" : "Confirm control action"}</button><button className="button-v2 secondary" type="button" onClick={() => setAction(null)}>Cancel</button></div></div></form>}

    <div className="manager-control-note-v2"><Icon name="shield" /><div><b>No vehicle moves without accountability</b><span>Drivers cannot approve their own request. Departure remains blocked until allocation and a passing pre-trip inspection are recorded.</span></div></div>

    <section className="panel-v2"><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search trip, route, vehicle or driver" /></div><div className="filter-tabs-v2"><button className={filter === "OPEN" ? "active" : ""} onClick={() => setFilter("OPEN")}>Open lifecycle</button><button className={filter === "ACTIVE" ? "active" : ""} onClick={() => setFilter("ACTIVE")}>Active</button><button className={filter === "REQUESTED" ? "active" : ""} onClick={() => setFilter("REQUESTED")}>Awaiting approval</button><button className={filter === "ALL" ? "active" : ""} onClick={() => setFilter("ALL")}>All trips</button></div></div>
      <div className="table-wrap fleet-table-v2"><table><thead><tr><th>Trip</th><th>Route</th><th>Schedule</th><th>Vehicle / driver</th><th>Lifecycle</th><th>Distance</th><th>Control</th></tr></thead><tbody>{visible.length ? visible.map((trip) => <tr key={trip.id}><td><b>{trip.tripNumber}</b><span className="cell-sub-v2">{trip.purpose}</span></td><td><b>{trip.origin}</b><span className="cell-sub-v2">→ {trip.destination}</span></td><td>{new Date(trip.requestedDeparture).toLocaleString()}<span className="cell-sub-v2">Return {new Date(trip.expectedReturn).toLocaleString()}</span></td><td>{trip.vehicle && trip.driver ? <><b>{trip.vehicle.registrationNumber}</b><span className="cell-sub-v2">{trip.driver.fullName}</span></> : <span className="muted-v2">Awaiting allocation</span>}</td><td><div className="trip-lifecycle-cell"><span className={`status-pill-v2 trip-${trip.status}`}><i />{trip.status.replaceAll("_", " ")}</span><div className="lifecycle-track-v2"><i style={{ width:`${Math.max(5, ((Math.max(0, lifecycle.indexOf(trip.status)) + 1) / lifecycle.length) * 100)}%` }} /></div></div></td><td>{trip.distanceKm != null ? <b>{trip.distanceKm.toLocaleString()} km</b> : "—"}</td><td>{actionsFor(trip)}</td></tr>) : <tr><td colSpan={7}><div className="empty-state-v2"><Icon name="trip" size={24} /><b>No trips match this view</b><span>Change the lifecycle filter or search term.</span></div></td></tr>}</tbody></table></div>
    </section>
  </>;
}
