import { useEffect, useMemo, useState, type FormEvent } from "react";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type UserRow={id:string;fullName:string;email:string;status:string;mustChangePassword:boolean;lastLoginAt?:string|null;roles:{role:{name:string}}[]};
type Role={id:string;name:string;description?:string};
const userFilters=[["ALL","All users"],["ACTIVE","Active"],["PASSWORD","Password change"],["NEVER","Never signed in"]] as const;

export function UsersPage(){
  const{me}=useAuth();const[items,setItems]=useState<UserRow[]>([]),[roles,setRoles]=useState<Role[]>([]),[show,setShow]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL"),[busy,setBusy]=useState(false);
  const load=()=>Promise.all([api<{items:UserRow[]}>("/users"),api<Role[]>("/users/roles")]).then(([u,r])=>{setItems(u.items);setRoles(r.filter(x=>x.name!=="DRIVER"));}).catch(e=>setError(e instanceof Error?e.message:"Unable to load users."));
  useEffect(()=>{void load();},[]);
  const stats=useMemo(()=>({active:items.filter(u=>u.status==="ACTIVE").length,password:items.filter(u=>u.mustChangePassword).length,never:items.filter(u=>!u.lastLoginAt).length,admins:items.filter(u=>u.roles.some(r=>["SUPER_ADMIN","ADMIN"].includes(r.role.name))).length}),[items]);
  const visible=useMemo(()=>items.filter(u=>{const q=query.trim().toLowerCase();const matchesQ=!q||[u.fullName,u.email,...u.roles.map(r=>r.role.name)].some(v=>v.toLowerCase().includes(q));const matchesFilter=filter==="ALL"||filter==="ACTIVE"&&u.status==="ACTIVE"||filter==="PASSWORD"&&u.mustChangePassword||filter==="NEVER"&&!u.lastLoginAt;return matchesQ&&matchesFilter;}),[items,query,filter]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await api("/users",{method:"POST",body:JSON.stringify({fullName:f.get("fullName"),email:f.get("email"),temporaryPassword:f.get("temporaryPassword"),roleNames:[f.get("roleName")]})});e.currentTarget.reset();setShow(false);await load();}catch(x){setError(x instanceof Error?x.message:"Unable to create user");}finally{setBusy(false);}};
  return <>
    <section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">ADMINISTRATION · IDENTITY & ACCESS</span><h2>Users & Permissions</h2><p>Provision accountable staff access, assign organizational roles and monitor account readiness without exposing driver self-registration.</p></div>{me?.permissions.includes("user.create")&&<button className="button-v2 primary" onClick={()=>setShow(v=>!v)}><Icon name={show?"close":"plus"} size={16}/>{show?"Close form":"Add staff user"}</button>}</section>
    {error&&<div className="error-box">{error}</div>}
    <div className="mini-kpi-grid-v2 four-v2"><div className="good"><span>Active users</span><b>{stats.active}</b><small>Enabled staff accounts</small></div><div><span>Privileged admins</span><b>{stats.admins}</b><small>Admin-level role holders</small></div><div className={stats.password?"warning":"good"}><span>Password change required</span><b>{stats.password}</b><small>Temporary credential state</small></div><div className={stats.never?"info":"good"}><span>Never signed in</span><b>{stats.never}</b><small>Accounts awaiting first login</small></div></div>
    {show&&<form className="panel-v2 create-panel-v2" onSubmit={submit}><div className="panel-head-v2"><div><span className="panel-kicker">STAFF ACCOUNT PROVISIONING</span><h3>Create internal user</h3><p>General staff accounts are created here. Driver portal accounts remain intentionally restricted to Driver Management.</p></div></div><div className="panel-body-v2 form-grid-v2"><label>Full name<input name="fullName" required/></label><label>Email<input name="email" type="email" required/></label><label>Role<select name="roleName" required><option value="">Select role</option>{roles.map(r=><option value={r.name} key={r.id}>{r.name.replaceAll("_"," ")}</option>)}</select></label><label>Temporary password<input name="temporaryPassword" type="password" minLength={12} required autoComplete="new-password"/></label><div className="form-actions-v2"><button className="button-v2 primary" disabled={busy}>{busy?"Creating…":"Create user"}</button><button className="button-v2 secondary" type="button" onClick={()=>setShow(false)}>Cancel</button></div></div></form>}
    <div className="manager-control-note-v2"><Icon name="shield"/><div><b>Access separation is deliberate</b><span>Staff users are provisioned here by authorized administrators. Driver accounts do not appear in the role selector and can only be issued through Driver Management by users with the dedicated driver-account permission.</span></div></div>
    <section className="panel-v2"><div className="fleet-toolbar-v2"><div className="fleet-search-v2"><Icon name="search" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email or role"/></div><div className="filter-tabs-v2">{userFilters.map(([value,label])=><button className={filter===value?"active":""} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>User</th><th>Email</th><th>Roles</th><th>Account status</th><th>Password state</th><th>Last login</th><th>Security</th></tr></thead><tbody>{visible.length?visible.map(u=><tr key={u.id}><td><div className="identity-cell-v2"><span>{u.fullName.split(/\s+/).slice(0,2).map(p=>p[0]).join("").toUpperCase()}</span><div><b>{u.fullName}</b><small>{u.id.slice(0,8)}</small></div></div></td><td>{u.email}</td><td><div className="role-stack-v2">{u.roles.map(r=><span key={r.role.name}>{r.role.name.replaceAll("_"," ")}</span>)}</div></td><td><span className={`status-pill-v2 portal-${u.status}`}><i/>{u.status}</span></td><td>{u.mustChangePassword?<span className="password-state-v2 warning"><Icon name="alert" size={12}/>Change required</span>:<span className="password-state-v2 good"><Icon name="check" size={12}/>Current</span>}</td><td>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():<span className="muted-v2">Never</span>}</td><td><span className="audit-ready-v2"><Icon name="audit" size={13}/> Audited</span></td></tr>):<tr><td colSpan={7}><div className="empty-state-v2"><Icon name="users" size={24}/><b>No users match this view</b><span>Change the account filter or search term.</span></div></td></tr>}</tbody></table></div></section>
  </>;
}
