import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { Icon } from "../components/Icon";
import { useAuth } from "../auth/AuthContext";

type Vehicle={id:string;registrationNumber:string;fleetNumber?:string|null;make:string;model:string;status:string;currentLocation?:string|null;currentOdometerKm:number;healthState?:string};
const statuses=["AVAILABLE","RESERVED","ASSIGNED","ON_TRIP","PARKED","SERVICE_DUE","SERVICE_OVERDUE","UNDER_INSPECTION","UNDER_MAINTENANCE","BREAKDOWN","ACCIDENT","GROUNDED","OUT_OF_SERVICE","DISPOSED"];
const label=(v:string)=>v.replaceAll("_"," ");

export function VehicleLifecycleControlPage(){
 const {me}=useAuth(); const [items,setItems]=useState<Vehicle[]>([]); const [selected,setSelected]=useState<Vehicle|null>(null); const [filter,setFilter]=useState("ALL"); const [q,setQ]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const canEdit=me?.permissions.includes("vehicle.edit")??false;
 const load=async()=>{try{setError("");const r=await api<{items:Vehicle[]}>(`/vehicles?limit=100${q.trim()?`&q=${encodeURIComponent(q.trim())}`:""}`);setItems(r.items);if(selected)setSelected(r.items.find(v=>v.id===selected.id)??null);}catch(e){setError(e instanceof Error?e.message:"Unable to load vehicle lifecycle.");}};
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>filter==="ALL"?items:items.filter(v=>v.status===filter),[items,filter]);
 const changeStatus=async(status:string)=>{if(!selected||status===selected.status)return;const needsReason=["GROUNDED","OUT_OF_SERVICE","DISPOSED"].includes(status);const reason=window.prompt(needsReason?`Reason for ${label(status).toLowerCase()}:`:"Operational note (optional):","");if(reason===null||(needsReason&&!reason.trim()))return;setBusy(true);try{await api(`/vehicles/${selected.id}`,{method:"PATCH",body:JSON.stringify({status,reason:reason||undefined})});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to change vehicle status.");}finally{setBusy(false);}};
 const archive=async()=>{if(!selected||selected.status!=="DISPOSED")return;const reason=window.prompt("Why is this disposed vehicle being archived from the active register?","");if(!reason?.trim())return;setBusy(true);try{await api(`/vehicles/${selected.id}/archive`,{method:"POST",body:JSON.stringify({reason})});setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to archive vehicle.");}finally{setBusy(false);}};
 return <><section className="page-hero-v2 compact-hero-v2"><div><span className="eyebrow-v2">FLEET GOVERNANCE · ASSET LIFECYCLE</span><h2>Vehicle Lifecycle Control</h2><p>One controlled workspace for operational status, retirement and final archival. Historical records remain protected throughout the vehicle lifecycle.</p></div><Link className="button-v2 secondary" to="/vehicles"><Icon name="vehicle" size={16}/> Fleet register</Link></section>
 {error&&<div className="error-box">{error}</div>}
 <section className="panel-v2"><div className="fleet-toolbar-v2"><form className="fleet-search-v2" onSubmit={e=>{e.preventDefault();void load();}}><Icon name="search" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search registration, fleet number, make or model"/><button type="submit">Search</button></form><div className="filter-tabs-v2"><button className={filter==="ALL"?"active":""} onClick={()=>setFilter("ALL")}>All</button><button className={filter==="AVAILABLE"?"active":""} onClick={()=>setFilter("AVAILABLE")}>Available</button><button className={filter==="ON_TRIP"?"active":""} onClick={()=>setFilter("ON_TRIP")}>On trip</button><button className={filter==="UNDER_MAINTENANCE"?"active":""} onClick={()=>setFilter("UNDER_MAINTENANCE")}>Workshop</button><button className={filter==="DISPOSED"?"active":""} onClick={()=>setFilter("DISPOSED")}>Disposed</button></div></div>
 <div className={`fleet-register-layout-v2 ${selected?"with-detail":""}`}><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Vehicle</th><th>Location</th><th>Odometer</th><th>Operational status</th><th>Health</th><th/></tr></thead><tbody>{filtered.map(v=><tr key={v.id} className={selected?.id===v.id?"selected-row":""}><td><b>{v.registrationNumber}</b><span className="cell-sub-v2">{v.fleetNumber||"No fleet number"} · {v.make} {v.model}</span></td><td>{v.currentLocation||"Not recorded"}</td><td>{v.currentOdometerKm.toLocaleString()} km</td><td><span className={`status-pill-v2 s-${v.status}`}><i/>{label(v.status)}</span></td><td><span className={`health-chip-v10 ${(v.healthState??"UNKNOWN").toLowerCase()}`}><i/>{v.healthState??"UNKNOWN"}</span></td><td><button className="table-detail-button" onClick={()=>setSelected(v)}>Control</button></td></tr>)}{!filtered.length&&<tr><td colSpan={6}><div className="empty-state-v2"><Icon name="vehicle"/><b>No vehicles in this lifecycle view</b><span>Change the filter or search term.</span></div></td></tr>}</tbody></table></div>
 {selected&&<aside className="vehicle-detail-v2"><div className="detail-head-v2"><div className="detail-icon-v2"><Icon name="vehicle" size={22}/></div><div><span>ASSET CONTROL</span><h3>{selected.registrationNumber}</h3><p>{selected.make} {selected.model}</p></div><button onClick={()=>setSelected(null)} aria-label="Close"><Icon name="close" size={17}/></button></div><div className="detail-status-v2"><span className={`status-pill-v2 s-${selected.status}`}><i/>{label(selected.status)}</span><small>{selected.currentLocation||"Location not recorded"}</small></div><div className="detail-grid-v2"><div><span>Fleet number</span><b>{selected.fleetNumber||"—"}</b></div><div><span>Odometer</span><b>{selected.currentOdometerKm.toLocaleString()} km</b></div><div className="detail-wide"><span>Current location</span><b>{selected.currentLocation||"Not recorded"}</b></div></div>{canEdit&&<div className="panel-v2 lifecycle-action-card"><div className="panel-head-v2"><div><span className="panel-kicker">STATUS CONTROL</span><h3>Move asset through lifecycle</h3><p>Status changes are validated by the fleet rules. Critical retirement states require a reason.</p></div></div><div className="panel-body-v2 form-grid-v2"><label className="span-2-v2">Operational status<select value={selected.status} disabled={busy} onChange={e=>void changeStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>{selected.status==="DISPOSED"&&<div className="form-actions-v2"><button className="button-v2 secondary" disabled={busy} onClick={()=>void archive()}><Icon name="archive" size={15}/> Archive from active register</button></div>}</div></div>}<div className="detail-actions-v2"><Link className="button-v2 secondary" to={`/vehicles/${selected.id}`}>Open Vehicle 360</Link><Link className="button-v2 secondary" to="/lifecycle">Lifecycle & TCO</Link></div></aside>}</div></section></>;
}
