import { useEffect,useMemo,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { api } from "../api/client";
import { Icon } from "../components/Icon";

type Data={vehicle:{id:string;registrationNumber:string;fleetNumber?:string|null;vin:string;engineNumber?:string|null;make:string;model:string;category:string;manufacturingYear:number;fuelType:string;status:string;currentOdometerKm:number;initialOdometerKm:number;currentLocation?:string|null;purchasePrice?:string|number|null;branch?:{name:string}|null;department?:{name:string}|null};assignment?:{startAt:string;assignmentType:string;purpose?:string|null;driver:{id:string;fullName:string;employeeNumber:string;status:string;licenceExpiry:string}}|null;trips:Array<{id:string;tripNumber:string;purpose:string;origin:string;destination:string;status:string;requestedDeparture:string;distanceKm?:number|null;driver?:{id:string;fullName:string}|null}>;maintenance:Array<{id:string;workOrderNumber:string;title:string;category:string;priority:string;status:string;openedAt:string;totalCost?:string|number|null}>;fuel:Array<{id:string;requestNumber:string;status:string;issuedLitres?:string|number|null;totalCost?:string|number|null;station?:string|null;requestedAt:string;issuedAt?:string|null}>;compliance:Array<{id:string;type:string;referenceNumber:string;provider?:string|null;expiryDate:string}>;tyres:Array<{id:string;serialNumber:string;brand:string;size:string;position?:string|null;currentTreadDepthMm?:string|number|null}>;preventiveMaintenance:Array<{id:string;name:string;nextDueAt?:string|null;nextDueKm?:number|null}>;telemetry?:{provider:string;latitude:string|number;longitude:string|number;speedKph?:string|number|null;fuelPercent?:number|null;recordedAt:string}|null;incidents:Array<{id:string;incidentNumber:string;type:string;severity:string;status:string;occurredAt:string;location:string}>;dispatches:Array<{id:string;dispatchNumber:string;status:string;plannedDeparture:string;plannedReturn:string}>;disposal?:{status:string;reason:string;disposalMethod:string;requestedAt:string}|null;economics:{acquisition:number;fuelSpend:number;fuelLitres:number;maintenanceSpend:number;explicitCost:number;tco:number;costPerKm:number|null}};
const money=(v:number)=>`UGX ${v.toLocaleString(undefined,{maximumFractionDigits:0})}`;const date=(v?:string|null)=>v?new Date(v).toLocaleDateString():"—";

export function Vehicle360Page(){const{id}=useParams();const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{if(!id)return;setLoading(true);void api<Data>(`/workspace/vehicles/${id}`).then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load Vehicle 360.")).finally(()=>setLoading(false));},[id]);const metrics=useMemo(()=>data?{openWorkshop:data.maintenance.filter(x=>!["CLOSED","CANCELLED"].includes(x.status)).length,openIncidents:data.incidents.filter(x=>x.status!=="CLOSED").length,complianceWatch:data.compliance.filter(x=>(new Date(x.expiryDate).getTime()-Date.now())/86400000<=60).length}:null,[data]);if(loading)return <div className="loading-screen inline-loading">Loading Vehicle 360…</div>;if(error||!data)return <div className="error-box">{error||"Vehicle profile unavailable."}</div>;const v=data.vehicle;return <>
<section className="page-hero-v2 vehicle360-hero"><div><span className="eyebrow-v2">VEHICLE 360 · SINGLE SOURCE OF TRUTH</span><div className="vehicle360-title"><span className="vehicle360-mark"><Icon name="vehicle" size={26}/></span><div><h2>{v.registrationNumber}</h2><p>{v.make} {v.model} · {v.category} · {v.manufacturingYear}</p></div></div></div><div className="hero-actions-v3"><Link className="button-v2 secondary" to="/vehicles">← Fleet register</Link><Link className="button-v2 primary" to="/assignments"><Icon name="assignment" size={15}/>Manage assignment</Link></div></section>
<div className="vehicle360-statusbar"><span className={`status-pill-v2 s-${v.status}`}><i/>{v.status.replaceAll("_"," ")}</span><span><b>{v.currentOdometerKm.toLocaleString()} km</b> current odometer</span><span><b>{v.currentLocation||"Location unavailable"}</b> last known location</span>{data.telemetry&&<span><b>{date(data.telemetry.recordedAt)}</b> latest telemetry</span>}</div>
<div className="mini-kpi-grid-v2 five-v2"><div><span>Total cost of ownership</span><b>{money(data.economics.tco)}</b><small>{data.economics.costPerKm==null?"Cost/km pending distance":`${money(data.economics.costPerKm)} / km`}</small></div><div><span>Fuel spend</span><b>{money(data.economics.fuelSpend)}</b><small>{data.economics.fuelLitres.toLocaleString(undefined,{maximumFractionDigits:1})} L issued</small></div><div><span>Maintenance spend</span><b>{money(data.economics.maintenanceSpend)}</b><small>{metrics?.openWorkshop} open workshop records</small></div><div className={metrics?.complianceWatch?"warning":"good"}><span>Compliance watch</span><b>{metrics?.complianceWatch}</b><small>Expired / due within 60 days</small></div><div className={metrics?.openIncidents?"danger":"good"}><span>Open incidents</span><b>{metrics?.openIncidents}</b><small>Unresolved safety events</small></div></div>
<div className="vehicle360-grid">
<section className="panel-v2 vehicle360-master"><div className="panel-head-v2"><div><span className="panel-kicker">MASTER DATA</span><h3>Asset identity & accountability</h3></div></div><div className="detail-grid-v2 panel-body-v2"><div><span>Fleet number</span><b>{v.fleetNumber||"—"}</b></div><div><span>VIN / chassis</span><b>{v.vin}</b></div><div><span>Engine</span><b>{v.engineNumber||"—"}</b></div><div><span>Fuel type</span><b>{v.fuelType}</b></div><div><span>Branch</span><b>{v.branch?.name||"—"}</b></div><div><span>Department</span><b>{v.department?.name||"—"}</b></div><div><span>Acquisition value</span><b>{money(data.economics.acquisition)}</b></div><div><span>Explicit lifecycle cost</span><b>{money(data.economics.explicitCost)}</b></div></div>{data.assignment?<div className="assignment-spotlight"><span className="panel-kicker">CURRENT CUSTODIAN</span><div><b>{data.assignment.driver.fullName}</b><small>{data.assignment.driver.employeeNumber} · {data.assignment.assignmentType} · since {date(data.assignment.startAt)}</small></div><Link to={`/drivers/${data.assignment.driver.id}`}>Driver 360 →</Link></div>:<div className="empty-strip">No active driver assignment.</div>}</section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">CONNECTED FLEET</span><h3>Latest telemetry</h3></div><Link to="/telemetry">Telemetry workspace →</Link></div><div className="panel-body-v2">{data.telemetry?<div className="telemetry360-grid"><div><span>Provider</span><b>{data.telemetry.provider}</b></div><div><span>Speed</span><b>{Number(data.telemetry.speedKph??0).toFixed(1)} km/h</b></div><div><span>Fuel</span><b>{data.telemetry.fuelPercent??"—"}%</b></div><div><span>Position</span><b>{Number(data.telemetry.latitude).toFixed(5)}, {Number(data.telemetry.longitude).toFixed(5)}</b></div><div className="span-2"><span>Recorded</span><b>{new Date(data.telemetry.recordedAt).toLocaleString()}</b></div></div>:<div className="empty-state-v2"><Icon name="route" size={24}/><b>No telemetry snapshot</b><span>This vehicle has not reported through a connected provider.</span></div>}</div></section>
</div>
<div className="vehicle360-grid wide-left">
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">MOVEMENT HISTORY</span><h3>Recent trips</h3></div><Link to="/trips">Trip Control →</Link></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Trip</th><th>Route</th><th>Driver</th><th>Status</th><th>Distance</th></tr></thead><tbody>{data.trips.map(x=><tr key={x.id}><td><b>{x.tripNumber}</b><span className="cell-sub-v2">{date(x.requestedDeparture)}</span></td><td><b>{x.origin} → {x.destination}</b><span className="cell-sub-v2">{x.purpose}</span></td><td>{x.driver?.fullName||"—"}</td><td><span className={`status-pill-v2 s-${x.status}`}><i/>{x.status.replaceAll("_"," ")}</span></td><td>{x.distanceKm?.toLocaleString()??"—"} km</td></tr>)}{!data.trips.length&&<tr><td colSpan={5}>No trip history.</td></tr>}</tbody></table></div></section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">SERVICE CONTROL</span><h3>Preventive maintenance</h3></div><Link to="/preventive-maintenance">PM Planning →</Link></div><div className="panel-body-v2 compact-stack">{data.preventiveMaintenance.map(x=><div className="record-card-v6" key={x.id}><div><b>{x.name}</b><small>{x.nextDueAt?`Due ${date(x.nextDueAt)}`:"No calendar due date"}</small></div><span>{x.nextDueKm?`${x.nextDueKm.toLocaleString()} km`:"Time based"}</span></div>)}{!data.preventiveMaintenance.length&&<div className="empty-strip">No active maintenance plan.</div>}</div></section>
</div>
<div className="vehicle360-grid wide-left">
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">WORKSHOP HISTORY</span><h3>Maintenance & repair</h3></div><Link to="/maintenance">Workshop →</Link></div><div className="table-wrap fleet-table-v2"><table><thead><tr><th>Work order</th><th>Work</th><th>Priority</th><th>Status</th><th>Cost</th></tr></thead><tbody>{data.maintenance.map(x=><tr key={x.id}><td><b>{x.workOrderNumber}</b><span className="cell-sub-v2">{date(x.openedAt)}</span></td><td><b>{x.title}</b><span className="cell-sub-v2">{x.category}</span></td><td>{x.priority}</td><td><span className={`status-pill-v2 s-${x.status}`}><i/>{x.status.replaceAll("_"," ")}</span></td><td>{x.totalCost!=null?money(Number(x.totalCost)):"—"}</td></tr>)}{!data.maintenance.length&&<tr><td colSpan={5}>No maintenance history.</td></tr>}</tbody></table></div></section>
<section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">TYRE CONTROL</span><h3>Current fitment</h3></div><Link to="/tyres">Tyres →</Link></div><div className="panel-body-v2 compact-stack">{data.tyres.map(x=><div className="record-card-v6" key={x.id}><div><b>{x.position||"Position not set"}</b><small>{x.brand} {x.size}</small></div><span>{x.serialNumber}<small>{x.currentTreadDepthMm!=null?` · ${Number(x.currentTreadDepthMm).toFixed(1)} mm`:""}</small></span></div>)}{!data.tyres.length&&<div className="empty-strip">No serialized tyres currently fitted.</div>}</div></section>
</div>
<div className="vehicle360-grid"><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">COMPLIANCE VAULT</span><h3>Vehicle documents</h3></div><Link to="/compliance">Compliance →</Link></div><div className="panel-body-v2 compact-stack">{data.compliance.map(x=>{const days=Math.ceil((new Date(x.expiryDate).getTime()-Date.now())/86400000);return <div className={`record-card-v6 ${days<=30?"attention":""}`} key={x.id}><div><b>{x.type.replaceAll("_"," ")}</b><small>{x.provider||"Provider not recorded"} · {x.referenceNumber}</small></div><span>{date(x.expiryDate)}<small>{days<0?` · ${Math.abs(days)}d expired`:` · ${days}d left`}</small></span></div>})}{!data.compliance.length&&<div className="empty-strip">No compliance documents recorded.</div>}</div></section><section className="panel-v2"><div className="panel-head-v2"><div><span className="panel-kicker">SAFETY & RISK</span><h3>Incidents</h3></div><Link to="/incidents">Incidents →</Link></div><div className="panel-body-v2 compact-stack">{data.incidents.slice(0,6).map(x=><div className={`record-card-v6 ${x.status!=="CLOSED"?"attention":""}`} key={x.id}><div><b>{x.incidentNumber} · {x.type}</b><small>{x.location} · {date(x.occurredAt)}</small></div><span>{x.severity}<small> · {x.status}</small></span></div>)}{!data.incidents.length&&<div className="empty-strip">No incidents recorded.</div>}</div></section></div>
{data.disposal&&<div className="manager-control-note-v2 danger-note-v6"><Icon name="alert"/><div><b>Active disposal workflow</b><span>{data.disposal.disposalMethod} · {data.disposal.status} · {data.disposal.reason}</span></div><Link to="/lifecycle">Review disposal →</Link></div>}
</>}
