import type { Prisma } from "@prisma/client";
import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { audit } from "../../lib/audit.js";
import { PERMISSIONS } from "../../domain/permissions.js";
import { validateOdometer } from "../../domain/rules.js";
import { requirePermission } from "../../middleware/authorize.js";

export const preventiveMaintenanceRouter = Router();
function routeId(value:string|string[]|undefined):string|null{return typeof value==="string"?value:null;}
const dayMs=86_400_000;
type DueState="OVERDUE"|"DUE_SOON"|"OK";

async function syncVehicleService(organizationId:string,vehicleId:string){
  const plans=await prisma.preventiveMaintenancePlan.findMany({where:{organizationId,vehicleId,status:"ACTIVE"},select:{nextDueAt:true,nextDueKm:true}});const dates=plans.map(p=>p.nextDueAt).filter((x):x is Date=>Boolean(x));const kms=plans.map(p=>p.nextDueKm).filter((x):x is number=>x!==null);await prisma.vehicle.update({where:{id:vehicleId},data:{nextServiceDueAt:dates.length?new Date(Math.min(...dates.map(d=>d.getTime()))):null,nextServiceDueKm:kms.length?Math.min(...kms):null}});
}

async function enriched(organizationId:string){
  const items=await prisma.preventiveMaintenancePlan.findMany({where:{organizationId},orderBy:[{status:"asc"},{nextDueAt:"asc"}],take:400});const ids=[...new Set(items.map(i=>i.vehicleId))];const vehicles=ids.length?await prisma.vehicle.findMany({where:{id:{in:ids}},select:{id:true,registrationNumber:true,fleetNumber:true,make:true,model:true,currentOdometerKm:true,status:true}}):[];const map=new Map(vehicles.map(v=>[v.id,v]));return items.map(item=>{const vehicle=map.get(item.vehicleId)??null;const daysRemaining=item.nextDueAt?Math.ceil((item.nextDueAt.getTime()-Date.now())/dayMs):null;const kmRemaining=item.nextDueKm!==null&&vehicle?item.nextDueKm-vehicle.currentOdometerKm:null;const overdue=(daysRemaining!==null&&daysRemaining<0)||(kmRemaining!==null&&kmRemaining<0);const dueSoon=!overdue&&((daysRemaining!==null&&daysRemaining<=30)||(kmRemaining!==null&&kmRemaining<=1000));const dueState:DueState=overdue?"OVERDUE":dueSoon?"DUE_SOON":"OK";return{...item,vehicle,daysRemaining,kmRemaining,dueState};});
}

preventiveMaintenanceRouter.get("/",requirePermission(PERMISSIONS.PM_VIEW),async(req,res)=>res.json({items:await enriched(req.auth!.organizationId)}));
preventiveMaintenanceRouter.get("/forecast",requirePermission(PERMISSIONS.PM_VIEW),async(req,res)=>{const items=await enriched(req.auth!.organizationId);const rank:Record<DueState,number>={OVERDUE:0,DUE_SOON:1,OK:2};const active=items.filter(i=>i.status==="ACTIVE").sort((a,b)=>rank[a.dueState]-rank[b.dueState]);return res.json({items:active,summary:{overdue:active.filter(i=>i.dueState==="OVERDUE").length,dueSoon:active.filter(i=>i.dueState==="DUE_SOON").length,healthy:active.filter(i=>i.dueState==="OK").length,total:active.length}});});

preventiveMaintenanceRouter.post("/",requirePermission(PERMISSIONS.PM_MANAGE),async(req,res)=>{
  const input=z.object({vehicleId:z.string().uuid(),name:z.string().min(2).max(200),intervalKm:z.number().int().positive().optional(),intervalDays:z.number().int().positive().optional(),notes:z.string().max(2000).optional()}).refine(v=>v.intervalKm!==undefined||v.intervalDays!==undefined,{message:"At least one maintenance interval is required."}).parse(req.body);const vehicle=await prisma.vehicle.findFirst({where:{id:input.vehicleId,organizationId:req.auth!.organizationId,archivedAt:null}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});const now=new Date();const created=await prisma.preventiveMaintenancePlan.create({data:{organizationId:req.auth!.organizationId,vehicleId:vehicle.id,name:input.name.trim(),status:"ACTIVE",intervalKm:input.intervalKm??null,intervalDays:input.intervalDays??null,nextDueKm:input.intervalKm!==undefined?vehicle.currentOdometerKm+input.intervalKm:null,nextDueAt:input.intervalDays!==undefined?new Date(now.getTime()+input.intervalDays*dayMs):null,createdByUserId:req.auth!.userId,notes:input.notes??null}});await syncVehicleService(req.auth!.organizationId,vehicle.id);await audit(req,{action:"CREATE",recordType:"PM_PLAN",recordId:created.id,newValue:created});return res.status(201).json(created);
});

preventiveMaintenanceRouter.patch("/:id",requirePermission(PERMISSIONS.PM_MANAGE),async(req,res)=>{
  const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid maintenance plan id."});const input=z.object({name:z.string().min(2).max(200).optional(),status:z.enum(["ACTIVE","PAUSED","RETIRED"]).optional(),intervalKm:z.number().int().positive().nullable().optional(),intervalDays:z.number().int().positive().nullable().optional(),notes:z.string().max(2000).nullable().optional()}).parse(req.body);const row=await prisma.preventiveMaintenancePlan.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!row)return res.status(404).json({error:"Preventive maintenance plan not found."});const intervalKm=input.intervalKm===undefined?row.intervalKm:input.intervalKm;const intervalDays=input.intervalDays===undefined?row.intervalDays:input.intervalDays;if(intervalKm===null&&intervalDays===null)return res.status(400).json({error:"At least one maintenance interval is required."});
  const data:Prisma.PreventiveMaintenancePlanUncheckedUpdateInput={};if(input.name!==undefined)data.name=input.name;if(input.status!==undefined)data.status=input.status;if(input.intervalKm!==undefined)data.intervalKm=input.intervalKm;if(input.intervalDays!==undefined)data.intervalDays=input.intervalDays;if(input.notes!==undefined)data.notes=input.notes;
  const updated=await prisma.preventiveMaintenancePlan.update({where:{id:row.id},data});await syncVehicleService(req.auth!.organizationId,row.vehicleId);await audit(req,{action:"UPDATE",recordType:"PM_PLAN",recordId:row.id,oldValue:row,newValue:updated});return res.json(updated);
});

preventiveMaintenanceRouter.post("/:id/complete",requirePermission(PERMISSIONS.PM_MANAGE),async(req,res)=>{
  const id=routeId(req.params.id);if(!id)return res.status(400).json({error:"Invalid maintenance plan id."});const input=z.object({odometerKm:z.number().int().min(0),completedAt:z.coerce.date().optional(),notes:z.string().max(2000).optional()}).parse(req.body);const plan=await prisma.preventiveMaintenancePlan.findFirst({where:{id,organizationId:req.auth!.organizationId}});if(!plan)return res.status(404).json({error:"Preventive maintenance plan not found."});if(plan.status!=="ACTIVE")return res.status(409).json({error:"Only an active maintenance plan can be completed."});const vehicle=await prisma.vehicle.findFirst({where:{id:plan.vehicleId,organizationId:req.auth!.organizationId,archivedAt:null}});if(!vehicle)return res.status(404).json({error:"Vehicle not found."});validateOdometer(vehicle.currentOdometerKm,input.odometerKm);const completedAt=input.completedAt??new Date();const nextDueAt=plan.intervalDays?new Date(completedAt.getTime()+plan.intervalDays*dayMs):null;const nextDueKm=plan.intervalKm?input.odometerKm+plan.intervalKm:null;const updated=await prisma.$transaction(async tx=>{await tx.vehicle.update({where:{id:vehicle.id},data:{currentOdometerKm:input.odometerKm,lastServiceAt:completedAt}});return tx.preventiveMaintenancePlan.update({where:{id:plan.id},data:{lastCompletedAt:completedAt,lastCompletedOdometerKm:input.odometerKm,nextDueAt,nextDueKm,notes:input.notes??plan.notes}});});await syncVehicleService(req.auth!.organizationId,vehicle.id);await prisma.operationalAlert.updateMany({where:{organizationId:req.auth!.organizationId,sourceType:"PM_PLAN",sourceId:plan.id,status:{not:"CLOSED"}},data:{status:"CLOSED",closedByUserId:req.auth!.userId,closedAt:new Date()}});await audit(req,{action:"COMPLETE",recordType:"PM_PLAN",recordId:plan.id,oldValue:{nextDueAt:plan.nextDueAt,nextDueKm:plan.nextDueKm},newValue:{lastCompletedAt:completedAt,lastCompletedOdometerKm:input.odometerKm,nextDueAt,nextDueKm}});return res.json(updated);
});
